# English (Australia) translations for ironic.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ironic project.
#
# Translators:
# Tom Fifield <tom@openstack.org>, 2014
msgid ""
msgstr ""
"Project-Id-Version:  Ironic\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-02 06:14+0000\n"
"PO-Revision-Date: 2014-07-21 23:13+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: English (Australia) "
"(http://www.transifex.com/projects/p/ironic/language/en_AU/)\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ironic/api/controllers/v1/driver.py:115
#: ironic/api/controllers/v1/node.py:554
msgid "Method not specified"
msgstr "Method not specified"

#: ironic/api/controllers/v1/node.py:308
#, python-format
msgid "Node %(node)s is already in the '%(state)s' state."
msgstr "Node %(node)s is already in the '%(state)s' state."

#: ironic/api/controllers/v1/node.py:321
#, python-format
msgid "Node %s is already being provisioned or decommissioned."
msgstr "Node %s is already being provisioned or decommissioned."

#: ironic/api/controllers/v1/node.py:592
msgid "Chassis id not specified."
msgstr "Chassis id not specified."

#: ironic/api/controllers/v1/node.py:773
#, python-format
msgid "Node %s can not be updated while a state transition is in progress."
msgstr "Node %s can not be updated while a state transition is in progress."

#: ironic/api/controllers/v1/port.py:180
msgid "Node id not specified."
msgstr "Node id not specified."

#: ironic/api/controllers/v1/types.py:135
#, python-format
msgid "'%s' is an internal attribute and can not be updated"
msgstr "'%s' is an internal attribute and can not be updated"

#: ironic/api/controllers/v1/types.py:139
#, python-format
msgid "'%s' is a mandatory attribute and can not be removed"
msgstr "'%s' is a mandatory attribute and can not be removed"

#: ironic/api/controllers/v1/types.py:144
msgid "'add' and 'replace' operations needs value"
msgstr "'add' and 'replace' operations needs value"

#: ironic/api/controllers/v1/types.py:175
#, python-format
msgid "Wrong type. Expected '%(type)s', got '%(value)s'"
msgstr "Wrong type. Expected '%(type)s', got '%(value)s'"

#: ironic/api/controllers/v1/utils.py:31
msgid "Limit must be positive"
msgstr "Limit must be positive"

#: ironic/api/controllers/v1/utils.py:38
#, python-format
msgid "Invalid sort direction: %s. Acceptable values are 'asc' or 'desc'"
msgstr "Invalid sort direction: %s. Acceptable values are 'asc' or 'desc'"

#: ironic/api/controllers/v1/utils.py:48
#, python-format
msgid "Adding a new attribute (%s) to the root of  the resource is not allowed"
msgstr "Adding a new attribute (%s) to the root of  the resource is not allowed"

#: ironic/api/middleware/auth_token.py:40
#, python-format
msgid "Cannot compile public API routes: %s"
msgstr "Cannot compile public API routes: %s"

#: ironic/api/middleware/parsable_error.py:52
#, python-format
msgid "ErrorDocumentMiddleware received an invalid status %s"
msgstr "ErrorDocumentMiddleware received an invalid status %s"

#: ironic/api/middleware/parsable_error.py:80
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr "Error parsing HTTP response: %s"

#: ironic/cmd/api.py:53
#, python-format
msgid "Serving on http://%(host)s:%(port)s"
msgstr "Serving on http://%(host)s:%(port)s"

#: ironic/cmd/api.py:55
msgid "Configuration:"
msgstr "Configuration:"

#: ironic/common/disk_partitioner.py:131
#, python-format
msgid "Failed to check the device %(device)s with fuser:  %(err)s"
msgstr ""

#: ironic/common/disk_partitioner.py:164
#, python-format
msgid ""
"Disk partitioning failed on device %(device)s. Processes with the "
"following PIDs are holding it: %(pids)s. Time out waiting for completion."
msgstr ""

#: ironic/common/disk_partitioner.py:170
#, python-format
msgid ""
"Disk partitioning failed on device %(device)s. Fuser exited with "
"\"%(fuser_err)s\". Time out waiting for completion."
msgstr ""

#: ironic/common/disk_partitioner.py:196
#, python-format
msgid ""
"Partition information from parted for device %(device)s does not match "
"expected format: %(line)s"
msgstr ""

#: ironic/common/driver_factory.py:120
#, python-format
msgid "Loaded the following drivers: %s"
msgstr ""

#: ironic/common/exception.py:57
msgid "An unknown exception occurred."
msgstr "An unknown exception occurred."

#: ironic/common/exception.py:78
msgid "Exception in string format operation"
msgstr "Exception in string format operation"

#: ironic/common/exception.py:98
msgid "Not authorized."
msgstr "Not authorised."

#: ironic/common/exception.py:103
msgid "Operation not permitted."
msgstr "Operation not permitted."

#: ironic/common/exception.py:107
msgid "Unacceptable parameters."
msgstr "Unacceptable parameters."

#: ironic/common/exception.py:112
msgid "Conflict."
msgstr "Conflict."

#: ironic/common/exception.py:117
msgid "Resource temporarily unavailable, please retry."
msgstr "Resource temporarily unavailable, please retry."

#: ironic/common/exception.py:122
msgid "Invalid resource state."
msgstr "Invalid resource state."

#: ironic/common/exception.py:126
#, python-format
msgid "A node with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:130
#, python-format
msgid "A port with MAC address %(mac)s already exists."
msgstr ""

#: ironic/common/exception.py:134
#, python-format
msgid "A chassis with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:138
#, python-format
msgid "A port with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:142
#, python-format
msgid ""
"Instance %(instance_uuid)s is already associated with a node, it cannot "
"be associated with this other node %(node)s"
msgstr ""

#: ironic/common/exception.py:147
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr "Expected a uuid but received %(uuid)s."

#: ironic/common/exception.py:151
#, python-format
msgid "Expected an uuid or int but received %(identity)s."
msgstr "Expected an uuid or int but received %(identity)s."

#: ironic/common/exception.py:155
#, python-format
msgid "Expected a MAC address but received %(mac)s."
msgstr "Expected a MAC address but received %(mac)s."

#: ironic/common/exception.py:159
#, python-format
msgid "Invalid state '%(state)s' requested for node %(node)s."
msgstr "Invalid state '%(state)s' requested for node %(node)s."

#: ironic/common/exception.py:163
#, python-format
msgid "Couldn't apply patch '%(patch)s'. Reason: %(reason)s"
msgstr "Couldn't apply patch '%(patch)s'. Reason: %(reason)s"

#: ironic/common/exception.py:167
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr "Failed to deploy instance: %(reason)s"

#: ironic/common/exception.py:171 ironic/common/exception.py:175
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "Image %(image_id)s is unacceptable: %(reason)s"

#: ironic/common/exception.py:181 ironic/common/exception.py:185
#, python-format
msgid "%(err)s"
msgstr "%(err)s"

#: ironic/common/exception.py:189
msgid "Resource could not be found."
msgstr "Resource could not be found."

#: ironic/common/exception.py:194
#, python-format
msgid "Failed to load DHCP provider %(dhcp_provider_name)s."
msgstr ""

#: ironic/common/exception.py:198
#, python-format
msgid "Failed to load driver %(driver_name)s."
msgstr "Failed to load driver %(driver_name)s."

#: ironic/common/exception.py:202
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "Image %(image_id)s could not be found."

#: ironic/common/exception.py:206
#, python-format
msgid "No valid host was found. Reason: %(reason)s"
msgstr "No valid host was found. Reason: %(reason)s"

#: ironic/common/exception.py:210
#, python-format
msgid "Instance %(instance)s could not be found."
msgstr "Instance %(instance)s could not be found."

#: ironic/common/exception.py:214
#, python-format
msgid "Node %(node)s could not be found."
msgstr "Node %(node)s could not be found."

#: ironic/common/exception.py:218
#, python-format
msgid "Node %(node)s is associated with instance %(instance)s."
msgstr "Node %(node)s is associated with instance %(instance)s."

#: ironic/common/exception.py:222
#, python-format
msgid "Port %(port)s could not be found."
msgstr "Port %(port)s could not be found."

#: ironic/common/exception.py:226
#, python-format
msgid "Update DHCP options on port: %(port_id)s failed."
msgstr "Update DHCP options on port: %(port_id)s failed."

#: ironic/common/exception.py:230
#, python-format
msgid "Update MAC address on port: %(port_id)s failed."
msgstr "Update MAC address on port: %(port_id)s failed."

#: ironic/common/exception.py:234
#, python-format
msgid "Chassis %(chassis)s could not be found."
msgstr "Chassis %(chassis)s could not be found."

#: ironic/common/exception.py:238
#, python-format
msgid "Conductor %(conductor)s could not be found."
msgstr "Conductor %(conductor)s could not be found."

#: ironic/common/exception.py:242
#, python-format
msgid "Conductor %(conductor)s already registered."
msgstr "Conductor %(conductor)s already registered."

#: ironic/common/exception.py:246
#, python-format
msgid "Failed to set node power state to %(pstate)s."
msgstr "Failed to set node power state to %(pstate)s."

#: ironic/common/exception.py:250
msgid "An exclusive lock is required, but the current context has a shared lock."
msgstr "An exclusive lock is required, but the current context has a shared lock."

#: ironic/common/exception.py:255
#, python-format
msgid "Failed to toggle maintenance-mode flag for node %(node)s: %(reason)s"
msgstr "Failed to toggle maintenance-mode flag for node %(node)s: %(reason)s"

#: ironic/common/exception.py:260
#, python-format
msgid "Console access is not enabled on node %(node)s"
msgstr "Console access is not enabled on node %(node)s"

#: ironic/common/exception.py:264
#, python-format
msgid ""
"The %(op)s operation can't be performed on node %(node)s because it's in "
"maintenance mode."
msgstr ""
"The %(op)s operation can't be performed on node %(node)s because it's in "
"maintenance mode."

#: ironic/common/exception.py:269
#, python-format
msgid ""
"Can not change instance association while node %(node)s is in power state"
" %(pstate)s."
msgstr ""
"Can not change instance association while node %(node)s is in power state"
" %(pstate)s."

#: ironic/common/exception.py:274
#, python-format
msgid ""
"Cannot complete the requested action because chassis %(chassis)s contains"
" nodes."
msgstr ""
"Cannot complete the requested action because chassis %(chassis)s contains"
" nodes."

#: ironic/common/exception.py:279
#, python-format
msgid "IPMI call failed: %(cmd)s."
msgstr "IPMI call failed: %(cmd)s."

#: ironic/common/exception.py:283
#, python-format
msgid "Failed to establish SSH connection to host %(host)s."
msgstr "Failed to establish SSH connection to host %(host)s."

#: ironic/common/exception.py:287
#, python-format
msgid "Failed to execute command via SSH: %(cmd)s."
msgstr "Failed to execute command via SSH: %(cmd)s."

#: ironic/common/exception.py:291
#, python-format
msgid "Unsupported object type %(objtype)s"
msgstr "Unsupported object type %(objtype)s"

#: ironic/common/exception.py:295
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr "Cannot call %(method)s on orphaned %(objtype)s object"

#: ironic/common/exception.py:299
#, python-format
msgid "Driver %(driver)s does not support %(extension)s."
msgstr "Driver %(driver)s does not support %(extension)s."

#: ironic/common/exception.py:303
#, python-format
msgid "Version %(objver)s of %(objname)s is not supported"
msgstr "Version %(objver)s of %(objname)s is not supported"

#: ironic/common/exception.py:307
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr "Connection to glance host %(host)s:%(port)s failed: %(reason)s"

#: ironic/common/exception.py:312
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "Not authorised for image %(image_id)s."

#: ironic/common/exception.py:316
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "Invalid image href %(image_href)s."

#: ironic/common/exception.py:320
msgid "Unauthorised for keystone service catalog."
msgstr "Unauthorised for keystone service catalog."

#: ironic/common/exception.py:328
#, python-format
msgid ""
"Service type %(service_type)s with endpoint type %(endpoint_type)s not "
"found in keystone service catalog."
msgstr ""
"Service type %(service_type)s with endpoint type %(endpoint_type)s not "
"found in keystone service catalog."

#: ironic/common/exception.py:333
msgid "Connection failed"
msgstr "Connection failed"

#: ironic/common/exception.py:337
msgid "Requested OpenStack Images API is forbidden"
msgstr "Requested OpenStack Images API is forbidden"

#: ironic/common/exception.py:345
msgid "The provided endpoint is invalid"
msgstr "The provided endpoint is invalid"

#: ironic/common/exception.py:349
msgid "Unable to communicate with the server."
msgstr "Unable to communicate with the server."

#: ironic/common/exception.py:365
#, python-format
msgid "Could not find config at %(path)s"
msgstr "Could not find config at %(path)s"

#: ironic/common/exception.py:369
#, python-format
msgid ""
"Node %(node)s is locked by host %(host)s, please retry after the current "
"operation is completed."
msgstr ""
"Node %(node)s is locked by host %(host)s, please retry after the current "
"operation is completed."

#: ironic/common/exception.py:374
#, python-format
msgid "Node %(node)s found not to be locked on release"
msgstr ""

#: ironic/common/exception.py:378
msgid ""
"Requested action cannot be performed due to lack of free conductor "
"workers."
msgstr ""
"Requested action cannot be performed due to lack of free conductor "
"workers."

#: ironic/common/exception.py:388
#, python-format
msgid "Invalid configuration file. %(error_msg)s"
msgstr "Invalid configuration file. %(error_msg)s"

#: ironic/common/exception.py:392
#, python-format
msgid "Driver %(driver)s could not be loaded. Reason: %(reason)s."
msgstr ""

#: ironic/common/exception.py:400
#, python-format
msgid "Could not find pid in pid file %(pid_path)s"
msgstr ""

#: ironic/common/exception.py:404
#, python-format
msgid "Console subprocess failed to start. %(error)s"
msgstr ""

#: ironic/common/exception.py:408
#, python-format
msgid "Failed to create the password file. %(error)s"
msgstr ""

#: ironic/common/exception.py:416
#, python-format
msgid "%(operation)s failed, error: %(error)s"
msgstr ""

#: ironic/common/exception.py:420
#, python-format
msgid ""
"DRAC client failed. Last error (cURL error code): %(last_error)s, fault "
"string: \"%(fault_string)s\" response_code: %(response_code)s"
msgstr ""

#: ironic/common/exception.py:427
#, python-format
msgid "DRAC %(operation)s failed. Reason: %(error)s"
msgstr ""

#: ironic/common/exception.py:431
#, python-format
msgid "Failed to get sensor data for node %(node)s. Error: %(error)s"
msgstr ""

#: ironic/common/exception.py:436
#, python-format
msgid "Failed to parse sensor data for node %(node)s. Error: %(error)s"
msgstr ""

#: ironic/common/exception.py:441
#, python-format
msgid ""
"Disk volume where '%(path)s' is located doesn't have enough disk space. "
"Required %(required)d MiB, only %(actual)d MiB available space present."
msgstr ""

#: ironic/common/exception.py:447
#, python-format
msgid "Creating %(image_type)s image failed: %(error)s"
msgstr ""

#: ironic/common/exception.py:451
#, python-format
msgid "Swift operation '%(operation)s' failed: %(error)s"
msgstr ""

#: ironic/common/hash_ring.py:67
msgid "Invalid hosts supplied when building HashRing."
msgstr "Invalid hosts supplied when building HashRing."

#: ironic/common/hash_ring.py:80
msgid "Invalid data supplied to HashRing.get_hosts."
msgstr "Invalid data supplied to HashRing.get_hosts."

#: ironic/common/hash_ring.py:145
#, python-format
msgid "The driver '%s' is unknown."
msgstr ""

#: ironic/common/images.py:261
msgid "'qemu-img info' parsing failed."
msgstr "'qemu-img info' parsing failed."

#: ironic/common/images.py:267
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr "fmt=%(fmt)s backed by: %(backing_file)s"

#: ironic/common/images.py:282
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr "Converted to raw, but format is now %s"

#: ironic/common/keystone.py:70
msgid "Keystone API endpoint is missing"
msgstr "Keystone API endpoint is missing"

#: ironic/common/keystone.py:90
#, python-format
msgid "Could not perform authorization process for service catalog: %s"
msgstr "Could not perform authorisation process for service catalog: %s"

#: ironic/common/keystone.py:95
msgid "No keystone service catalog loaded"
msgstr "No keystone service catalog loaded"

#: ironic/common/policy.py:31
msgid "JSON file representing policy."
msgstr "JSON file representing policy."

#: ironic/common/policy.py:34
msgid "Rule checked when requested rule is not found."
msgstr "Rule checked when requested rule is not found."

#: ironic/common/service.py:87
#, python-format
msgid "Service error occurred when stopping the RPC server. Error: %s"
msgstr ""

#: ironic/common/service.py:92
#, python-format
msgid "Service error occurred when cleaning up the RPC manager. Error: %s"
msgstr ""

#: ironic/common/swift.py:96
msgid "put container"
msgstr ""

#: ironic/common/swift.py:107
msgid "put object"
msgstr ""

#: ironic/common/swift.py:127
msgid "head account"
msgstr ""

#: ironic/common/swift.py:155
msgid "delete object"
msgstr ""

#: ironic/common/swift.py:171
msgid "head object"
msgstr ""

#: ironic/common/swift.py:186
msgid "post object"
msgstr ""

#: ironic/common/utils.py:98
msgid "Invalid private key"
msgstr "Invalid private key"

#: ironic/common/utils.py:145
#, python-format
msgid "Invalid backend: %s"
msgstr "Invalid backend: %s"

#: ironic/common/utils.py:411
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr "Could not remove tmpdir: %s"

#: ironic/common/utils.py:446
#, python-format
msgid "Failed to unlink %(path)s, error: %(e)s"
msgstr "Failed to unlink %(path)s, error: %(e)s"

#: ironic/common/utils.py:455
#, python-format
msgid "Failed to remove dir %(path)s, error: %(e)s"
msgstr "Failed to remove dir %(path)s, error: %(e)s"

#: ironic/common/utils.py:471
#, python-format
msgid "Failed to create symlink from %(source)s to %(link)s, error: %(e)s"
msgstr "Failed to create symlink from %(source)s to %(link)s, error: %(e)s"

#: ironic/common/utils.py:485
#, python-format
msgid ""
"Failed to remove trailing character. Returning original object. Supplied "
"object is not a string: %s,"
msgstr ""
"Failed to remove trailing character. Returning original object. Supplied "
"object is not a string: %s,"

#: ironic/common/glance_service/base_image_service.py:127
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."

#: ironic/common/glance_service/v2/image_service.py:128
#, python-format
msgid "The given image info does not have a valid image id: %s"
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:154
msgid ""
"Swift temporary URLs require a shared secret to be created. You must "
"provide \"swift_temp_url_key\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:158
msgid ""
"Swift temporary URLs require a Swift endpoint URL. You must provide "
"\"swift_endpoint_url\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:162
msgid ""
"Swift temporary URLs require a Swift account string. You must provide "
"\"swift_account\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:166
msgid "\"swift_temp_url_duration\" must be a positive integer."
msgstr ""

#: ironic/conductor/manager.py:192
#, python-format
msgid ""
"A conductor with hostname %(hostname)s was previously registered. "
"Updating registration"
msgstr ""
"A conductor with hostname %(hostname)s was previously registered. "
"Updating registration"

#: ironic/conductor/manager.py:215
msgid "Failed to start keepalive"
msgstr ""

#: ironic/conductor/manager.py:252
msgid "Invalid method call: update_node can not change node state."
msgstr "Invalid method call: update_node can not change node state."

#: ironic/conductor/manager.py:401
msgid "No free conductor workers available"
msgstr ""

#: ironic/conductor/manager.py:449
#, python-format
msgid ""
"RPC do_node_deploy called to rebuild %(node)s, but provision state is "
"%(curstate)s. State must be one of : %(states)s."
msgstr ""

#: ironic/conductor/manager.py:456
#, python-format
msgid ""
"RPC do_node_deploy called for %(node)s, but provision state is already "
"%(state)s."
msgstr ""
"RPC do_node_deploy called for %(node)s, but provision state is already "
"%(state)s."

#: ironic/conductor/manager.py:462
msgid "provisioning"
msgstr "provisioning"

#: ironic/conductor/manager.py:469
#, python-format
msgid "RPC do_node_deploy failed to validate deploy info. Error: %(msg)s"
msgstr "RPC do_node_deploy failed to validate deploy info. Error: %(msg)s"

#: ironic/conductor/manager.py:499
#, python-format
msgid "Error in deploy of node %(node)s: %(err)s"
msgstr ""

#: ironic/conductor/manager.py:501
#, python-format
msgid "Failed to deploy. Error: %s"
msgstr "Failed to deploy. Error: %s"

#: ironic/conductor/manager.py:544
#, python-format
msgid "RPC do_node_tear_down not allowed for node %(node)s in state %(state)s"
msgstr "RPC do_node_tear_down not allowed for node %(node)s in state %(state)s"

#: ironic/conductor/manager.py:557
#, python-format
msgid "RPC do_node_tear_down failed to validate power info. Error: %(msg)s"
msgstr ""

#: ironic/conductor/manager.py:587
#, python-format
msgid "Error in tear_down of node %(node)s: %(err)s"
msgstr ""

#: ironic/conductor/manager.py:589
#, python-format
msgid "Failed to tear down. Error: %s"
msgstr "Failed to tear down. Error: %s"

#: ironic/conductor/manager.py:616
#, python-format
msgid ""
"During sync_power_state, max retries exceeded for node %(node)s, node "
"state %(actual)s does not match expected state '%(state)s'. Updating DB "
"state to '%(actual)s' Switching node to maintenance mode."
msgstr ""
"During sync_power_state, max retries exceeded for node %(node)s, node "
"state %(actual)s does not match expected state '%(state)s'. Updating DB "
"state to '%(actual)s' Switching node to maintenance mode."

#: ironic/conductor/manager.py:647
#, python-format
msgid ""
"During sync_power_state, could not get power state for node %(node)s. "
"Error: %(err)s."
msgstr ""
"During sync_power_state, could not get power state for node %(node)s. "
"Error: %(err)s."

#: ironic/conductor/manager.py:659
#, python-format
msgid ""
"During sync_power_state, node %(node)s has no previous known state. "
"Recording current state '%(state)s'."
msgstr ""
"During sync_power_state, node %(node)s has no previous known state. "
"Recording current state '%(state)s'."

#: ironic/conductor/manager.py:672
#, python-format
msgid ""
"During sync_power_state, node %(node)s state does not match expected "
"state '%(state)s'. Updating recorded state to '%(actual)s'."
msgstr ""
"During sync_power_state, node %(node)s state does not match expected "
"state '%(state)s'. Updating recorded state to '%(actual)s'."

#: ironic/conductor/manager.py:688
#, python-format
msgid ""
"During sync_power_state, node %(node)s state '%(actual)s' does not match "
"expected state. Changing hardware state to '%(state)s'."
msgstr ""
"During sync_power_state, node %(node)s state '%(actual)s' does not match "
"expected state. Changing hardware state to '%(state)s'."

#: ironic/conductor/manager.py:700
#, python-format
msgid "Failed to change power state of node %(node)s to '%(state)s'."
msgstr "Failed to change power state of node %(node)s to '%(state)s'."

#: ironic/conductor/manager.py:705
#, python-format
msgid "%(left)s attempts remaining to sync_power_state for node %(node)s"
msgstr "%(left)s attempts remaining to sync_power_state for node %(node)s"

#: ironic/conductor/manager.py:762
#, python-format
msgid ""
"During sync_power_state, node %(node)s was not found and presumed deleted"
" by another process."
msgstr ""
"During sync_power_state, node %(node)s was not found and presumed deleted"
" by another process."

#: ironic/conductor/manager.py:766
#, python-format
msgid ""
"During sync_power_state, node %(node)s was already locked by another "
"process. Skip."
msgstr ""
"During sync_power_state, node %(node)s was already locked by another "
"process. Skip."

#: ironic/conductor/manager.py:868
msgid "not supported"
msgstr "not supported"

#: ironic/conductor/manager.py:897
msgid "The node is already in maintenance mode"
msgstr "The node is already in maintenance mode"

#: ironic/conductor/manager.py:898
msgid "The node is not in maintenance mode"
msgstr "The node is not in maintenance mode"

#: ironic/conductor/manager.py:941
#, python-format
msgid "Node %s can't be deleted because it's not powered off"
msgstr "Node %s can't be deleted because it's not powered off"

#: ironic/conductor/manager.py:1015
msgid "enabled"
msgstr "enabled"

#: ironic/conductor/manager.py:1015
msgid "disabled"
msgstr "disabled"

#: ironic/conductor/manager.py:1016
#, python-format
msgid "No console action was triggered because the console is already %s"
msgstr "No console action was triggered because the console is already %s"

#: ironic/conductor/manager.py:1035
msgid "enabling"
msgstr "enabling"

#: ironic/conductor/manager.py:1035
msgid "disabling"
msgstr "disabling"

#: ironic/conductor/manager.py:1036
#, python-format
msgid "Error %(op)s the console on node %(node)s. Reason: %(error)s"
msgstr "Error %(op)s the console on node %(node)s. Reason: %(error)s"

#: ironic/conductor/manager.py:1074
#, python-format
msgid ""
"No VIF found for instance %(instance)s port %(port)s when attempting to "
"update port MAC address."
msgstr ""

#: ironic/conductor/rpcapi.py:93
#, python-format
msgid "No conductor service registered which supports driver %s."
msgstr "No conductor service registered which supports driver %s."

#: ironic/conductor/utils.py:71 ironic/conductor/utils.py:109
#, python-format
msgid "Failed to change power state to '%(target)s'. Error: %(error)s"
msgstr "Failed to change power state to '%(target)s'. Error: %(error)s"

#: ironic/conductor/utils.py:88
#, python-format
msgid ""
"Not going to change_node_power_state because current state = requested "
"state = '%(state)s'."
msgstr ""
"Not going to change_node_power_state because current state = requested "
"state = '%(state)s'."

#: ironic/conductor/utils.py:133
#, python-format
msgid "Timeout reached while waiting for callback for node %s"
msgstr ""

#: ironic/conductor/utils.py:139
#, python-format
msgid "Cleanup failed for node %(node)s after deploy timeout:  %(error)s"
msgstr "Cleanup failed for node %(node)s after deploy timeout:  %(error)s"

#: ironic/conductor/utils.py:151
msgid ""
"Deploy timed out, but an unhandled exception was encountered while "
"aborting. More info may be found in the log file."
msgstr ""
"Deploy timed out, but an unhandled exception was encountered while "
"aborting. More info may be found in the log file."

#: ironic/db/sqlalchemy/api.py:328
msgid "Cannot overwrite UUID for an existing Node."
msgstr ""

#: ironic/db/sqlalchemy/api.py:409
msgid "Cannot overwrite UUID for an existing Port."
msgstr ""

#: ironic/db/sqlalchemy/api.py:472
msgid "Cannot overwrite UUID for an existing Chassis."
msgstr ""

#: ironic/dhcp/neutron.py:69
msgid "Neutron auth_strategy should be either \"noauth\" or \"keystone\"."
msgstr ""

#: ironic/dhcp/neutron.py:113
#, python-format
msgid "Failed to update Neutron port %s."
msgstr "Failed to update Neutron port %s."

#: ironic/dhcp/neutron.py:127
#, python-format
msgid "Failed to update MAC address on Neutron port %s."
msgstr "Failed to update MAC address on Neutron port %s."

#: ironic/dhcp/neutron.py:159
#, python-format
msgid "Failed to set DHCP BOOT options for any port on node %s."
msgstr "Failed to set DHCP BOOT options for any port on node %s."

#: ironic/drivers/base.py:411
#, python-format
msgid "Vendor interface does not support driver vendor_passthru method: %s"
msgstr ""

#: ironic/drivers/drac.py:33 ironic/drivers/fake.py:141
msgid "Unable to import pywsman library"
msgstr ""

#: ironic/drivers/fake.py:129 ironic/drivers/pxe.py:152
msgid "Unable to import proliantutils library"
msgstr ""

#: ironic/drivers/pxe.py:85
msgid "Unable to import pyghmi library"
msgstr ""

#: ironic/drivers/utils.py:21 ironic/drivers/modules/fake.py:35
#, python-format
msgid "Unsupported method (%s) passed through to vendor extension."
msgstr "Unsupported method (%s) passed through to vendor extension."

#: ironic/drivers/utils.py:24 ironic/drivers/modules/fake.py:38
msgid "Method not specified when calling vendor extension."
msgstr "Method not specified when calling vendor extension."

#: ironic/drivers/modules/agent.py:107
#: ironic/drivers/modules/iscsi_deploy.py:263
#, python-format
msgid ""
"Node %s failed to power off while handling deploy failure. This may be a "
"serious condition. Node should be removed from Ironic or put in "
"maintenance mode until the problem is resolved."
msgstr ""
"Node %s failed to power off while handling deploy failure. This may be a "
"serious condition. Node should be removed from Ironic or put in "
"maintenance mode until the problem is resolved."

#: ironic/drivers/modules/agent.py:203
#, python-format
msgid "Node %s failed to validate deploy image info"
msgstr ""

#: ironic/drivers/modules/agent.py:332 ironic/drivers/modules/agent.py:345
#, python-format
msgid "No handler for method %s"
msgstr ""

#: ironic/drivers/modules/agent.py:353
#, python-format
msgid "vendor_passthru failed with method %s"
msgstr ""

#: ironic/drivers/modules/agent.py:383
msgid "Node failed to get image for deploy."
msgstr ""

#: ironic/drivers/modules/agent.py:387
msgid "Node failed to move to active state."
msgstr ""

#: ironic/drivers/modules/agent.py:433
#, python-format
msgid "node %(node)s command status errored: %(error)s"
msgstr ""

#: ironic/drivers/modules/agent.py:489
#, python-format
msgid "Unknown lookup payloadversion: %s"
msgstr ""

#: ironic/drivers/modules/agent.py:521
#, python-format
msgid "Malformed network interfaces lookup: %s"
msgstr ""

#: ironic/drivers/modules/agent.py:549
#, python-format
msgid "No ports matching the given MAC addresses %sexist in the database."
msgstr ""

#: ironic/drivers/modules/agent.py:557
#, python-format
msgid "Could not find matching node for the provided MACs %s."
msgstr ""

#: ironic/drivers/modules/agent.py:593
#, python-format
msgid ""
"Ports matching mac addresses match multiple nodes. MACs: %(macs)s. Port "
"ids: %(port_ids)s"
msgstr ""

#: ironic/drivers/modules/agent_client.py:42
msgid "Agent driver requires agent_url in driver_info"
msgstr ""

#: ironic/drivers/modules/console_utils.py:89
#, python-format
msgid ""
"Cannot create directory '%(path)s' for console PID file. Reason: "
"%(reason)s."
msgstr ""

#: ironic/drivers/modules/console_utils.py:210
#, python-format
msgid ""
"%(exec_error)s\n"
"Command: %(command)s"
msgstr ""

#: ironic/drivers/modules/console_utils.py:227
#, python-format
msgid ""
"Command: %(command)s.\n"
"Exit code: %(return_code)s.\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: ironic/drivers/modules/console_utils.py:238
#, python-format
msgid "Timeout while waiting for console subprocess to start for node %s."
msgstr ""

#: ironic/drivers/modules/console_utils.py:262
#, python-format
msgid "No console pid found for node %s while trying to stop shellinabox console."
msgstr ""

#: ironic/drivers/modules/console_utils.py:266
#, python-format
msgid "Could not stop the console for node '%(node)s'. Reason: %(err)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:228
#, python-format
msgid ""
"Failed to erase beginning of disk for node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:240
#, python-format
msgid ""
"Failed to get disk block count for node %(node)s. Command: %(command)s. "
"Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:253
#, python-format
msgid ""
"Failed to erase the end of the disk on node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:280
#, python-format
msgid "Parent device '%s' not found"
msgstr "Parent device '%s' not found"

#: ironic/drivers/modules/deploy_utils.py:297
#, python-format
msgid "Root device '%s' not found"
msgstr "Root device '%s' not found"

#: ironic/drivers/modules/deploy_utils.py:300
#, python-format
msgid "Swap device '%s' not found"
msgstr "Swap device '%s' not found"

#: ironic/drivers/modules/deploy_utils.py:304
#, python-format
msgid "Ephemeral device '%s' not found"
msgstr "Ephemeral device '%s' not found"

#: ironic/drivers/modules/deploy_utils.py:318
msgid "Failed to detect root device UUID."
msgstr "Failed to detect root device UUID."

#: ironic/drivers/modules/deploy_utils.py:356
#: ironic/drivers/modules/deploy_utils.py:362
#, python-format
msgid "Deploy to address %s failed."
msgstr "Deploy to address %s failed."

#: ironic/drivers/modules/deploy_utils.py:357
#, python-format
msgid "Command: %s"
msgstr "Command: %s"

#: ironic/drivers/modules/deploy_utils.py:358
#, python-format
msgid "StdOut: %r"
msgstr "StdOut: %r"

#: ironic/drivers/modules/deploy_utils.py:359
#, python-format
msgid "StdErr: %r"
msgstr "StdErr: %r"

#: ironic/drivers/modules/deploy_utils.py:397
#, python-format
msgid ""
"%(error_msg)s. The following parameters were not passed to ironic: "
"%(missing_info)s"
msgstr ""

#: ironic/drivers/modules/fake.py:56 ironic/drivers/modules/ipminative.py:272
#, python-format
msgid "set_power_state called with an invalid power state: %s."
msgstr "set_power_state called with an invalid power state: %s."

#: ironic/drivers/modules/fake.py:103
msgid "Parameter 'bar' not passed to method 'first_method'."
msgstr "Parameter 'bar' not passed to method 'first_method'."

#: ironic/drivers/modules/fake.py:131
msgid "Parameter 'bar' not passed to method 'second_method'."
msgstr "Parameter 'bar' not passed to method 'second_method'."

#: ironic/drivers/modules/fake.py:180 ironic/drivers/modules/ipminative.py:338
#: ironic/drivers/modules/ipmitool.py:694
#: ironic/drivers/modules/seamicro.py:541 ironic/drivers/modules/ssh.py:634
#, python-format
msgid "Invalid boot device %s specified."
msgstr "Invalid boot device %s specified."

#: ironic/drivers/modules/iboot.py:39
msgid "IP address of the node. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:40 ironic/drivers/modules/seamicro.py:69
msgid "username. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:41 ironic/drivers/modules/seamicro.py:67
msgid "password. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:44
msgid "iBoot PDU relay id; default is 1. Optional."
msgstr ""

#: ironic/drivers/modules/iboot.py:45
msgid "iBoot PDU port; default is 9100. Optional."
msgstr ""

#: ironic/drivers/modules/iboot.py:55
#, python-format
msgid "The following iBoot credentials were not supplied to iBoot PDU driver: %s."
msgstr ""

#: ironic/drivers/modules/iboot.py:67
msgid "iBoot PDU relay id must be an integer."
msgstr ""

#: ironic/drivers/modules/iboot.py:74
msgid "iBoot PDU port must be an integer."
msgstr ""

#: ironic/drivers/modules/iboot.py:109
#, python-format
msgid ""
"Cannot get power status for node '%(node)s'. iBoot get_relays() returned "
"'%(resp)s'."
msgstr ""

#: ironic/drivers/modules/iboot.py:189 ironic/drivers/modules/ipmitool.py:613
#: ironic/drivers/modules/ssh.py:549
#, python-format
msgid "set_power_state called with invalid power state %s."
msgstr "set_power_state called with invalid power state %s."

#: ironic/drivers/modules/image_cache.py:118
#, python-format
msgid "Master cache miss for image %(uuid)s, starting download"
msgstr ""

#: ironic/drivers/modules/image_cache.py:179
#, python-format
msgid ""
"Cache clean up was unable to reclaim %(required)d MiB of disk space, "
"still %(left)d MiB required"
msgstr ""

#: ironic/drivers/modules/image_cache.py:206
#: ironic/drivers/modules/image_cache.py:244
#, python-format
msgid "Unable to delete file %(name)s from master image cache: %(exc)s"
msgstr ""

#: ironic/drivers/modules/image_cache.py:253
#, python-format
msgid ""
"After cleaning up cache dir %(dir)s cache size %(actual)d is still larger"
" than threshold %(expected)d"
msgstr ""

#: ironic/drivers/modules/ipminative.py:57
msgid "IP of the node's BMC. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:58
msgid "IPMI password. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:59
msgid "IPMI username. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:79
#: ironic/drivers/modules/ipmitool.py:212
#, python-format
msgid "The following IPMI credentials are not supplied to IPMI driver: %s."
msgstr "The following IPMI credentials are not supplied to IPMI driver: %s."

#: ironic/drivers/modules/ipminative.py:105
#, python-format
msgid ""
"IPMI power on failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""
"IPMI power on failed for node %(node_id)s with the following error: "
"%(error)s"

#: ironic/drivers/modules/ipminative.py:135
#, python-format
msgid ""
"IPMI power off failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""
"IPMI power off failed for node %(node_id)s with the following error: "
"%(error)s"

#: ironic/drivers/modules/ipminative.py:167
#, python-format
msgid ""
"IPMI power reboot failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""
"IPMI power reboot failed for node %(node_id)s with the following error: "
"%(error)s"

#: ironic/drivers/modules/ipminative.py:202
#, python-format
msgid ""
"IPMI get power state failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""
"IPMI get power state failed for node %(node_id)s with the following "
"error: %(error)s"

#: ironic/drivers/modules/ipminative.py:216
#, python-format
msgid ""
"IPMI get power state for node %(node_id)s returns the  following details:"
" %(detail)s"
msgstr ""
"IPMI get power state for node %(node_id)s returns the  following details:"
" %(detail)s"

#: ironic/drivers/modules/ipmitool.py:70
msgid "IP address or hostname of the node. Required."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:73
msgid "password. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:74
#, python-format
msgid "privilege level; default is ADMINISTRATOR. One of %s. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:76
msgid "username; default is NULL user. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:77
msgid ""
"bridging_type; default is \"no\". One of \"single\", \"dual\", \"no\". "
"Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:79
msgid ""
"transit channel for bridged request. Required only if ipmi_bridging is "
"set to \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:81
msgid ""
"transit address for bridged request. Required only if ipmi_bridging is "
"set to \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:83
msgid ""
"destination channel for bridged request. Required only if ipmi_bridging "
"is set to \"single\" or \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:86
msgid ""
"destination address for bridged request. Required only if ipmi_bridging "
"is set to \"single\" or \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:89
msgid ""
"local IPMB address for bridged requests. Used only if ipmi_bridging is "
"set to \"single\" or \"dual\". Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:96
msgid "node's UDP port to connect to. Only required for console access."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:233
msgid "IPMI terminal port is not an integer."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:244
#, python-format
msgid ""
"Value for ipmi_bridging is provided as %s, but IPMI bridging is not "
"supported by the IPMI utility installed on host. Ensure ipmitool version "
"is > 1.8.11"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:267
#, python-format
msgid "%(param)s not provided"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:270
#, python-format
msgid ""
"Invalid value for ipmi_bridging: %(bridging_type)s, the valid value can "
"be one of: %(bridging_types)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:278
#, python-format
msgid ""
"Invalid privilege level value:%(priv_level)s, the valid value can be one "
"of %(valid_levels)s"
msgstr ""
"Invalid privilege level value:%(priv_level)s, the valid value can be one "
"of %(valid_levels)s"

#: ironic/drivers/modules/ipmitool.py:402
#, python-format
msgid "IPMI power %(state)s failed for node %(node)s."
msgstr "IPMI power %(state)s failed for node %(node)s."

#: ironic/drivers/modules/ipmitool.py:413
#, python-format
msgid ""
"IPMI power %(state)s timed out after %(tries)s retries on node "
"%(node_id)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:467
#, python-format
msgid "IPMI power status failed for node %(node_id)s with error: %(error)s."
msgstr "IPMI power status failed for node %(node_id)s with error: %(error)s."

#: ironic/drivers/modules/ipmitool.py:507
#, python-format
msgid "parse ipmi sensor data failed, unknown sensor type data: %(sensors_data)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:545
#, python-format
msgid ""
"parse ipmi sensor data failed, get nothing with input data: "
"%(sensors_data)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:558
#: ironic/drivers/modules/ipmitool.py:649
#: ironic/drivers/modules/ipmitool.py:792
#: ironic/drivers/modules/ipmitool.py:927
msgid ""
"Unable to locate usable ipmitool command in the system path when checking"
" ipmitool version"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:818
#, python-format
msgid "IPMI \"raw bytes\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:852
#, python-format
msgid "IPMI \"bmc reset\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:880
msgid "Parameter raw_bytes (string of bytes) was not specified."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:887
#, python-format
msgid "Unsupported method (%s) passed to IPMItool driver."
msgstr "Unsupported method (%s) passed to IPMItool driver."

#: ironic/drivers/modules/ipmitool.py:945
msgid "IPMI terminal port not supplied to IPMI driver."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:120
msgid "Cannot validate iSCSI deploy"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:130
#, python-format
msgid ""
"Cannot validate parameter for iSCSI deploy. Invalid parameter %(param)s. "
"Reason: %(reason)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:136
#, python-format
msgid "'%s' is not an integer value."
msgstr "'%s' is not an integer value."

#: ironic/drivers/modules/iscsi_deploy.py:165
#, python-format
msgid ""
"Root partition is too small for requested image. Image size: %(image_mb)d"
" MB, Root size: %(root_mb)d MB"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:220
msgid "Deploy key does not match"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:236
#, python-format
msgid "Parameters %s were not passed to ironic for deploy."
msgstr "Parameters %s were not passed to ironic for deploy."

#: ironic/drivers/modules/iscsi_deploy.py:296
msgid "Failure in deploy ramdisk."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:310 ironic/drivers/modules/pxe.py:435
msgid "Failed to continue iSCSI deployment."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:369
#, python-format
msgid "Failed to connect to Glance to get the properties of the image %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:373
#, python-format
msgid "Image %s not found in Glance"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:383
#, python-format
msgid "Image %(image)s is missing the following properties: %(properties)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:400 ironic/drivers/modules/ssh.py:496
#, python-format
msgid "Node %s does not have any port associated with it."
msgstr "Node %s does not have any port associated with it."

#: ironic/drivers/modules/iscsi_deploy.py:409
msgid ""
"Couldn't get the URL of the Ironic API service from the configuration "
"file or keystone catalog."
msgstr ""
"Couldn't get the URL of the Ironic API service from the configuration "
"file or keystone catalog."

#: ironic/drivers/modules/pxe.py:88
msgid "UUID (from Glance) of the deployment kernel. Required."
msgstr ""

#: ironic/drivers/modules/pxe.py:90
msgid "UUID (from Glance) of the ramdisk that is mounted at boot time. Required."
msgstr ""

#: ironic/drivers/modules/pxe.py:112
msgid "Cannot validate PXE bootloader"
msgstr ""

#: ironic/drivers/modules/pxe.py:269
msgid "iPXE boot is enabled but no HTTP URL or HTTP root was specified."
msgstr ""

#: ironic/drivers/modules/pxe.py:393
#, python-format
msgid "Unsupported method (%s) passed to PXE driver."
msgstr "Unsupported method (%s) passed to PXE driver."

#: ironic/drivers/modules/seamicro.py:66
msgid "API endpoint. Required."
msgstr ""

#: ironic/drivers/modules/seamicro.py:68
msgid "server ID. Required."
msgstr ""

#: ironic/drivers/modules/seamicro.py:72
msgid "version of SeaMicro API client; default is 2. Optional."
msgstr ""

#: ironic/drivers/modules/seamicro.py:94
#, python-format
msgid "Invalid 'seamicro_api_version' parameter. Reason: %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:109
#, python-format
msgid "SeaMicro driver requires the following to be set: %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:167
#, python-format
msgid "SeaMicro client exception %(msg)s for node %(uuid)s"
msgstr "SeaMicro client exception %(msg)s for node %(uuid)s"

#: ironic/drivers/modules/seamicro.py:203
#, python-format
msgid "Power-on failed for node %s."
msgstr "Power-on failed for node %s."

#: ironic/drivers/modules/seamicro.py:243
#, python-format
msgid "Power-off failed for node %s."
msgstr "Power-off failed for node %s."

#: ironic/drivers/modules/seamicro.py:283
#, python-format
msgid "Reboot failed for node %s."
msgstr "Reboot failed for node %s."

#: ironic/drivers/modules/seamicro.py:308
msgid "Invalid volume id specified"
msgstr "Invalid volume id specified"

#: ironic/drivers/modules/seamicro.py:324
msgid "No storage pools found for ironic"
msgstr "No storage pools found for ironic"

#: ironic/drivers/modules/seamicro.py:388
msgid "set_power_state called with invalid power state."
msgstr "set_power_state called with invalid power state."

#: ironic/drivers/modules/seamicro.py:420
#, python-format
msgid "Unsupported method (%s) passed to SeaMicro driver."
msgstr "Unsupported method (%s) passed to SeaMicro driver."

#: ironic/drivers/modules/seamicro.py:439
msgid "No vlan id provided"
msgstr "No vlan id provided"

#: ironic/drivers/modules/seamicro.py:451
#: ironic/drivers/modules/seamicro.py:487
#, python-format
msgid "SeaMicro client exception: %s"
msgstr "SeaMicro client exception: %s"

#: ironic/drivers/modules/seamicro.py:477
msgid "No volume size provided for creating volume"
msgstr "No volume size provided for creating volume"

#: ironic/drivers/modules/ssh.py:60
msgid "IP address or hostname of the node to ssh into. Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:62
msgid "username to authenticate as. Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:63
msgid ""
"virtualization software to use; one of vbox, virsh, vmware, parallels. "
"Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:67
msgid ""
"private key(s). One of this, ssh_key_filename, or ssh_password must be "
"specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:69
msgid ""
"(list of) filename(s) of optional private key(s) for authentication. One "
"of this, ssh_key_contents, or ssh_password must be specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:72
msgid ""
"password to use for authentication or for unlocking a private key. One of"
" this, ssh_key_contents, or ssh_key_filename must be specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:75
msgid "port on the node to connect to; default is 22. Optional."
msgstr ""

#: ironic/drivers/modules/ssh.py:101
#, python-format
msgid "SSHPowerDriver '%(virt_type)s' is not a valid virt_type."
msgstr ""

#: ironic/drivers/modules/ssh.py:195
#, python-format
msgid "SSHPowerDriver '%(virt_type)s' is not a valid virt_type, "
msgstr "SSHPowerDriver '%(virt_type)s' is not a valid virt_type, "

#: ironic/drivers/modules/ssh.py:286
#, python-format
msgid "SSHPowerDriver requires the following to be set: %s."
msgstr ""

#: ironic/drivers/modules/ssh.py:296
msgid "SSHPowerDriver requires ssh_port to be integer value"
msgstr "SSHPowerDriver requires ssh_port to be integer value"

#: ironic/drivers/modules/ssh.py:317
msgid ""
"SSHPowerDriver requires one and only one of password, key_contents and "
"key_filename to be set."
msgstr ""
"SSHPowerDriver requires one and only one of password, key_contents and "
"key_filename to be set."

#: ironic/drivers/modules/ssh.py:326
#, python-format
msgid "SSH key file %s not found."
msgstr "SSH key file %s not found."

#: ironic/drivers/modules/ssh.py:359
#, python-format
msgid "Node \"%(host)s\" with MAC address %(mac)s not found."
msgstr "Node \"%(host)s\" with MAC address %(mac)s not found."

#: ironic/drivers/modules/ssh.py:501
#, python-format
msgid "SSH connection cannot be established: %s"
msgstr "SSH connection cannot be established: %s"

#: ironic/drivers/modules/drac/common.py:25
msgid "IP address or hostname of the DRAC card. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:26
msgid "username used for authentication. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:27
msgid "password used for authentication. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:30
msgid "port used for WS-Man endpoint; default is 443. Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:31
msgid "path used for WS-Man endpoint; default is \"/wsman\". Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:33
msgid ""
"protocol used for WS-Man endpoint; one of http, https; default is "
"\"https\". Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:58
#, python-format
msgid "'%s' not supplied to DracDriver."
msgstr ""

#: ironic/drivers/modules/drac/common.py:60
#, python-format
msgid "'%s' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:68
msgid "'drac_path' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:74
msgid "'drac_protocol' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:79
msgid "'drac_port' is not an integer value."
msgstr ""

#: ironic/drivers/modules/drac/common.py:82
#: ironic/drivers/modules/ilo/common.py:98
#, python-format
msgid ""
"The following errors were encountered while parsing driver_info:\n"
"%s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:48
msgid "IP address or hostname of the iLO. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:49
msgid "username for the iLO with administrator privileges. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:51
msgid "password for ilo_username. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:54
msgid "port to be used for iLO operations. Optional."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:55
msgid "timeout (in seconds) for iLO operations. Optional."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:82
#, python-format
msgid "'%s' not supplied to IloDriver."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:84
#, python-format
msgid ""
"The following parameters were mising while parsing driver_info:\n"
"%s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:93
#, python-format
msgid "'%s' is not an integer."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:146
msgid "iLO license check"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:65
#, python-format
msgid "iLO get_power_state failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/power.py:68
msgid "iLO get_power_status"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:129
#, python-format
msgid "_set_power_state called with invalid power state '%s'"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:134
#, python-format
msgid ""
"iLO set_power_state failed to set state to %(tstate)s  for node "
"%(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:138
msgid "iLO set_power_state"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:147
#, python-format
msgid "iLO failed to change state to %(tstate)s within %(timeout)s sec"
msgstr ""

#: ironic/nova/scheduler/filters/exact_core_filter.py:36
msgid "VCPUs not set; assuming CPU collection broken"
msgstr "VCPUs not set; assuming CPU collection broken"

#: ironic/nova/virt/ironic/client_wrapper.py:72
msgid "Unable to authenticate Ironic client."
msgstr "Unable to authenticate Ironic client."

#: ironic/nova/virt/ironic/client_wrapper.py:110
#, python-format
msgid ""
"Error contacting Ironic server for '%(method)s'. Attempt %(attempt)d of "
"%(total)d"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:278
#, python-format
msgid ""
"Failed to add deploy parameters on node %(node)s when provisioning the "
"instance %(instance)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:300
#, python-format
msgid "Fail to clean up node %s parameters"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:325
#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr "Failed to provision instance %(inst)s: %(reason)s"

#: ironic/nova/virt/ironic/driver.py:571
#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr "Ironic node uuid not supplied to driver for instance %s."

#: ironic/nova/virt/ironic/driver.py:593
#, python-format
msgid ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"
msgstr ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"

#: ironic/nova/virt/ironic/driver.py:618
#, python-format
msgid "Failed to request Ironic to provision instance %(inst)s: %(reason)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:663
#, python-format
msgid ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."
msgstr ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."

#: ironic/nova/virt/ironic/driver.py:843
#, python-format
msgid ""
"Ironic node: %(id)s virtual to physical interface count  missmatch (Vif "
"count: %(vif_count)d, Pif count: %(pif_count)d)"
msgstr ""
"Ironic node: %(id)s virtual to physical interface count  missmatch (Vif "
"count: %(vif_count)d, Pif count: %(pif_count)d)"

#: ironic/nova/virt/ironic/driver.py:962
#, python-format
msgid "Failed to request Ironic to rebuild instance %(inst)s: %(reason)s"
msgstr ""

#: ironic/objects/base.py:69
#, python-format
msgid "Error setting %(attr)s"
msgstr "Error setting %(attr)s"

#: ironic/objects/base.py:159
msgid "Invalid version string"
msgstr "Invalid version string"

#: ironic/objects/base.py:220
#, python-format
msgid "Unable to instantiate unregistered object type %(objtype)s"
msgstr "Unable to instantiate unregistered object type %(objtype)s"

#: ironic/objects/base.py:349
#, python-format
msgid "Cannot load '%(attrname)s' in the base class"
msgstr "Cannot load '%(attrname)s' in the base class"

#: ironic/objects/base.py:358
msgid "Cannot save anything in the base class"
msgstr "Cannot save anything in the base class"

#: ironic/objects/base.py:390
#, python-format
msgid "%(objname)s object has no attribute '%(attrname)s'"
msgstr ""

#: ironic/objects/conductor.py:58
msgid "Cannot update a conductor record directly."
msgstr "Cannot update a conductor record directly."

#: ironic/objects/utils.py:38
msgid "A datetime.datetime is required here"
msgstr "A datetime.datetime is required here"

#: ironic/objects/utils.py:103
#, python-format
msgid "An object of class %s is required here"
msgstr "An object of class %s is required here"

#: ironic/openstack/common/cliutils.py:271
#, python-format
msgid "No %(name)s with a name or ID of '%(name_or_id)s' exists."
msgstr ""

#: ironic/openstack/common/cliutils.py:279
#, python-format
msgid ""
"Multiple %(name)s matches found for '%(name_or_id)s', use an ID to be "
"more specific."
msgstr ""

#: ironic/openstack/common/gettextutils.py:301
msgid "Message objects do not support addition."
msgstr "Message objects do not support addition."

#: ironic/openstack/common/gettextutils.py:311
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."

#: ironic/openstack/common/imageutils.py:75
#, python-format
msgid "Invalid input value \"%s\"."
msgstr ""

#: ironic/openstack/common/imageutils.py:104
msgid "Snapshot list encountered but no header found!"
msgstr "Snapshot list encountered but no header found!"

#: ironic/openstack/common/lockutils.py:101
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: ironic/openstack/common/log.py:287
#, python-format
msgid "Deprecated: %s"
msgstr "Deprecated: %s"

#: ironic/openstack/common/log.py:396
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr "Error loading logging config %(log_config)s: %(err_msg)s"

#: ironic/openstack/common/log.py:457
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog facility must be one of: %s"

#: ironic/openstack/common/log.py:700
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Fatal call to deprecated config: %(msg)s"

#: ironic/openstack/common/periodic_task.py:40
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr "Unexpected argument for periodic task creation: %(arg)s."

#: ironic/openstack/common/policy.py:395
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr "Failed to understand rule %(rule)s"

#: ironic/openstack/common/policy.py:405
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No handler for matches of kind %s"

#: ironic/openstack/common/policy.py:680
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr "Failed to understand rule %(rule)r"

#: ironic/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: ironic/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: ironic/openstack/common/processutils.py:143
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: ironic/openstack/common/processutils.py:148
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: ironic/openstack/common/processutils.py:245
msgid "Environment not supported over SSH"
msgstr "Environment not supported over SSH"

#: ironic/openstack/common/processutils.py:249
msgid "process_input not supported over SSH"
msgstr "process_input not supported over SSH"

#: ironic/openstack/common/strutils.py:114
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr "Unrecognised value '%(val)s', acceptable values are: %(acceptable)s"

#: ironic/openstack/common/strutils.py:219
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: ironic/openstack/common/strutils.py:228
#, python-format
msgid "Invalid string format: %s"
msgstr "Invalid string format: %s"

#: ironic/openstack/common/versionutils.py:88
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: ironic/openstack/common/versionutils.py:92
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: ironic/openstack/common/versionutils.py:96
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: ironic/openstack/common/versionutils.py:99
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: ironic/openstack/common/apiclient/base.py:224
#: ironic/openstack/common/apiclient/base.py:381
#, python-format
msgid "No %(name)s matching %(args)s."
msgstr ""

#: ironic/openstack/common/apiclient/client.py:233
msgid "Cannot find endpoint or token for request"
msgstr ""

#: ironic/openstack/common/apiclient/client.py:356
#, python-format
msgid ""
"Invalid %(api_name)s client version '%(version)s'. Must be one of: "
"%(version_map)s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:41
#, python-format
msgid "Missing arguments: %s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:74
#, python-format
msgid "Authentication failed. Missing options: %s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:83
#, python-format
msgid "AuthSystemNotFound: %s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:106
#, python-format
msgid "AmbiguousEndpoints: %s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:114
msgid "HTTP Error"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:134
msgid "HTTP Redirection"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:142
msgid "HTTP Client Error"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:151
msgid "HTTP Server Error"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:161
msgid "Multiple Choices"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:170
msgid "Bad Request"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:180
msgid "Unauthorized"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:189
msgid "Payment Required"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:199
msgid "Forbidden"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:209
msgid "Not Found"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:219
msgid "Method Not Allowed"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:229
msgid "Not Acceptable"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:238
msgid "Proxy Authentication Required"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:247
msgid "Request Timeout"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:257
msgid "Conflict"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:267
msgid "Gone"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:277
msgid "Length Required"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:287
msgid "Precondition Failed"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:296
msgid "Request Entity Too Large"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:313
msgid "Request-URI Too Long"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:323
msgid "Unsupported Media Type"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:333
msgid "Requested Range Not Satisfiable"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:342
msgid "Expectation Failed"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:352
msgid "Unprocessable Entity"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:361
msgid "Internal Server Error"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:372
msgid "Not Implemented"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:382
msgid "Bad Gateway"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:391
msgid "Service Unavailable"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:401
msgid "Gateway Timeout"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:410
msgid "HTTP Version Not Supported"
msgstr ""

#: ironic/tests/db/sqlalchemy/test_migrations.py:171
#, python-format
msgid "Failed to migrate to version %(version)s on engine %(engine)s"
msgstr "Failed to migrate to version %(version)s on engine %(engine)s"

