# English (Australia) translations for ironic.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ironic project.
#
# Translators:
# Tom Fifield <tom@openstack.org>, 2014
msgid ""
msgstr ""
"Project-Id-Version:  Ironic\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-05-23 06:02+0000\n"
"PO-Revision-Date: 2014-05-21 12:40+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: English (Australia) "
"(http://www.transifex.com/projects/p/ironic/language/en_AU/)\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ironic/api/controllers/v1/driver.py:104
#: ironic/api/controllers/v1/node.py:476
msgid "Method not specified"
msgstr "Method not specified"

#: ironic/api/controllers/v1/node.py:226
#, python-format
msgid "Node %(node)s is already in the '%(state)s' state."
msgstr "Node %(node)s is already in the '%(state)s' state."

#: ironic/api/controllers/v1/node.py:239
#, python-format
msgid "Node %s is already being provisioned or decommissioned."
msgstr "Node %s is already being provisioned or decommissioned."

#: ironic/api/controllers/v1/node.py:506
msgid "Chassis id not specified."
msgstr "Chassis id not specified."

#: ironic/api/controllers/v1/node.py:682
#, python-format
msgid "Node %s can not be updated while a state transition is in progress."
msgstr "Node %s can not be updated while a state transition is in progress."

#: ironic/api/controllers/v1/port.py:169
msgid "Node id not specified."
msgstr "Node id not specified."

#: ironic/api/controllers/v1/types.py:135
#, python-format
msgid "'%s' is an internal attribute and can not be updated"
msgstr "'%s' is an internal attribute and can not be updated"

#: ironic/api/controllers/v1/types.py:139
#, python-format
msgid "'%s' is a mandatory attribute and can not be removed"
msgstr "'%s' is a mandatory attribute and can not be removed"

#: ironic/api/controllers/v1/types.py:144
msgid "'add' and 'replace' operations needs value"
msgstr "'add' and 'replace' operations needs value"

#: ironic/api/controllers/v1/types.py:175
#, python-format
msgid "Wrong type. Expected '%(type)s', got '%(value)s'"
msgstr "Wrong type. Expected '%(type)s', got '%(value)s'"

#: ironic/api/controllers/v1/utils.py:31
msgid "Limit must be positive"
msgstr "Limit must be positive"

#: ironic/api/controllers/v1/utils.py:38
#, python-format
msgid "Invalid sort direction: %s. Acceptable values are 'asc' or 'desc'"
msgstr "Invalid sort direction: %s. Acceptable values are 'asc' or 'desc'"

#: ironic/api/controllers/v1/utils.py:48
#, python-format
msgid "Adding a new attribute (%s) to the root of  the resource is not allowed"
msgstr "Adding a new attribute (%s) to the root of  the resource is not allowed"

#: ironic/api/middleware/auth_token.py:40
#, python-format
msgid "Cannot compile public API routes: %s"
msgstr "Cannot compile public API routes: %s"

#: ironic/api/middleware/parsable_error.py:52
#, python-format
msgid "ErrorDocumentMiddleware received an invalid status %s"
msgstr "ErrorDocumentMiddleware received an invalid status %s"

#: ironic/api/middleware/parsable_error.py:80
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr "Error parsing HTTP response: %s"

#: ironic/cmd/api.py:53
#, python-format
msgid "Serving on http://%(host)s:%(port)s"
msgstr "Serving on http://%(host)s:%(port)s"

#: ironic/cmd/api.py:55
msgid "Configuration:"
msgstr "Configuration:"

#: ironic/common/driver_factory.py:114
#, python-format
msgid "Loaded the following drivers: %s"
msgstr ""

#: ironic/common/exception.py:57
msgid "An unknown exception occurred."
msgstr "An unknown exception occurred."

#: ironic/common/exception.py:78
msgid "Exception in string format operation"
msgstr "Exception in string format operation"

#: ironic/common/exception.py:98
msgid "Not authorized."
msgstr "Not authorised."

#: ironic/common/exception.py:103
msgid "Operation not permitted."
msgstr "Operation not permitted."

#: ironic/common/exception.py:107
msgid "Unacceptable parameters."
msgstr "Unacceptable parameters."

#: ironic/common/exception.py:112
msgid "Conflict."
msgstr "Conflict."

#: ironic/common/exception.py:117
msgid "Resource temporarily unavailable, please retry."
msgstr "Resource temporarily unavailable, please retry."

#: ironic/common/exception.py:122
msgid "Invalid resource state."
msgstr "Invalid resource state."

#: ironic/common/exception.py:126
#, python-format
msgid "A Port with MAC address %(mac)s already exists."
msgstr "A Port with MAC address %(mac)s already exists."

#: ironic/common/exception.py:130
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr "Expected a uuid but received %(uuid)s."

#: ironic/common/exception.py:134
#, python-format
msgid "Expected an uuid or int but received %(identity)s."
msgstr "Expected an uuid or int but received %(identity)s."

#: ironic/common/exception.py:138
#, python-format
msgid "Expected a MAC address but received %(mac)s."
msgstr "Expected a MAC address but received %(mac)s."

#: ironic/common/exception.py:142
#, python-format
msgid "Invalid state '%(state)s' requested for node %(node)s."
msgstr "Invalid state '%(state)s' requested for node %(node)s."

#: ironic/common/exception.py:146
#, python-format
msgid "Couldn't apply patch '%(patch)s'. Reason: %(reason)s"
msgstr "Couldn't apply patch '%(patch)s'. Reason: %(reason)s"

#: ironic/common/exception.py:150
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr "Failed to deploy instance: %(reason)s"

#: ironic/common/exception.py:154 ironic/common/exception.py:158
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr "Image %(image_id)s is unacceptable: %(reason)s"

#: ironic/common/exception.py:164
#, python-format
msgid "%(err)s"
msgstr "%(err)s"

#: ironic/common/exception.py:168
msgid "Resource could not be found."
msgstr "Resource could not be found."

#: ironic/common/exception.py:173
#, python-format
msgid "Failed to load driver %(driver_name)s."
msgstr "Failed to load driver %(driver_name)s."

#: ironic/common/exception.py:177
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr "Image %(image_id)s could not be found."

#: ironic/common/exception.py:181
#, python-format
msgid "No valid host was found. Reason: %(reason)s"
msgstr "No valid host was found. Reason: %(reason)s"

#: ironic/common/exception.py:185
#, python-format
msgid "Instance %(instance)s could not be found."
msgstr "Instance %(instance)s could not be found."

#: ironic/common/exception.py:189
#, python-format
msgid "Node %(node)s could not be found."
msgstr "Node %(node)s could not be found."

#: ironic/common/exception.py:193
#, python-format
msgid "Node %(node)s is associated with instance %(instance)s."
msgstr "Node %(node)s is associated with instance %(instance)s."

#: ironic/common/exception.py:197
#, python-format
msgid "Port %(port)s could not be found."
msgstr "Port %(port)s could not be found."

#: ironic/common/exception.py:201
#, python-format
msgid "Update DHCP options on port: %(port_id)s failed."
msgstr "Update DHCP options on port: %(port_id)s failed."

#: ironic/common/exception.py:205
#, python-format
msgid "Update MAC address on port: %(port_id)s failed."
msgstr "Update MAC address on port: %(port_id)s failed."

#: ironic/common/exception.py:209
#, python-format
msgid "Chassis %(chassis)s could not be found."
msgstr "Chassis %(chassis)s could not be found."

#: ironic/common/exception.py:213
#, python-format
msgid "Conductor %(conductor)s could not be found."
msgstr "Conductor %(conductor)s could not be found."

#: ironic/common/exception.py:217
#, python-format
msgid "Conductor %(conductor)s already registered."
msgstr "Conductor %(conductor)s already registered."

#: ironic/common/exception.py:221
#, python-format
msgid "Failed to set node power state to %(pstate)s."
msgstr "Failed to set node power state to %(pstate)s."

#: ironic/common/exception.py:225
msgid "An exclusive lock is required, but the current context has a shared lock."
msgstr "An exclusive lock is required, but the current context has a shared lock."

#: ironic/common/exception.py:230
#, python-format
msgid "Failed to toggle maintenance-mode flag for node %(node)s: %(reason)s"
msgstr "Failed to toggle maintenance-mode flag for node %(node)s: %(reason)s"

#: ironic/common/exception.py:235
#, python-format
msgid "Console access is not enabled on node %(node)s"
msgstr "Console access is not enabled on node %(node)s"

#: ironic/common/exception.py:239
#, python-format
msgid ""
"The %(op)s operation can't be performed on node %(node)s because it's in "
"maintenance mode."
msgstr ""
"The %(op)s operation can't be performed on node %(node)s because it's in "
"maintenance mode."

#: ironic/common/exception.py:244
#, python-format
msgid ""
"Can not change instance association while node %(node)s is in power state"
" %(pstate)s."
msgstr ""
"Can not change instance association while node %(node)s is in power state"
" %(pstate)s."

#: ironic/common/exception.py:249
#, python-format
msgid ""
"Cannot complete the requested action because chassis %(chassis)s contains"
" nodes."
msgstr ""
"Cannot complete the requested action because chassis %(chassis)s contains"
" nodes."

#: ironic/common/exception.py:254
#, python-format
msgid "IPMI call failed: %(cmd)s."
msgstr "IPMI call failed: %(cmd)s."

#: ironic/common/exception.py:258
#, python-format
msgid "Failed to establish SSH connection to host %(host)s."
msgstr "Failed to establish SSH connection to host %(host)s."

#: ironic/common/exception.py:262
#, python-format
msgid "Failed to execute command via SSH: %(cmd)s."
msgstr "Failed to execute command via SSH: %(cmd)s."

#: ironic/common/exception.py:266
#, python-format
msgid "Unsupported object type %(objtype)s"
msgstr "Unsupported object type %(objtype)s"

#: ironic/common/exception.py:270
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr "Cannot call %(method)s on orphaned %(objtype)s object"

#: ironic/common/exception.py:274
#, python-format
msgid "Driver %(driver)s does not support %(extension)s."
msgstr "Driver %(driver)s does not support %(extension)s."

#: ironic/common/exception.py:278
#, python-format
msgid "Version %(objver)s of %(objname)s is not supported"
msgstr "Version %(objver)s of %(objname)s is not supported"

#: ironic/common/exception.py:282
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr "Connection to glance host %(host)s:%(port)s failed: %(reason)s"

#: ironic/common/exception.py:287
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr "Not authorised for image %(image_id)s."

#: ironic/common/exception.py:291
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr "Invalid image href %(image_href)s."

#: ironic/common/exception.py:295
msgid "Unauthorised for keystone service catalog."
msgstr "Unauthorised for keystone service catalog."

#: ironic/common/exception.py:303
#, python-format
msgid ""
"Service type %(service_type)s with endpoint type %(endpoint_type)s not "
"found in keystone service catalog."
msgstr ""
"Service type %(service_type)s with endpoint type %(endpoint_type)s not "
"found in keystone service catalog."

#: ironic/common/exception.py:308
msgid "Connection failed"
msgstr "Connection failed"

#: ironic/common/exception.py:312
msgid "Requested OpenStack Images API is forbidden"
msgstr "Requested OpenStack Images API is forbidden"

#: ironic/common/exception.py:320
msgid "The provided endpoint is invalid"
msgstr "The provided endpoint is invalid"

#: ironic/common/exception.py:324
msgid "Unable to communicate with the server."
msgstr "Unable to communicate with the server."

#: ironic/common/exception.py:340
#, python-format
msgid "Could not find config at %(path)s"
msgstr "Could not find config at %(path)s"

#: ironic/common/exception.py:344
#, python-format
msgid ""
"Node %(node)s is locked by host %(host)s, please retry after the current "
"operation is completed."
msgstr ""
"Node %(node)s is locked by host %(host)s, please retry after the current "
"operation is completed."

#: ironic/common/exception.py:349
msgid ""
"Requested action cannot be performed due to lack of free conductor "
"workers."
msgstr ""
"Requested action cannot be performed due to lack of free conductor "
"workers."

#: ironic/common/exception.py:359
#, python-format
msgid "Invalid configuration file. %(error_msg)s"
msgstr "Invalid configuration file. %(error_msg)s"

#: ironic/common/exception.py:363
#, python-format
msgid "Driver %(driver)s could not be loaded. Reason: %(reason)s."
msgstr ""

#: ironic/common/exception.py:367
#, python-format
msgid "Could not find pid in pid file %(pid_path)s"
msgstr ""

#: ironic/common/exception.py:371
#, python-format
msgid "Console subprocess failed to start. %(error)s"
msgstr ""

#: ironic/common/exception.py:375
#, python-format
msgid "Failed to create the password file. %(error)s"
msgstr ""

#: ironic/common/hash_ring.py:67
msgid "Invalid hosts supplied when building HashRing."
msgstr "Invalid hosts supplied when building HashRing."

#: ironic/common/hash_ring.py:80
msgid "Invalid data supplied to HashRing.get_hosts."
msgstr "Invalid data supplied to HashRing.get_hosts."

#: ironic/common/images.py:110
msgid "Snapshot list encountered but no header found!"
msgstr "Snapshot list encountered but no header found!"

#: ironic/common/images.py:203
msgid "'qemu-img info' parsing failed."
msgstr "'qemu-img info' parsing failed."

#: ironic/common/images.py:209
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr "fmt=%(fmt)s backed by: %(backing_file)s"

#: ironic/common/images.py:224
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr "Converted to raw, but format is now %s"

#: ironic/common/keystone.py:30
msgid "Keystone API endpoint is missing"
msgstr "Keystone API endpoint is missing"

#: ironic/common/keystone.py:53
#, python-format
msgid "Could not perform authorization process for service catalog: %s"
msgstr "Could not perform authorisation process for service catalog: %s"

#: ironic/common/keystone.py:58
msgid "No keystone service catalog loaded"
msgstr "No keystone service catalog loaded"

#: ironic/common/neutron.py:91
#, python-format
msgid "Failed to update Neutron port %s."
msgstr "Failed to update Neutron port %s."

#: ironic/common/neutron.py:105
#, python-format
msgid "Failed to update MAC address on Neutron port %s."
msgstr "Failed to update MAC address on Neutron port %s."

#: ironic/common/policy.py:31
msgid "JSON file representing policy."
msgstr "JSON file representing policy."

#: ironic/common/policy.py:34
msgid "Rule checked when requested rule is not found."
msgstr "Rule checked when requested rule is not found."

#: ironic/common/service.py:84
#, python-format
msgid "Service error occurred when stopping the RPC server. Error: %s"
msgstr ""

#: ironic/common/service.py:89
#, python-format
msgid "Service error occurred when cleaning up the RPC manager. Error: %s"
msgstr ""

#: ironic/common/utils.py:98
msgid "Invalid private key"
msgstr "Invalid private key"

#: ironic/common/utils.py:145
#, python-format
msgid "Invalid backend: %s"
msgstr "Invalid backend: %s"

#: ironic/common/utils.py:411
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr "Could not remove tmpdir: %s"

#: ironic/common/utils.py:446
#, python-format
msgid "Failed to unlink %(path)s, error: %(e)s"
msgstr "Failed to unlink %(path)s, error: %(e)s"

#: ironic/common/utils.py:455
#, python-format
msgid "Failed to remove dir %(path)s, error: %(e)s"
msgstr "Failed to remove dir %(path)s, error: %(e)s"

#: ironic/common/utils.py:471
#, python-format
msgid "Failed to create symlink from %(source)s to %(link)s, error: %(e)s"
msgstr "Failed to create symlink from %(source)s to %(link)s, error: %(e)s"

#: ironic/common/utils.py:485
#, python-format
msgid ""
"Failed to remove trailing character. Returning original object. Supplied "
"object is not a string: %s,"
msgstr ""
"Failed to remove trailing character. Returning original object. Supplied "
"object is not a string: %s,"

#: ironic/common/glance_service/base_image_service.py:127
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."

#: ironic/conductor/manager.py:148
#, python-format
msgid ""
"A conductor with hostname %(hostname)s was previously registered. "
"Updating registration"
msgstr ""
"A conductor with hostname %(hostname)s was previously registered. "
"Updating registration"

#: ironic/conductor/manager.py:191
msgid "Invalid method call: update_node can not change node state."
msgstr "Invalid method call: update_node can not change node state."

#: ironic/conductor/manager.py:353
#, python-format
msgid ""
"RPC do_node_deploy called to rebuild %(node)s, but provision state is "
"%(curstate)s. Must be %(state)s."
msgstr ""

#: ironic/conductor/manager.py:359
#, python-format
msgid ""
"RPC do_node_deploy called for %(node)s, but provision state is already "
"%(state)s."
msgstr ""
"RPC do_node_deploy called for %(node)s, but provision state is already "
"%(state)s."

#: ironic/conductor/manager.py:365
msgid "provisioning"
msgstr "provisioning"

#: ironic/conductor/manager.py:371
#, python-format
msgid "RPC do_node_deploy failed to validate deploy info. Error: %(msg)s"
msgstr "RPC do_node_deploy failed to validate deploy info. Error: %(msg)s"

#: ironic/conductor/manager.py:391
#, python-format
msgid "Failed to deploy. Error: %s"
msgstr "Failed to deploy. Error: %s"

#: ironic/conductor/manager.py:429
#, python-format
msgid "RPC do_node_tear_down not allowed for node %(node)s in state %(state)s"
msgstr "RPC do_node_tear_down not allowed for node %(node)s in state %(state)s"

#: ironic/conductor/manager.py:437
#, python-format
msgid "RPC do_node_tear_down failed to validate deploy info. Error: %(msg)s"
msgstr "RPC do_node_tear_down failed to validate deploy info. Error: %(msg)s"

#: ironic/conductor/manager.py:456
#, python-format
msgid "Failed to tear down. Error: %s"
msgstr "Failed to tear down. Error: %s"

#: ironic/conductor/manager.py:477
#, python-format
msgid ""
"During sync_power_state, max retries exceeded for node %(node)s, node "
"state %(actual)s does not match expected state '%(state)s'. Updating DB "
"state to '%(actual)s' Switching node to maintenance mode."
msgstr ""
"During sync_power_state, max retries exceeded for node %(node)s, node "
"state %(actual)s does not match expected state '%(state)s'. Updating DB "
"state to '%(actual)s' Switching node to maintenance mode."

#: ironic/conductor/manager.py:507
#, python-format
msgid ""
"During sync_power_state, could not get power state for node %(node)s. "
"Error: %(err)s."
msgstr ""
"During sync_power_state, could not get power state for node %(node)s. "
"Error: %(err)s."

#: ironic/conductor/manager.py:519
#, python-format
msgid ""
"During sync_power_state, node %(node)s has no previous known state. "
"Recording current state '%(state)s'."
msgstr ""
"During sync_power_state, node %(node)s has no previous known state. "
"Recording current state '%(state)s'."

#: ironic/conductor/manager.py:532
#, python-format
msgid ""
"During sync_power_state, node %(node)s state does not match expected "
"state '%(state)s'. Updating recorded state to '%(actual)s'."
msgstr ""
"During sync_power_state, node %(node)s state does not match expected "
"state '%(state)s'. Updating recorded state to '%(actual)s'."

#: ironic/conductor/manager.py:548
#, python-format
msgid ""
"During sync_power_state, node %(node)s state '%(actual)s' does not match "
"expected state. Changing hardware state to '%(state)s'."
msgstr ""
"During sync_power_state, node %(node)s state '%(actual)s' does not match "
"expected state. Changing hardware state to '%(state)s'."

#: ironic/conductor/manager.py:561
#, python-format
msgid "Failed to change power state of node %(node)s to '%(state)s'."
msgstr "Failed to change power state of node %(node)s to '%(state)s'."

#: ironic/conductor/manager.py:566
#, python-format
msgid "%(left)s attempts remaining to sync_power_state for node %(node)s"
msgstr "%(left)s attempts remaining to sync_power_state for node %(node)s"

#: ironic/conductor/manager.py:623
#, python-format
msgid ""
"During sync_power_state, node %(node)s was not found and presumed deleted"
" by another process."
msgstr ""
"During sync_power_state, node %(node)s was not found and presumed deleted"
" by another process."

#: ironic/conductor/manager.py:627
#, python-format
msgid ""
"During sync_power_state, node %(node)s was already locked by another "
"process. Skip."
msgstr ""
"During sync_power_state, node %(node)s was already locked by another "
"process. Skip."

#: ironic/conductor/manager.py:716
msgid "not supported"
msgstr "not supported"

#: ironic/conductor/manager.py:745
msgid "The node is already in maintenance mode"
msgstr "The node is already in maintenance mode"

#: ironic/conductor/manager.py:746
msgid "The node is not in maintenance mode"
msgstr "The node is not in maintenance mode"

#: ironic/conductor/manager.py:789
#, python-format
msgid "Node %s can't be deleted because it's not powered off"
msgstr "Node %s can't be deleted because it's not powered off"

#: ironic/conductor/manager.py:857
msgid "enabled"
msgstr "enabled"

#: ironic/conductor/manager.py:857
msgid "disabled"
msgstr "disabled"

#: ironic/conductor/manager.py:858
#, python-format
msgid "No console action was triggered because the console is already %s"
msgstr "No console action was triggered because the console is already %s"

#: ironic/conductor/manager.py:877
msgid "enabling"
msgstr "enabling"

#: ironic/conductor/manager.py:877
msgid "disabling"
msgstr "disabling"

#: ironic/conductor/manager.py:878
#, python-format
msgid "Error %(op)s the console on node %(node)s. Reason: %(error)s"
msgstr "Error %(op)s the console on node %(node)s. Reason: %(error)s"

#: ironic/conductor/manager.py:912
#, python-format
msgid ""
"No VIF found for instance %(instance)s port %(port)s when attempting to "
"update Neutron port MAC address."
msgstr ""
"No VIF found for instance %(instance)s port %(port)s when attempting to "
"update Neutron port MAC address."

#: ironic/conductor/rpcapi.py:90
#, python-format
msgid "No conductor service registered which supports driver %s."
msgstr "No conductor service registered which supports driver %s."

#: ironic/conductor/task_manager.py:200
msgid "Multi-node TaskManager has no attribute 'node'"
msgstr "Multi-node TaskManager has no attribute 'node'"

#: ironic/conductor/task_manager.py:209
msgid "Multi-node TaskManager has no attribute 'ports'"
msgstr "Multi-node TaskManager has no attribute 'ports'"

#: ironic/conductor/task_manager.py:218
msgid "Multi-node TaskManager has no attribute 'driver'"
msgstr "Multi-node TaskManager has no attribute 'driver'"

#: ironic/conductor/task_manager.py:227
msgid "Multi-node TaskManager can't select single node manager from the list"
msgstr "Multi-node TaskManager can't select single node manager from the list"

#: ironic/conductor/utils.py:71 ironic/conductor/utils.py:109
#, python-format
msgid "Failed to change power state to '%(target)s'. Error: %(error)s"
msgstr "Failed to change power state to '%(target)s'. Error: %(error)s"

#: ironic/conductor/utils.py:88
#, python-format
msgid ""
"Not going to change_node_power_state because current state = requested "
"state = '%(state)s'."
msgstr ""
"Not going to change_node_power_state because current state = requested "
"state = '%(state)s'."

#: ironic/conductor/utils.py:130
#, python-format
msgid "Timeout reached while waiting for callback for node %s"
msgstr ""

#: ironic/conductor/utils.py:136
#, python-format
msgid "Cleanup failed for node %(node)s after deploy timeout:  %(error)s"
msgstr "Cleanup failed for node %(node)s after deploy timeout:  %(error)s"

#: ironic/conductor/utils.py:148
msgid ""
"Deploy timed out, but an unhandled exception was encountered while "
"aborting. More info may be found in the log file."
msgstr ""
"Deploy timed out, but an unhandled exception was encountered while "
"aborting. More info may be found in the log file."

#: ironic/drivers/base.py:355
#, python-format
msgid "Vendor interface does not support driver vendor_passthru method: %s"
msgstr ""

#: ironic/drivers/utils.py:21 ironic/drivers/modules/fake.py:35
#, python-format
msgid "Unsupported method (%s) passed through to vendor extension."
msgstr "Unsupported method (%s) passed through to vendor extension."

#: ironic/drivers/utils.py:24 ironic/drivers/modules/fake.py:38
msgid "Method not specified when calling vendor extension."
msgstr "Method not specified when calling vendor extension."

#: ironic/drivers/modules/console_utils.py:135
#, python-format
msgid ""
"Failed to kill the old console process %(pid)s before starting a new "
"shellinabox console for node %(node)s."
msgstr ""

#: ironic/drivers/modules/console_utils.py:163
#, python-format
msgid ""
"%(exec_error)s\n"
"Command: %(command)s"
msgstr ""

#: ironic/drivers/modules/console_utils.py:180
#, python-format
msgid ""
"Command: %(command)s.\n"
"Exit code: %(return_code)s.\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: ironic/drivers/modules/console_utils.py:191
#, python-format
msgid "Timeout while waiting for console subprocess to start for node %s."
msgstr ""

#: ironic/drivers/modules/console_utils.py:211
#, python-format
msgid "No console pid found for node %s while trying to stop shellinabox console."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:208
#, python-format
msgid "Parent device '%s' not found"
msgstr "Parent device '%s' not found"

#: ironic/drivers/modules/deploy_utils.py:217
#, python-format
msgid "Root device '%s' not found"
msgstr "Root device '%s' not found"

#: ironic/drivers/modules/deploy_utils.py:220
#, python-format
msgid "Swap device '%s' not found"
msgstr "Swap device '%s' not found"

#: ironic/drivers/modules/deploy_utils.py:224
#, python-format
msgid "Ephemeral device '%s' not found"
msgstr "Ephemeral device '%s' not found"

#: ironic/drivers/modules/deploy_utils.py:238
msgid "Failed to detect root device UUID."
msgstr "Failed to detect root device UUID."

#: ironic/drivers/modules/deploy_utils.py:276
#: ironic/drivers/modules/deploy_utils.py:282
#, python-format
msgid "Deploy to address %s failed."
msgstr "Deploy to address %s failed."

#: ironic/drivers/modules/deploy_utils.py:277
#, python-format
msgid "Command: %s"
msgstr "Command: %s"

#: ironic/drivers/modules/deploy_utils.py:278
#, python-format
msgid "StdOut: %r"
msgstr "StdOut: %r"

#: ironic/drivers/modules/deploy_utils.py:279
#, python-format
msgid "StdErr: %r"
msgstr "StdErr: %r"

#: ironic/drivers/modules/fake.py:53 ironic/drivers/modules/ipminative.py:245
#, python-format
msgid "set_power_state called with an invalid power state: %s."
msgstr "set_power_state called with an invalid power state: %s."

#: ironic/drivers/modules/fake.py:93
msgid "Parameter 'bar' not passed to method 'first_method'."
msgstr "Parameter 'bar' not passed to method 'first_method'."

#: ironic/drivers/modules/fake.py:117
msgid "Parameter 'bar' not passed to method 'second_method'."
msgstr "Parameter 'bar' not passed to method 'second_method'."

#: ironic/drivers/modules/fake.py:160 ironic/drivers/modules/ipminative.py:282
#: ironic/drivers/modules/ipminative.py:309
#: ironic/drivers/modules/ipmitool.py:373
#: ironic/drivers/modules/ipmitool.py:390
#, python-format
msgid "Invalid boot device %s specified."
msgstr "Invalid boot device %s specified."

#: ironic/drivers/modules/image_cache.py:93
#, python-format
msgid "Master cache miss for image %(uuid)s, starting download"
msgstr ""

#: ironic/drivers/modules/image_cache.py:180
#, python-format
msgid "Unable to delete file %(name)s from master image cache: %(exc)s"
msgstr ""

#: ironic/drivers/modules/image_cache.py:187
#, python-format
msgid ""
"After cleaning up cache dir %(dir)s cache size %(actual)d is still larger"
" than threshold %(expected)d"
msgstr ""

#: ironic/drivers/modules/ipminative.py:59
#, python-format
msgid "The following IPMI credentials are not supplied to IPMI driver: %s."
msgstr "The following IPMI credentials are not supplied to IPMI driver: %s."

#: ironic/drivers/modules/ipminative.py:80
#, python-format
msgid ""
"IPMI power on failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""
"IPMI power on failed for node %(node_id)s with the following error: "
"%(error)s"

#: ironic/drivers/modules/ipminative.py:110
#, python-format
msgid ""
"IPMI power off failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""
"IPMI power off failed for node %(node_id)s with the following error: "
"%(error)s"

#: ironic/drivers/modules/ipminative.py:142
#, python-format
msgid ""
"IPMI power reboot failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""
"IPMI power reboot failed for node %(node_id)s with the following error: "
"%(error)s"

#: ironic/drivers/modules/ipminative.py:177
#, python-format
msgid ""
"IPMI get power state failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""
"IPMI get power state failed for node %(node_id)s with the following "
"error: %(error)s"

#: ironic/drivers/modules/ipminative.py:191
#, python-format
msgid ""
"IPMI get power state for node %(node_id)s returns the  following details:"
" %(detail)s"
msgstr ""
"IPMI get power state for node %(node_id)s returns the  following details:"
" %(detail)s"

#: ironic/drivers/modules/ipminative.py:291
#, python-format
msgid ""
"IPMI set boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""
"IPMI set boot device failed for node %(node_id)s with the following "
"error: %(error)s"

#: ironic/drivers/modules/ipminative.py:312
#, python-format
msgid "Unsupported method (%s) passed to IPMINative driver."
msgstr "Unsupported method (%s) passed to IPMINative driver."

#: ironic/drivers/modules/ipmitool.py:95
msgid "IPMI terminal port is not an integer."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:99
msgid "IPMI address not supplied to IPMI driver."
msgstr "IPMI address not supplied to IPMI driver."

#: ironic/drivers/modules/ipmitool.py:104
#, python-format
msgid ""
"Invalid privilege level value:%(priv_level)s, the valid value can be one "
"of %(valid_levels)s"
msgstr ""
"Invalid privilege level value:%(priv_level)s, the valid value can be one "
"of %(valid_levels)s"

#: ironic/drivers/modules/ipmitool.py:201
#, python-format
msgid "IPMI power %(state)s failed for node %(node)s."
msgstr "IPMI power %(state)s failed for node %(node)s."

#: ironic/drivers/modules/ipmitool.py:212
#, python-format
msgid "IPMI power %(state)s timed out after %(tries)s retries."
msgstr "IPMI power %(state)s timed out after %(tries)s retries."

#: ironic/drivers/modules/ipmitool.py:264
#, python-format
msgid "IPMI power status failed for node %(node_id)s with error: %(error)s."
msgstr "IPMI power status failed for node %(node_id)s with error: %(error)s."

#: ironic/drivers/modules/ipmitool.py:294
#, python-format
msgid "BMC inaccessible for node %(node)s: %(error)s"
msgstr "BMC inaccessible for node %(node)s: %(error)s"

#: ironic/drivers/modules/ipmitool.py:332 ironic/drivers/modules/ssh.py:424
#, python-format
msgid "set_power_state called with invalid power state %s."
msgstr "set_power_state called with invalid power state %s."

#: ironic/drivers/modules/ipmitool.py:393
#, python-format
msgid "Unsupported method (%s) passed to IPMItool driver."
msgstr "Unsupported method (%s) passed to IPMItool driver."

#: ironic/drivers/modules/ipmitool.py:419
msgid "IPMI terminal port not supplied to IPMI driver."
msgstr ""

#: ironic/drivers/modules/pxe.py:115
#, python-format
msgid ""
"Can not validate PXE bootloader. The following parameters were not passed"
" to ironic: %s"
msgstr ""
"Can not validate PXE bootloader. The following parameters were not passed"
" to ironic: %s"

#: ironic/drivers/modules/pxe.py:126
#, python-format
msgid ""
"Can not validate PXE bootloader. Invalid parameter pxe_%(param)s. Reason:"
" %(reason)s"
msgstr ""
"Can not validate PXE bootloader. Invalid parameter pxe_%(param)s. Reason:"
" %(reason)s"

#: ironic/drivers/modules/pxe.py:132
#, python-format
msgid "'%s' is not an integer value."
msgstr "'%s' is not an integer value."

#: ironic/drivers/modules/pxe.py:415
#, python-format
msgid ""
"No VIFs found for node %(node)s when attempting to update Neutron DHCP "
"BOOT options."
msgstr ""
"No VIFs found for node %(node)s when attempting to update Neutron DHCP "
"BOOT options."

#: ironic/drivers/modules/pxe.py:434
#, python-format
msgid "Failed to set DHCP BOOT options for any port on node %s."
msgstr "Failed to set DHCP BOOT options for any port on node %s."

#: ironic/drivers/modules/pxe.py:438
#, python-format
msgid ""
"Some errors were encountered when updating the DHCP BOOT options for node"
" %(node)s on the following ports: %(ports)s."
msgstr ""
"Some errors were encountered when updating the DHCP BOOT options for node"
" %(node)s on the following ports: %(ports)s."

#: ironic/drivers/modules/pxe.py:469
#, python-format
msgid ""
"Root partition is too small for requested image. Image size: %(image_mb)d"
" MB, Root size: %(root_mb)d MB"
msgstr ""

#: ironic/drivers/modules/pxe.py:486 ironic/drivers/modules/ssh.py:369
#, python-format
msgid "Node %s does not have any port associated with it."
msgstr "Node %s does not have any port associated with it."

#: ironic/drivers/modules/pxe.py:497
msgid ""
"Couldn't get the URL of the Ironic API service from the configuration "
"file or keystone catalog."
msgstr ""
"Couldn't get the URL of the Ironic API service from the configuration "
"file or keystone catalog."

#: ironic/drivers/modules/pxe.py:598
msgid "Deploy key does not match"
msgstr ""

#: ironic/drivers/modules/pxe.py:616
#, python-format
msgid "Parameters %s were not passed to ironic for deploy."
msgstr "Parameters %s were not passed to ironic for deploy."

#: ironic/drivers/modules/pxe.py:630
#, python-format
msgid "Unsupported method (%s) passed to PXE driver."
msgstr "Unsupported method (%s) passed to PXE driver."

#: ironic/drivers/modules/pxe.py:652
#, python-format
msgid ""
"Node %s failed to power off while handling deploy failure. This may be a "
"serious condition. Node should be removed from Ironic or put in "
"maintenance mode until the problem is resolved."
msgstr ""
"Node %s failed to power off while handling deploy failure. This may be a "
"serious condition. Node should be removed from Ironic or put in "
"maintenance mode until the problem is resolved."

#: ironic/drivers/modules/pxe.py:664
#, python-format
msgid "Node %s is not waiting to be deployed."
msgstr "Node %s is not waiting to be deployed."

#: ironic/drivers/modules/pxe.py:676
#, python-format
msgid "Error returned from PXE deploy ramdisk: %s"
msgstr "Error returned from PXE deploy ramdisk: %s"

#: ironic/drivers/modules/pxe.py:678
msgid "Failure in PXE deploy ramdisk."
msgstr "Failure in PXE deploy ramdisk."

#: ironic/drivers/modules/pxe.py:681
#, python-format
msgid "Continuing deployment for node %(node)s, params %(params)s"
msgstr "Continuing deployment for node %(node)s, params %(params)s"

#: ironic/drivers/modules/pxe.py:687
#, python-format
msgid "PXE deploy failed for instance %(instance)s. Error: %(error)s"
msgstr "PXE deploy failed for instance %(instance)s. Error: %(error)s"

#: ironic/drivers/modules/pxe.py:690
msgid "PXE driver failed to continue deployment."
msgstr "PXE driver failed to continue deployment."

#: ironic/drivers/modules/pxe.py:692
#, python-format
msgid "Deployment to node %s done"
msgstr "Deployment to node %s done"

#: ironic/drivers/modules/seamicro.py:91
msgid "SeaMicro driver requires api_endpoint be set"
msgstr "SeaMicro driver requires api_endpoint be set"

#: ironic/drivers/modules/seamicro.py:95
msgid "SeaMicro driver requires both username and password be set"
msgstr "SeaMicro driver requires both username and password be set"

#: ironic/drivers/modules/seamicro.py:99
msgid "SeaMicro driver requires server_id be set"
msgstr "SeaMicro driver requires server_id be set"

#: ironic/drivers/modules/seamicro.py:149
#, python-format
msgid "SeaMicro client exception %(msg)s for node %(uuid)s"
msgstr "SeaMicro client exception %(msg)s for node %(uuid)s"

#: ironic/drivers/modules/seamicro.py:184
#, python-format
msgid "Power-on failed for node %s."
msgstr "Power-on failed for node %s."

#: ironic/drivers/modules/seamicro.py:223
#, python-format
msgid "Power-off failed for node %s."
msgstr "Power-off failed for node %s."

#: ironic/drivers/modules/seamicro.py:262
#, python-format
msgid "Reboot failed for node %s."
msgstr "Reboot failed for node %s."

#: ironic/drivers/modules/seamicro.py:287
msgid "Invalid volume id specified"
msgstr "Invalid volume id specified"

#: ironic/drivers/modules/seamicro.py:303
msgid "No storage pools found for ironic"
msgstr "No storage pools found for ironic"

#: ironic/drivers/modules/seamicro.py:364
msgid "set_power_state called with invalid power state."
msgstr "set_power_state called with invalid power state."

#: ironic/drivers/modules/seamicro.py:395
#, python-format
msgid "Unsupported method (%s) passed to SeaMicro driver."
msgstr "Unsupported method (%s) passed to SeaMicro driver."

#: ironic/drivers/modules/seamicro.py:413
msgid "No vlan id provided"
msgstr "No vlan id provided"

#: ironic/drivers/modules/seamicro.py:425
#: ironic/drivers/modules/seamicro.py:461
#, python-format
msgid "SeaMicro client exception: %s"
msgstr "SeaMicro client exception: %s"

#: ironic/drivers/modules/seamicro.py:451
msgid "No volume size provided for creating volume"
msgstr "No volume size provided for creating volume"

#: ironic/drivers/modules/seamicro.py:477
msgid "No boot device provided"
msgstr "No boot device provided"

#: ironic/drivers/modules/seamicro.py:480
msgid "Boot device is invalid"
msgstr "Boot device is invalid"

#: ironic/drivers/modules/seamicro.py:490
#, python-format
msgid "set_boot_device error:  %s"
msgstr "set_boot_device error:  %s"

#: ironic/drivers/modules/ssh.py:116
#, python-format
msgid "SSHPowerDriver '%(virt_type)s' is not a valid virt_type, "
msgstr "SSHPowerDriver '%(virt_type)s' is not a valid virt_type, "

#: ironic/drivers/modules/ssh.py:164
msgid "SSHPowerDriver requires ssh_port to be integer value"
msgstr "SSHPowerDriver requires ssh_port to be integer value"

#: ironic/drivers/modules/ssh.py:180
msgid "SSHPowerDriver requires virt_type be set."
msgstr "SSHPowerDriver requires virt_type be set."

#: ironic/drivers/modules/ssh.py:187
msgid "SSHPowerDriver requires both address and username be set."
msgstr "SSHPowerDriver requires both address and username be set."

#: ironic/drivers/modules/ssh.py:192
msgid ""
"SSHPowerDriver requires one and only one of password, key_contents and "
"key_filename to be set."
msgstr ""
"SSHPowerDriver requires one and only one of password, key_contents and "
"key_filename to be set."

#: ironic/drivers/modules/ssh.py:201
#, python-format
msgid "SSH key file %s not found."
msgstr "SSH key file %s not found."

#: ironic/drivers/modules/ssh.py:234
#, python-format
msgid "Node \"%(host)s\" with MAC address %(mac)s not found."
msgstr "Node \"%(host)s\" with MAC address %(mac)s not found."

#: ironic/drivers/modules/ssh.py:374
#, python-format
msgid "SSH connection cannot be established: %s"
msgstr "SSH connection cannot be established: %s"

#: ironic/nova/scheduler/filters/exact_core_filter.py:35
msgid "VCPUs not set; assuming CPU collection broken"
msgstr "VCPUs not set; assuming CPU collection broken"

#: ironic/nova/virt/ironic/client_wrapper.py:53
msgid "Unable to authenticate Ironic client."
msgstr "Unable to authenticate Ironic client."

#: ironic/nova/virt/ironic/client_wrapper.py:89
#, python-format
msgid ""
"Error contacting Ironic server for '%(method)s'. Attempt %(attempt)d of "
"%(total)d"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:100
#, python-format
msgid "Power state %s not found."
msgstr "Power state %s not found."

#: ironic/nova/virt/ironic/driver.py:238
#, python-format
msgid ""
"Failed to add deploy parameters on node %(node)s when provisioning the "
"instance %(instance)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:254
#, python-format
msgid ""
"Failed clean up the parameters on node %(node)s when unprovisioning the "
"instance %(instance)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:258
#, python-format
msgid "Fail to clean up node %s parameters"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:285
#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr "Failed to provision instance %(inst)s: %(reason)s"

#: ironic/nova/virt/ironic/driver.py:395
#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr "Ironic node uuid not supplied to driver for instance %s."

#: ironic/nova/virt/ironic/driver.py:409
#, python-format
msgid ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"
msgstr ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"

#: ironic/nova/virt/ironic/driver.py:422
#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node "
"%(node)s."
msgstr ""
"Error preparing deploy for instance %(instance)s on baremetal node "
"%(node)s."

#: ironic/nova/virt/ironic/driver.py:435
#, python-format
msgid "Failed to request Ironic to provision instance %(inst)s: %(reason)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:473
#, python-format
msgid ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."
msgstr ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."

#: ironic/nova/virt/ironic/driver.py:569
#, python-format
msgid ""
"Ironic node: %(id)s virtual to physical interface count  missmatch (Vif "
"count: %(vif_count)d, Pif count: %(pif_count)d)"
msgstr ""
"Ironic node: %(id)s virtual to physical interface count  missmatch (Vif "
"count: %(vif_count)d, Pif count: %(pif_count)d)"

#: ironic/nova/virt/ironic/driver.py:642
#, python-format
msgid ""
"Failed to add deploy parameters on node %(node)s when rebuilding the "
"instance %(instance)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:653
#, python-format
msgid "Failed to request Ironic to rebuild instance %(inst)s: %(reason)s"
msgstr ""

#: ironic/nova/virt/ironic/patcher.py:68
#, python-format
msgid "'%s' not found in flavor's extra_specs"
msgstr ""

#: ironic/objects/base.py:69
#, python-format
msgid "Error setting %(attr)s"
msgstr "Error setting %(attr)s"

#: ironic/objects/base.py:159
msgid "Invalid version string"
msgstr "Invalid version string"

#: ironic/objects/base.py:220
#, python-format
msgid "Unable to instantiate unregistered object type %(objtype)s"
msgstr "Unable to instantiate unregistered object type %(objtype)s"

#: ironic/objects/base.py:349
#, python-format
msgid "Cannot load '%(attrname)s' in the base class"
msgstr "Cannot load '%(attrname)s' in the base class"

#: ironic/objects/base.py:358
msgid "Cannot save anything in the base class"
msgstr "Cannot save anything in the base class"

#: ironic/objects/base.py:390
#, python-format
msgid "%(objname)s object has no attribute '%(attrname)s'"
msgstr ""

#: ironic/objects/conductor.py:54
msgid "Cannot update a conductor record directly."
msgstr "Cannot update a conductor record directly."

#: ironic/objects/utils.py:39
msgid "A datetime.datetime is required here"
msgstr "A datetime.datetime is required here"

#: ironic/objects/utils.py:104
#, python-format
msgid "An object of class %s is required here"
msgstr "An object of class %s is required here"

#: ironic/openstack/common/gettextutils.py:297
msgid "Message objects do not support addition."
msgstr "Message objects do not support addition."

#: ironic/openstack/common/gettextutils.py:306
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."

#: ironic/openstack/common/lockutils.py:105
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "Could not release the acquired lock `%s`"

#: ironic/openstack/common/lockutils.py:170
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr "Got semaphore \"%(lock)s\""

#: ironic/openstack/common/lockutils.py:179
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr "Attempting to grab file lock \"%(lock)s\""

#: ironic/openstack/common/lockutils.py:189
#, python-format
msgid "Created lock path: %s"
msgstr "Created lock path: %s"

#: ironic/openstack/common/lockutils.py:207
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr "Got file lock \"%(lock)s\" at %(path)s"

#: ironic/openstack/common/lockutils.py:211
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr "Released file lock \"%(lock)s\" at %(path)s"

#: ironic/openstack/common/lockutils.py:249
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr "Got semaphore / lock \"%(function)s\""

#: ironic/openstack/common/lockutils.py:253
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr "Semaphore / lock released \"%(function)s\""

#: ironic/openstack/common/log.py:327
#, python-format
msgid "Deprecated: %s"
msgstr "Deprecated: %s"

#: ironic/openstack/common/log.py:438
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr "Error loading logging config %(log_config)s: %(err_msg)s"

#: ironic/openstack/common/log.py:489
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog facility must be one of: %s"

#: ironic/openstack/common/log.py:710
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Fatal call to deprecated config: %(msg)s"

#: ironic/openstack/common/periodic_task.py:43
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr "Unexpected argument for periodic task creation: %(arg)s."

#: ironic/openstack/common/periodic_task.py:134
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr "Skipping periodic task %(task)s because its interval is negative"

#: ironic/openstack/common/periodic_task.py:139
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr "Skipping periodic task %(task)s because it is disabled"

#: ironic/openstack/common/periodic_task.py:177
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr "Running periodic task %(full_task_name)s"

#: ironic/openstack/common/periodic_task.py:186
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "Error during %(full_task_name)s: %(e)s"

#: ironic/openstack/common/policy.py:395
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr "Failed to understand rule %(rule)s"

#: ironic/openstack/common/policy.py:405
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No handler for matches of kind %s"

#: ironic/openstack/common/policy.py:680
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr "Failed to understand rule %(rule)r"

#: ironic/openstack/common/processutils.py:127
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr "Got unknown keyword args to utils.execute: %r"

#: ironic/openstack/common/processutils.py:142
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "Running cmd (subprocess): %s"

#: ironic/openstack/common/processutils.py:167
#: ironic/openstack/common/processutils.py:240
#, python-format
msgid "Result was %s"
msgstr "Result was %s"

#: ironic/openstack/common/processutils.py:179
#, python-format
msgid "%r failed. Retrying."
msgstr "%r failed. Retrying."

#: ironic/openstack/common/processutils.py:219
#, python-format
msgid "Running cmd (SSH): %s"
msgstr "Running cmd (SSH): %s"

#: ironic/openstack/common/processutils.py:221
msgid "Environment not supported over SSH"
msgstr "Environment not supported over SSH"

#: ironic/openstack/common/processutils.py:225
msgid "process_input not supported over SSH"
msgstr "process_input not supported over SSH"

#: ironic/openstack/common/service.py:166
#: ironic/openstack/common/service.py:384
msgid "Full set of CONF:"
msgstr "Full set of CONF:"

#: ironic/openstack/common/service.py:175
#: ironic/openstack/common/service.py:269
#, python-format
msgid "Caught %s, exiting"
msgstr "Caught %s, exiting"

#: ironic/openstack/common/service.py:187
msgid "Exception during rpc cleanup."
msgstr "Exception during rpc cleanup."

#: ironic/openstack/common/service.py:238
msgid "Parent process has died unexpectedly, exiting"
msgstr "Parent process has died unexpectedly, exiting"

#: ironic/openstack/common/service.py:275
msgid "Unhandled exception"
msgstr "Unhandled exception"

#: ironic/openstack/common/service.py:308
msgid "Forking too fast, sleeping"
msgstr "Forking too fast, sleeping"

#: ironic/openstack/common/service.py:327
#, python-format
msgid "Started child %d"
msgstr "Started child %d"

#: ironic/openstack/common/service.py:337
#, python-format
msgid "Starting %d workers"
msgstr "Starting %d workers"

#: ironic/openstack/common/service.py:354
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr "Child %(pid)d killed by signal %(sig)d"

#: ironic/openstack/common/service.py:358
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr "Child %(pid)s exited with status %(code)d"

#: ironic/openstack/common/service.py:362
#, python-format
msgid "pid %d not in child list"
msgstr "pid %d not in child list"

#: ironic/openstack/common/service.py:392
#, python-format
msgid "Caught %s, stopping children"
msgstr "Caught %s, stopping children"

#: ironic/openstack/common/service.py:410
#, python-format
msgid "Waiting on %d children to exit"
msgstr "Waiting on %d children to exit"

#: ironic/openstack/common/strutils.py:88
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr "Unrecognised value '%(val)s', acceptable values are: %(acceptable)s"

#: ironic/openstack/common/strutils.py:184
#, python-format
msgid "Invalid string format: %s"
msgstr "Invalid string format: %s"

#: ironic/openstack/common/strutils.py:191
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr "Unknown byte multiplier: %s"

#: ironic/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr "Invalid Parameter: Unicode is not supported by the current database."

#: ironic/openstack/common/db/sqlalchemy/migration.py:188
msgid "version should be an integer"
msgstr "version should be an integer"

#: ironic/openstack/common/db/sqlalchemy/migration.py:216
#, python-format
msgid ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"
msgstr ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"

#: ironic/openstack/common/db/sqlalchemy/migration.py:240
msgid ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."
msgstr ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."

#: ironic/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr "Sort key supplied was not valid."

#: ironic/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "Unknown sort direction, must be 'desc' or 'asc'"

#: ironic/openstack/common/db/sqlalchemy/utils.py:164
#, python-format
msgid ""
"There is no `deleted` column in `%s` table. Project doesn't use soft-"
"deleted feature."
msgstr ""
"There is no `deleted` column in `%s` table. Project doesn't use soft-"
"deleted feature."

#: ironic/openstack/common/db/sqlalchemy/utils.py:176
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr "Unrecognized read_deleted value '%s'"

#: ironic/openstack/common/db/sqlalchemy/utils.py:183
#, python-format
msgid "There is no `project_id` column in `%s` table."
msgstr "There is no `project_id` column in `%s` table."

#: ironic/openstack/common/db/sqlalchemy/utils.py:241
msgid "model should be a subclass of ModelBase"
msgstr "model should be a subclass of ModelBase"

#: ironic/openstack/common/db/sqlalchemy/utils.py:284
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."

#: ironic/openstack/common/db/sqlalchemy/utils.py:290
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."

#: ironic/openstack/common/db/sqlalchemy/utils.py:391
msgid "Unsupported id columns type"
msgstr "Unsupported id columns type"

#: ironic/tests/db/sqlalchemy/test_migrations.py:312
#, python-format
msgid "Failed to migrate to version %(version)s on engine %(engine)s"
msgstr "Failed to migrate to version %(version)s on engine %(engine)s"

