# Translations template for ironic.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the ironic project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ironic 4.3.1.dev202\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-01-27 06:37+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: ironic/common/exception.py:76
#, python-format
msgid ""
"Exception class: %s Using the 'message' attribute in an exception has "
"been deprecated. The exception class should be modified to use the "
"'_msg_fmt' attribute."
msgstr ""

#: ironic/common/utils.py:470
#, python-format
msgid "Failed to remove dir %(path)s, error: %(e)s"
msgstr ""

#: ironic/common/utils.py:487
#, python-format
msgid "Failed to create symlink from %(source)s to %(link)s, error: %(e)s"
msgstr ""

#: ironic/common/utils.py:501
#, python-format
msgid ""
"Failed to remove trailing character. Returning original object. Supplied "
"object is not a string: %s,"
msgstr ""

#: ironic/conductor/base_manager.py:129
#, python-format
msgid ""
"A conductor with hostname %(hostname)s was previously registered. "
"Updating registration"
msgstr ""

#: ironic/conductor/base_manager.py:242
msgid "Conductor could not connect to database while heartbeating."
msgstr ""

#: ironic/conductor/manager.py:881
msgid ""
"Returning CLEANING for asynchronous prepare cleaning has been deprecated."
" Please use CLEANWAIT instead."
msgstr ""

#: ironic/conductor/manager.py:950
msgid ""
"Returning CLEANING for asynchronous clean steps has been deprecated. "
"Please use CLEANWAIT instead."
msgstr ""

#: ironic/conductor/manager.py:1268
#, python-format
msgid ""
"During checking for deploying state, node %s was not found and presumed "
"deleted by another process. Skipping."
msgstr ""

#: ironic/conductor/manager.py:1273
#, python-format
msgid ""
"During checking for deploying state, when releasing the lock of the node "
"%s, it was locked by another process. Skipping."
msgstr ""

#: ironic/conductor/manager.py:1279
#, python-format
msgid ""
"During checking for deploying state, when releasing the lock of the node "
"%s, it was already unlocked."
msgstr ""

#: ironic/conductor/manager.py:1646
#, python-format
msgid ""
"No VIF found for instance %(instance)s port %(port)s when attempting to "
"update port MAC address."
msgstr ""

#: ironic/conductor/manager.py:1704
#, python-format
msgid ""
"get_sensors_data is not implemented for driver %(driver)s, node_uuid is "
"%(node)s"
msgstr ""

#: ironic/conductor/manager.py:1709
#, python-format
msgid ""
"During get_sensors_data, could not parse sensor data for node %(node)s. "
"Error: %(err)s."
msgstr ""

#: ironic/conductor/manager.py:1714
#, python-format
msgid ""
"During get_sensors_data, could not get sensor data for node %(node)s. "
"Error: %(err)s."
msgstr ""

#: ironic/conductor/manager.py:1719
#, python-format
msgid ""
"During send_sensor_data, node %(node)s was not found and presumed deleted"
" by another process."
msgstr ""

#: ironic/conductor/manager.py:1724
#, python-format
msgid "Failed to get sensor data for node %(node)s. Error: %(error)s"
msgstr ""

#: ironic/conductor/manager.py:2284
#, python-format
msgid ""
"During sync_power_state, could not get power state for node %(node)s, "
"attempt %(attempt)s of %(retries)s. Error: %(err)s."
msgstr ""

#: ironic/conductor/manager.py:2323
#, python-format
msgid ""
"During sync_power_state, node %(node)s state '%(actual)s' does not match "
"expected state. Changing hardware state to '%(state)s'."
msgstr ""

#: ironic/conductor/manager.py:2341
#, python-format
msgid ""
"During sync_power_state, node %(node)s state does not match expected "
"state '%(state)s'. Updating recorded state to '%(actual)s'."
msgstr ""

#: ironic/conductor/task_manager.py:402
#, python-format
msgid "Task's on_error hook failed to call %(method)s on node %(node)s"
msgstr ""

#: ironic/conductor/utils.py:104
#, python-format
msgid ""
"Not going to change node power state because current state = requested "
"state = '%(state)s'."
msgstr ""

#: ironic/conductor/utils.py:111
#, python-format
msgid "Driver returns ERROR power state for node %s."
msgstr ""

#: ironic/conductor/utils.py:196
#, python-format
msgid ""
"No free conductor workers available to perform an action on node "
"%(node)s, setting node's provision_state back to %(prov_state)s and "
"target_provision_state to %(tgt_prov_state)s."
msgstr ""

#: ironic/conductor/utils.py:246
#, python-format
msgid ""
"No free conductor workers available to perform an action on node "
"%(node)s, setting node's power state back to %(power_state)s."
msgstr ""

#: ironic/db/sqlalchemy/api.py:582
#, python-format
msgid "Cleared reservations held by %(hostname)s: %(nodes)s"
msgstr ""

#: ironic/dhcp/neutron.py:186
#, python-format
msgid ""
"Some errors were encountered when updating the DHCP BOOT options for node"
" %(node)s on the following ports: %(ports)s."
msgstr ""

#: ironic/dhcp/neutron.py:250
#, python-format
msgid "No VIFs found for node %(node)s when attempting  to get port IP address."
msgstr ""

#: ironic/dhcp/neutron.py:279
#, python-format
msgid ""
"Some errors were encountered on node %(node)s while retrieving IP address"
" on the following ports: %(ports)s."
msgstr ""

#: ironic/drivers/base.py:1145
msgid ""
"Using periodic tasks with parallel=False is deprecated, \"parallel\" "
"argument will be ignored starting with the Mitaka release"
msgstr ""

#: ironic/drivers/utils.py:146
#, python-format
msgid "Ignoring malformed capability '%s'. Format should be 'key:val'."
msgstr ""

#: ironic/drivers/modules/agent.py:149
#, python-format
msgid ""
"Skip the image size check as memory_mb is not defined in properties on "
"node %s."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:491
#, python-format
msgid "Malformed MAC: %s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:534
#, python-format
msgid "MAC address %s not found in database"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:599
#: ironic/drivers/modules/oneview/vendor.py:96
#, python-format
msgid ""
"Failed to soft power off node %(node_uuid)s in at least %(timeout)d "
"seconds. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/console_utils.py:136
#, python-format
msgid ""
"Console process for node %s is not running but pid file exists while "
"trying to stop shellinabox console."
msgstr ""

#: ironic/drivers/modules/console_utils.py:189
#, python-format
msgid ""
"Failed to kill the old console process before starting a new shellinabox "
"console for node %(node)s. Reason: %(err)s"
msgstr ""

#: ironic/drivers/modules/console_utils.py:275
#, python-format
msgid "No console pid found for node %s while trying to stop shellinabox console."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:660
#, python-format
msgid ""
"ipmitool is unable to set boot device while the node %s is in UEFI boot "
"mode. Please set the boot device manually."
msgstr ""

#: ironic/drivers/modules/iboot.py:122
#, python-format
msgid ""
"Reached maximum number of attempts (%(attempts)d) to set power state for "
"node %(node)s to \"%(op)s\""
msgstr ""

#: ironic/drivers/modules/iboot.py:135
#, python-format
msgid ""
"Cannot call set power state for node '%(node)s' at relay '%(relay)s'. "
"iBoot switch() failed."
msgstr ""

#: ironic/drivers/modules/iboot.py:170
#, python-format
msgid ""
"Reached maximum number of attempts (%(attempts)d) to get power state for "
"node %(node)s"
msgstr ""

#: ironic/drivers/modules/iboot.py:186
#, python-format
msgid ""
"Cannot get power state for node '%(node)s' at relay '%(relay)s'. iBoot "
"get_relays() failed."
msgstr ""

#: ironic/drivers/modules/image_cache.py:206
#, python-format
msgid ""
"Cache clean up was unable to reclaim %(required)d MiB of disk space, "
"still %(left)d MiB required"
msgstr ""

#: ironic/drivers/modules/image_cache.py:233
#: ironic/drivers/modules/image_cache.py:272
#, python-format
msgid "Unable to delete file %(name)s from master image cache: %(exc)s"
msgstr ""

#: ironic/drivers/modules/image_cache.py:407
#, python-format
msgid ""
"Image service couldn't determine last modification time of %(href)s, "
"considering cached image up to date."
msgstr ""

#: ironic/drivers/modules/ipminative.py:263
#, python-format
msgid ""
"IPMI get power state for node %(node_id)s returns the following details: "
"%(detail)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:433
#, python-format
msgid ""
"IPMI Error encountered, retrying \"%(cmd)s\" for node %(node)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:490
#, python-format
msgid "IPMI power %(state)s failed for node %(node)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:555
#, python-format
msgid "IPMI power status failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:869
#, python-format
msgid ""
"IPMI set boot device failed for node %(node)s when executing \"ipmitool "
"%(cmd)s\". Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:912
#, python-format
msgid ""
"IPMI get boot device failed for node %(node)s when executing \"ipmitool "
"%(cmd)s\". Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:856
#: ironic/drivers/modules/iscsi_deploy.py:902
#, python-format
msgid ""
"The node %s is using the bash deploy ramdisk for its deployment. This "
"deploy ramdisk has been deprecated. Please use the ironic-python-agent "
"(IPA) ramdisk instead."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:876
#, python-format
msgid ""
"Bash deploy ramdisk doesn't support in-band cleaning. Please use the "
"ironic-python-agent (IPA) ramdisk instead for node %s. "
msgstr ""

#: ironic/drivers/modules/pxe.py:139
#, python-format
msgid ""
"The CONF option [agent]agent_%(opt_name)s is deprecated and will be "
"removed in Mitaka release of Ironic. Please use [pxe]%(opt_name)s "
"instead."
msgstr ""

#: ironic/drivers/modules/pxe.py:499
#, python-format
msgid ""
"Could not get deploy image info to clean up images for node %(node)s: "
"%(err)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:539
#, python-format
msgid ""
"The UUID for the root partition can't be found, unable to switch the pxe "
"config from deployment mode to service (boot) mode for node %(node)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:545
#, python-format
msgid ""
"The disk id for the whole disk image can't be found, unable to switch the"
" pxe config from deployment mode to service (boot) mode for node %(node)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:583
#, python-format
msgid ""
"Could not get instance image info to clean up images for node %(node)s: "
"%(err)s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:231
#, python-format
msgid "Power-on failed for node %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:271
#, python-format
msgid "Power-off failed for node %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:312
#, python-format
msgid "Reboot failed for node %s."
msgstr ""

#: ironic/drivers/modules/snmp.py:373
#, python-format
msgid "SNMP PDU %(addr)s outlet %(outlet)s: unrecognised power state %(state)s."
msgstr ""

#: ironic/drivers/modules/snmp.py:539
#, python-format
msgid ""
"Eaton Power SNMP PDU %(addr)s outlet %(outlet)s: unrecognised power state"
" %(state)s."
msgstr ""

#: ironic/drivers/modules/ssh.py:787
#, python-format
msgid ""
"Failed to get boot device for node %(node)s, virt_type %(vtype)s does not"
" support this operation"
msgstr ""

#: ironic/drivers/modules/amt/power.py:180
#, python-format
msgid ""
"AMT failed to set power state %(state)s after %(tries)s retries on node "
"%(node_id)s."
msgstr ""

#: ironic/drivers/modules/amt/power.py:190
#, python-format
msgid ""
"AMT set power state %(state)s for node %(node)s - Attempt %(attempt)s "
"times of %(max_attempt)s failed."
msgstr ""

#: ironic/drivers/modules/drac/client.py:91
#, python-format
msgid ""
"Empty response on calling %(action)s on client. Last error (cURL error "
"code): %(last_error)s, fault string: \"%(fault_string)s\" response_code: "
"%(response_code)s. Retry attempt %(count)d"
msgstr ""

#: ironic/drivers/modules/ilo/boot.py:350
#, python-format
msgid "The UUID for the root partition could not be found for node %s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:555
#, python-format
msgid ""
"Temporary object associated with virtual floppy was already deleted from "
"Swift. Error: %s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:142
#, python-format
msgid "Secure boot mode is not supported for node %s"
msgstr ""

#: ironic/drivers/modules/ilo/inspect.py:59
#, python-format
msgid "Port already exists for MAC address %(address)s for node %(node)s"
msgstr ""

#: ironic/drivers/modules/ilo/management.py:101
#, python-format
msgid ""
"'%(step)s' clean step is not supported on node %(uuid)s. Skipping the "
"clean step."
msgstr ""

#: ironic/drivers/modules/oneview/common.py:138
#, python-format
msgid ""
"Using 'server_profile_template_uri' in driver_info is now deprecated and "
"will be ignored in future releases. Node %s should have it in its "
"properties/capabilities instead."
msgstr ""

