# Translations template for ironic.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ironic project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ironic 2015.1.dev31\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-02-18 06:14+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ironic/api/controllers/base.py:92
msgid "Invalid value for X-OpenStack-Ironic-API-Version header."
msgstr ""

#: ironic/api/controllers/v1/__init__.py:164
#, python-format
msgid ""
"Mutually exclusive versions requested. Version %(ver)s requested but not "
"supported by this service."
msgstr ""

#: ironic/api/controllers/v1/__init__.py:170
#, python-format
msgid ""
"Unsupported minor version requested. This API service supports the "
"following version range: [%(min)s, %(max)s]."
msgstr ""

#: ironic/api/controllers/v1/driver.py:146
#: ironic/api/controllers/v1/node.py:716
msgid "Method not specified"
msgstr ""

#: ironic/api/controllers/v1/node.py:423
#, python-format
msgid "Adding a config drive is only supported when setting provision state to %s"
msgstr ""

#: ironic/api/controllers/v1/node.py:446
#, python-format
msgid "The requested action \"%(action)s\" could not be understood."
msgstr ""

#: ironic/api/controllers/v1/node.py:801
msgid "Chassis id not specified."
msgstr ""

#: ironic/api/controllers/v1/node.py:975
#, python-format
msgid "Cannot create node with invalid name %(name)s"
msgstr ""

#: ironic/api/controllers/v1/node.py:1003
#, python-format
msgid "Node %s can not be updated while a state transition is in progress."
msgstr ""

#: ironic/api/controllers/v1/node.py:1013
#, python-format
msgid "Node %(node)s: Cannot change name to invalid name '%(name)s'"
msgstr ""

#: ironic/api/controllers/v1/port.py:182
msgid "Node id not specified."
msgstr ""

#: ironic/api/controllers/v1/types.py:171
#, python-format
msgid "%s is not JSON serializable"
msgstr ""

#: ironic/api/controllers/v1/types.py:222
#, python-format
msgid "'%s' is an internal attribute and can not be updated"
msgstr ""

#: ironic/api/controllers/v1/types.py:226
#, python-format
msgid "'%s' is a mandatory attribute and can not be removed"
msgstr ""

#: ironic/api/controllers/v1/types.py:231
msgid "'add' and 'replace' operations needs value"
msgstr ""

#: ironic/api/controllers/v1/utils.py:32
msgid "Limit must be positive"
msgstr ""

#: ironic/api/controllers/v1/utils.py:39
#, python-format
msgid "Invalid sort direction: %s. Acceptable values are 'asc' or 'desc'"
msgstr ""

#: ironic/api/controllers/v1/utils.py:49
#, python-format
msgid "Adding a new attribute (%s) to the root of  the resource is not allowed"
msgstr ""

#: ironic/api/middleware/auth_token.py:41
#, python-format
msgid "Cannot compile public API routes: %s"
msgstr ""

#: ironic/api/middleware/parsable_error.py:53
#, python-format
msgid "ErrorDocumentMiddleware received an invalid status %s"
msgstr ""

#: ironic/common/disk_partitioner.py:167
#, python-format
msgid ""
"Disk partitioning failed on device %(device)s. Processes with the "
"following PIDs are holding it: %(pids)s. Time out waiting for completion."
msgstr ""

#: ironic/common/disk_partitioner.py:173
#, python-format
msgid ""
"Disk partitioning failed on device %(device)s. Fuser exited with "
"\"%(fuser_err)s\". Time out waiting for completion."
msgstr ""

#: ironic/common/exception.py:58
msgid "An unknown exception occurred."
msgstr ""

#: ironic/common/exception.py:99
msgid "Not authorized."
msgstr ""

#: ironic/common/exception.py:104
msgid "Operation not permitted."
msgstr ""

#: ironic/common/exception.py:108
msgid "Unacceptable parameters."
msgstr ""

#: ironic/common/exception.py:113
msgid "Conflict."
msgstr ""

#: ironic/common/exception.py:118
msgid "Resource temporarily unavailable, please retry."
msgstr ""

#: ironic/common/exception.py:124
msgid "Request not acceptable."
msgstr ""

#: ironic/common/exception.py:129
msgid "Invalid resource state."
msgstr ""

#: ironic/common/exception.py:133
#, python-format
msgid "A node with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:137
#, python-format
msgid "A port with MAC address %(mac)s already exists."
msgstr ""

#: ironic/common/exception.py:141
#, python-format
msgid "A chassis with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:145
#, python-format
msgid "A port with UUID %(uuid)s already exists."
msgstr ""

#: ironic/common/exception.py:149
#, python-format
msgid ""
"Instance %(instance_uuid)s is already associated with a node, it cannot "
"be associated with this other node %(node)s"
msgstr ""

#: ironic/common/exception.py:154
#, python-format
msgid "A node with name %(name)s already exists."
msgstr ""

#: ironic/common/exception.py:158
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: ironic/common/exception.py:162
#, python-format
msgid "Expected a logical name or uuid but received %(name)s."
msgstr ""

#: ironic/common/exception.py:166
#, python-format
msgid "Expected a logical name but received %(name)s."
msgstr ""

#: ironic/common/exception.py:170
#, python-format
msgid "Expected an uuid or int but received %(identity)s."
msgstr ""

#: ironic/common/exception.py:174
#, python-format
msgid "Expected a MAC address but received %(mac)s."
msgstr ""

#: ironic/common/exception.py:178
#, python-format
msgid ""
"The requested action \"%(action)s\" can not be performed on node "
"\"%(node)s\" while it is in state \"%(state)s\"."
msgstr ""

#: ironic/common/exception.py:183
#, python-format
msgid "Couldn't apply patch '%(patch)s'. Reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:187
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr ""

#: ironic/common/exception.py:191 ironic/common/exception.py:195
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: ironic/common/exception.py:201 ironic/common/exception.py:205
#, python-format
msgid "%(err)s"
msgstr ""

#: ironic/common/exception.py:209
msgid "Resource already exists."
msgstr ""

#: ironic/common/exception.py:213
msgid "Resource could not be found."
msgstr ""

#: ironic/common/exception.py:218
#, python-format
msgid "Failed to load DHCP provider %(dhcp_provider_name)s."
msgstr ""

#: ironic/common/exception.py:222
#, python-format
msgid "Could not find the following driver(s): %(driver_name)s."
msgstr ""

#: ironic/common/exception.py:226
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: ironic/common/exception.py:230
#, python-format
msgid "No valid host was found. Reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:234
#, python-format
msgid "Instance %(instance)s could not be found."
msgstr ""

#: ironic/common/exception.py:238
#, python-format
msgid "Node %(node)s could not be found."
msgstr ""

#: ironic/common/exception.py:242
#, python-format
msgid "Node %(node)s is associated with instance %(instance)s."
msgstr ""

#: ironic/common/exception.py:246
#, python-format
msgid "Port %(port)s could not be found."
msgstr ""

#: ironic/common/exception.py:250
#, python-format
msgid "Update DHCP options on port: %(port_id)s failed."
msgstr ""

#: ironic/common/exception.py:254
#, python-format
msgid "Retrieve IP address on port: %(port_id)s failed."
msgstr ""

#: ironic/common/exception.py:258
#, python-format
msgid "Invalid IPv4 address %(ip_address)s."
msgstr ""

#: ironic/common/exception.py:262
#, python-format
msgid "Update MAC address on port: %(port_id)s failed."
msgstr ""

#: ironic/common/exception.py:266
#, python-format
msgid "Chassis %(chassis)s could not be found."
msgstr ""

#: ironic/common/exception.py:270
#, python-format
msgid "Conductor %(conductor)s cannot be started because no drivers were loaded."
msgstr ""

#: ironic/common/exception.py:275
#, python-format
msgid "Conductor %(conductor)s could not be found."
msgstr ""

#: ironic/common/exception.py:279
#, python-format
msgid "Conductor %(conductor)s already registered."
msgstr ""

#: ironic/common/exception.py:283
#, python-format
msgid "Failed to set node power state to %(pstate)s."
msgstr ""

#: ironic/common/exception.py:287
msgid "An exclusive lock is required, but the current context has a shared lock."
msgstr ""

#: ironic/common/exception.py:292
#, python-format
msgid "Failed to toggle maintenance-mode flag for node %(node)s: %(reason)s"
msgstr ""

#: ironic/common/exception.py:297
#, python-format
msgid "Console access is not enabled on node %(node)s"
msgstr ""

#: ironic/common/exception.py:301
#, python-format
msgid ""
"The %(op)s operation can't be performed on node %(node)s because it's in "
"maintenance mode."
msgstr ""

#: ironic/common/exception.py:306
#, python-format
msgid ""
"Can not change instance association while node %(node)s is in power state"
" %(pstate)s."
msgstr ""

#: ironic/common/exception.py:311
#, python-format
msgid ""
"Cannot complete the requested action because chassis %(chassis)s contains"
" nodes."
msgstr ""

#: ironic/common/exception.py:316
#, python-format
msgid "IPMI call failed: %(cmd)s."
msgstr ""

#: ironic/common/exception.py:320
#, python-format
msgid "Failed to establish SSH connection to host %(host)s."
msgstr ""

#: ironic/common/exception.py:324
#, python-format
msgid "Failed to execute command via SSH: %(cmd)s."
msgstr ""

#: ironic/common/exception.py:328
#, python-format
msgid "Unsupported object type %(objtype)s"
msgstr ""

#: ironic/common/exception.py:332
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""

#: ironic/common/exception.py:336
#, python-format
msgid "Driver %(driver)s does not support %(extension)s."
msgstr ""

#: ironic/common/exception.py:340
#, python-format
msgid "Version %(objver)s of %(objname)s is not supported"
msgstr ""

#: ironic/common/exception.py:344
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr ""

#: ironic/common/exception.py:349
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: ironic/common/exception.py:353
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: ironic/common/exception.py:357
msgid "Not authorized in Keystone."
msgstr ""

#: ironic/common/exception.py:370
#, python-format
msgid ""
"Service type %(service_type)s with endpoint type %(endpoint_type)s not "
"found in keystone service catalog."
msgstr ""

#: ironic/common/exception.py:375
msgid "Connection failed"
msgstr ""

#: ironic/common/exception.py:379
msgid "Requested OpenStack Images API is forbidden"
msgstr ""

#: ironic/common/exception.py:387
msgid "The provided endpoint is invalid"
msgstr ""

#: ironic/common/exception.py:391
msgid "Unable to communicate with the server."
msgstr ""

#: ironic/common/exception.py:407
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: ironic/common/exception.py:411
#, python-format
msgid ""
"Node %(node)s is locked by host %(host)s, please retry after the current "
"operation is completed."
msgstr ""

#: ironic/common/exception.py:416
#, python-format
msgid "Node %(node)s found not to be locked on release"
msgstr ""

#: ironic/common/exception.py:420
msgid ""
"Requested action cannot be performed due to lack of free conductor "
"workers."
msgstr ""

#: ironic/common/exception.py:430
#, python-format
msgid "Invalid configuration file. %(error_msg)s"
msgstr ""

#: ironic/common/exception.py:434
#, python-format
msgid "Driver %(driver)s could not be loaded. Reason: %(reason)s."
msgstr ""

#: ironic/common/exception.py:442
#, python-format
msgid "Could not find pid in pid file %(pid_path)s"
msgstr ""

#: ironic/common/exception.py:446
#, python-format
msgid "Console subprocess failed to start. %(error)s"
msgstr ""

#: ironic/common/exception.py:450
#, python-format
msgid "Failed to create the password file. %(error)s"
msgstr ""

#: ironic/common/exception.py:458
#, python-format
msgid "%(operation)s failed, error: %(error)s"
msgstr ""

#: ironic/common/exception.py:466
#, python-format
msgid ""
"DRAC client failed. Last error (cURL error code): %(last_error)s, fault "
"string: \"%(fault_string)s\" response_code: %(response_code)s"
msgstr ""

#: ironic/common/exception.py:473
#, python-format
msgid "DRAC operation failed. Message: %(message)s"
msgstr ""

#: ironic/common/exception.py:477
#, python-format
msgid ""
"DRAC operation yielded return value %(actual_return_value)s that is "
"neither error nor expected %(expected_return_value)s"
msgstr ""

#: ironic/common/exception.py:482
#, python-format
msgid ""
"Another job with ID %(job_id)s is already created  to configure "
"%(target)s. Wait until existing job is completed or is canceled"
msgstr ""

#: ironic/common/exception.py:488
#, python-format
msgid ""
"Invalid filter dialect '%(invalid_filter)s'. Supported options are "
"%(supported)s"
msgstr ""

#: ironic/common/exception.py:493
#, python-format
msgid "Failed to get sensor data for node %(node)s. Error: %(error)s"
msgstr ""

#: ironic/common/exception.py:498
#, python-format
msgid "Failed to parse sensor data for node %(node)s. Error: %(error)s"
msgstr ""

#: ironic/common/exception.py:503
#, python-format
msgid ""
"Disk volume where '%(path)s' is located doesn't have enough disk space. "
"Required %(required)d MiB, only %(actual)d MiB available space present."
msgstr ""

#: ironic/common/exception.py:509
#, python-format
msgid "Creating %(image_type)s image failed: %(error)s"
msgstr ""

#: ironic/common/exception.py:513
#, python-format
msgid "Swift operation '%(operation)s' failed: %(error)s"
msgstr ""

#: ironic/common/exception.py:517
#, python-format
msgid "SNMP operation '%(operation)s' failed: %(error)s"
msgstr ""

#: ironic/common/exception.py:521
#, python-format
msgid "Failed to create a file system. File system %(fs)s is not supported."
msgstr ""

#: ironic/common/exception.py:526
#, python-format
msgid "iRMC %(operation)s failed. Reason: %(error)s"
msgstr ""

#: ironic/common/exception.py:530
#, python-format
msgid "VirtualBox operation '%(operation)s' failed. Error: %(error)s"
msgstr ""

#: ironic/common/fsm.py:84
#, python-format
msgid "State '%s' already defined"
msgstr ""

#: ironic/common/fsm.py:87
msgid "On enter callback must be callable"
msgstr ""

#: ironic/common/fsm.py:90
msgid "On exit callback must be callable"
msgstr ""

#: ironic/common/fsm.py:92
#, python-format
msgid "Target state '%s' does not exist"
msgstr ""

#: ironic/common/fsm.py:108
#, python-format
msgid ""
"Can not add a transition on event '%(event)s' that starts in a undefined "
"state '%(state)s'"
msgstr ""

#: ironic/common/fsm.py:113
#, python-format
msgid ""
"Can not add a transition on event '%(event)s' that ends in a undefined "
"state '%(state)s'"
msgstr ""

#: ironic/common/fsm.py:124
msgid "Can only process events after being initialized (not before)"
msgstr ""

#: ironic/common/fsm.py:128
#, python-format
msgid "Can not transition from terminal state '%(state)s' on event '%(event)s'"
msgstr ""

#: ironic/common/fsm.py:133
#, python-format
msgid ""
"Can not transition from state '%(state)s' on event '%(event)s' (no "
"defined transition)"
msgstr ""

#: ironic/common/fsm.py:171
#, python-format
msgid "Can not start from an undefined state '%s'"
msgstr ""

#: ironic/common/fsm.py:174
#, python-format
msgid "Can not start from a terminal state '%s'"
msgstr ""

#: ironic/common/hash_ring.py:85
msgid "Invalid hosts supplied when building HashRing."
msgstr ""

#: ironic/common/hash_ring.py:114
msgid "Invalid data supplied to HashRing.get_hosts."
msgstr ""

#: ironic/common/hash_ring.py:197
#, python-format
msgid "The driver '%s' is unknown."
msgstr ""

#: ironic/common/images.py:257
msgid "'qemu-img info' parsing failed."
msgstr ""

#: ironic/common/images.py:263
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: ironic/common/images.py:278
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: ironic/common/keystone.py:52
msgid "Keystone API endpoint is missing"
msgstr ""

#: ironic/common/keystone.py:75
#, python-format
msgid "Could not authorize in Keystone: %s"
msgstr ""

#: ironic/common/keystone.py:110
msgid "No Keystone service catalog loaded"
msgstr ""

#: ironic/common/pxe_utils.py:100
#, python-format
msgid "Failed to get IP address for any port on node %s."
msgstr ""

#: ironic/common/swift.py:97
msgid "put container"
msgstr ""

#: ironic/common/swift.py:108
msgid "put object"
msgstr ""

#: ironic/common/swift.py:128
msgid "head account"
msgstr ""

#: ironic/common/swift.py:156
msgid "delete object"
msgstr ""

#: ironic/common/swift.py:172
msgid "head object"
msgstr ""

#: ironic/common/swift.py:187
msgid "post object"
msgstr ""

#: ironic/common/utils.py:117
msgid "Invalid private key"
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:139
#, python-format
msgid "The given image info does not have a valid image id: %s"
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:165
msgid ""
"Swift temporary URLs require a shared secret to be created. You must "
"provide \"swift_temp_url_key\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:169
msgid ""
"Swift temporary URLs require a Swift endpoint URL. You must provide "
"\"swift_endpoint_url\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:173
msgid ""
"Swift temporary URLs require a Swift account string. You must provide "
"\"swift_account\" as a config option."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:177
msgid "\"swift_temp_url_duration\" must be a positive integer."
msgstr ""

#: ironic/common/glance_service/v2/image_service.py:182
msgid ""
"An integer value between 0 and 32 is required for "
"swift_store_multiple_containers_seed."
msgstr ""

#: ironic/conductor/manager.py:338
msgid "Invalid method call: update_node can not change node state."
msgstr ""

#: ironic/conductor/manager.py:463 ironic/conductor/manager.py:555
#: ironic/drivers/utils.py:84
#, python-format
msgid "No handler for method %s"
msgstr ""

#: ironic/conductor/manager.py:468 ironic/conductor/manager.py:560
#, python-format
msgid "The method %(method)s does not support HTTP %(http)s"
msgstr ""

#: ironic/conductor/manager.py:657
msgid "provisioning"
msgstr ""

#: ironic/conductor/manager.py:664
#, python-format
msgid "RPC do_node_deploy failed to validate deploy or power info. Error: %(msg)s"
msgstr ""

#: ironic/conductor/manager.py:724
#, python-format
msgid ""
"Failed to validate power driver interface. Can not delete instance. "
"Error: %(msg)s"
msgstr ""

#: ironic/conductor/manager.py:994
msgid "not supported"
msgstr ""

#: ironic/conductor/manager.py:1022
#, python-format
msgid "Node %s can't be deleted because it's not powered off"
msgstr ""

#: ironic/conductor/manager.py:1101
msgid "enabled"
msgstr ""

#: ironic/conductor/manager.py:1101
msgid "disabled"
msgstr ""

#: ironic/conductor/manager.py:1124
msgid "enabling"
msgstr ""

#: ironic/conductor/manager.py:1124
msgid "disabling"
msgstr ""

#: ironic/conductor/manager.py:1125
#, python-format
msgid "Error %(op)s the console on node %(node)s. Reason: %(error)s"
msgstr ""

#: ironic/conductor/manager.py:1376 ironic/conductor/manager.py:1404
msgid "No free conductor workers available"
msgstr ""

#: ironic/conductor/manager.py:1476
#, python-format
msgid "Failed to upload the configdrive to Swift. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:1486
#, python-format
msgid "Failed to prepare to deploy. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:1494
#, python-format
msgid "Failed to deploy. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:1528
#, python-format
msgid "Failed to tear down. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:1548
#, python-format
msgid ""
"During sync_power_state, max retries exceeded for node %(node)s, node "
"state %(actual)s does not match expected state '%(state)s'. Updating DB "
"state to '%(actual)s' Switching node to maintenance mode."
msgstr ""

#: ironic/conductor/manager.py:1594
msgid "Power driver returned ERROR state while trying to sync power state."
msgstr ""

#: ironic/conductor/rpcapi.py:105
#, python-format
msgid "No conductor service registered which supports driver %s."
msgstr ""

#: ironic/conductor/utils.py:71 ironic/conductor/utils.py:118
#, python-format
msgid "Failed to change power state to '%(target)s'. Error: %(error)s"
msgstr ""

#: ironic/conductor/utils.py:139
#, python-format
msgid "Timeout reached while waiting for callback for node %s"
msgstr ""

#: ironic/conductor/utils.py:145
#, python-format
msgid "Cleanup failed for node %(node)s after deploy timeout:  %(error)s"
msgstr ""

#: ironic/conductor/utils.py:157
msgid ""
"Deploy timed out, but an unhandled exception was encountered while "
"aborting. More info may be found in the log file."
msgstr ""

#: ironic/db/sqlalchemy/api.py:338
msgid "Cannot overwrite UUID for an existing Node."
msgstr ""

#: ironic/db/sqlalchemy/api.py:425
msgid "Cannot overwrite UUID for an existing Port."
msgstr ""

#: ironic/db/sqlalchemy/api.py:488
msgid "Cannot overwrite UUID for an existing Chassis."
msgstr ""

#: ironic/dhcp/neutron.py:70
msgid "Neutron auth_strategy should be either \"noauth\" or \"keystone\"."
msgstr ""

#: ironic/dhcp/neutron.py:161
#, python-format
msgid ""
"No VIFs found for node %(node)s when attempting to update DHCP BOOT "
"options."
msgstr ""

#: ironic/dhcp/neutron.py:175
#, python-format
msgid "Failed to set DHCP BOOT options for any port on node %s."
msgstr ""

#: ironic/drivers/agent.py:103 ironic/drivers/fake.py:197
#: ironic/drivers/pxe.py:231
msgid "Unable to import pyremotevbox library"
msgstr ""

#: ironic/drivers/drac.py:34 ironic/drivers/fake.py:159
msgid "Unable to import pywsman library"
msgstr ""

#: ironic/drivers/fake.py:96
msgid "Unable to import pyghmi IPMI library"
msgstr ""

#: ironic/drivers/fake.py:110 ironic/drivers/pxe.py:114
msgid "Unable to import seamicroclient library"
msgstr ""

#: ironic/drivers/fake.py:134 ironic/drivers/pxe.py:142
msgid "Unable to import iboot library"
msgstr ""

#: ironic/drivers/fake.py:146 ironic/drivers/ilo.py:43 ironic/drivers/ilo.py:66
#: ironic/drivers/pxe.py:162
msgid "Unable to import proliantutils library"
msgstr ""

#: ironic/drivers/fake.py:173 ironic/drivers/pxe.py:184
msgid "Unable to import pysnmp library"
msgstr ""

#: ironic/drivers/fake.py:185 ironic/drivers/pxe.py:207
msgid "Unable to import python-scciclient library"
msgstr ""

#: ironic/drivers/pxe.py:91
msgid "Unable to import pyghmi library"
msgstr ""

#: ironic/drivers/utils.py:78
msgid "Method not specified when calling vendor extension."
msgstr ""

#: ironic/drivers/utils.py:216
#, python-format
msgid ""
"Invalid %(capability)s parameter '%(value)s'. Acceptable values are: "
"%(valid_values)s."
msgstr ""

#: ironic/drivers/modules/agent.py:182
#, python-format
msgid "Node %s failed to validate deploy image info. Some parameters were missing"
msgstr ""

#: ironic/drivers/modules/agent.py:336
#, python-format
msgid "node %(node)s command status errored: %(error)s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:119
msgid "Missing parameter version"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:122
#, python-format
msgid "Unknown lookup payload version: %s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:149
msgid "For heartbeat operation, \"agent_url\" must be specified."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:158
msgid "Failed checking if deploy is done."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:161
msgid "Node failed to get image for deploy."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:165
msgid "Node failed to move to active state."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:245
#, python-format
msgid "Malformed network interfaces lookup: %s"
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:274
#, python-format
msgid "No ports matching the given MAC addresses %sexist in the database."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:322
#, python-format
msgid ""
"Ports matching mac addresses match multiple nodes. MACs: %(macs)s. Port "
"ids: %(port_ids)s"
msgstr ""

#: ironic/drivers/modules/agent_client.py:48
msgid "Agent driver requires agent_url in driver_internal_info"
msgstr ""

#: ironic/drivers/modules/console_utils.py:89
#, python-format
msgid ""
"Cannot create directory '%(path)s' for console PID file. Reason: "
"%(reason)s."
msgstr ""

#: ironic/drivers/modules/console_utils.py:210
#, python-format
msgid ""
"%(exec_error)s\n"
"Command: %(command)s"
msgstr ""

#: ironic/drivers/modules/console_utils.py:227
#, python-format
msgid ""
"Command: %(command)s.\n"
"Exit code: %(return_code)s.\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: ironic/drivers/modules/console_utils.py:238
#, python-format
msgid "Timeout while waiting for console subprocess to start for node %s."
msgstr ""

#: ironic/drivers/modules/console_utils.py:265
#, python-format
msgid "Could not stop the console for node '%(node)s'. Reason: %(err)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:117
#, python-format
msgid ""
"iSCSI connection was not seen by the file system after attempting to "
"verify %d times."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:140
#, python-format
msgid ""
"iSCSI connection did not become active after attempting to verify %d "
"times."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:406
#, python-format
msgid ""
"Can't download the configdrive content for node %(node)s from '%(url)s'. "
"Reason: %(reason)s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:415
#, python-format
msgid ""
"Config drive for node %s is not base64 encoded or the content is "
"malformed."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:418
#, python-format
msgid " Downloaded from \"%s\"."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:431
#, python-format
msgid ""
"Encountered error while decompressing and writing config drive for node "
"%(node)s. Error: %(exc)s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:468
#, python-format
msgid "Parent device '%s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:496
#, python-format
msgid "Root device '%s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:505
#, python-format
msgid "'%(partition)s' device '%(part_device)s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:613
#, python-format
msgid "%(error_msg)s. Missing are: %(missing_info)s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:701
#, python-format
msgid ""
"Error parsing capabilities from Node %s instance_info field. A dictionary"
" or a dictionary string is expected."
msgstr ""

#: ironic/drivers/modules/fake.py:48 ironic/drivers/modules/ipminative.py:338
#, python-format
msgid "set_power_state called with an invalid power state: %s."
msgstr ""

#: ironic/drivers/modules/fake.py:96
msgid "Parameter 'bar' not passed to method 'first_method'."
msgstr ""

#: ironic/drivers/modules/fake.py:100
msgid "Test if the value of bar is baz"
msgstr ""

#: ironic/drivers/modules/fake.py:116
#, python-format
msgid "Parameter 'bar' not passed to method '%s'."
msgstr ""

#: ironic/drivers/modules/fake.py:120
msgid "Test if the value of bar is kazoo"
msgstr ""

#: ironic/drivers/modules/fake.py:125
msgid "Test if the value of bar is meow"
msgstr ""

#: ironic/drivers/modules/fake.py:163 ironic/drivers/modules/ipminative.py:404
#: ironic/drivers/modules/ipmitool.py:723
#: ironic/drivers/modules/seamicro.py:571 ironic/drivers/modules/ssh.py:644
#: ironic/drivers/modules/virtualbox.py:338
#: ironic/drivers/modules/ilo/management.py:132
#, python-format
msgid "Invalid boot device %s specified."
msgstr ""

#: ironic/drivers/modules/iboot.py:38
msgid "IP address of the node. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:39 ironic/drivers/modules/seamicro.py:71
msgid "username. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:40 ironic/drivers/modules/seamicro.py:69
msgid "password. Required."
msgstr ""

#: ironic/drivers/modules/iboot.py:43
msgid "iBoot PDU relay id; default is 1. Optional."
msgstr ""

#: ironic/drivers/modules/iboot.py:44
msgid "iBoot PDU port; default is 9100. Optional."
msgstr ""

#: ironic/drivers/modules/iboot.py:54
#, python-format
msgid "Missing the following iBoot credentials in node's driver_info: %s."
msgstr ""

#: ironic/drivers/modules/iboot.py:66
msgid "iBoot PDU relay id must be an integer."
msgstr ""

#: ironic/drivers/modules/iboot.py:73
msgid "iBoot PDU port must be an integer."
msgstr ""

#: ironic/drivers/modules/iboot.py:108
#, python-format
msgid "Cannot get power status for node '%(node)s'. iBoot get_relays() failed."
msgstr ""

#: ironic/drivers/modules/iboot.py:185 ironic/drivers/modules/ipmitool.py:642
#: ironic/drivers/modules/snmp.py:672 ironic/drivers/modules/ssh.py:561
#, python-format
msgid "set_power_state called with invalid power state %s."
msgstr ""

#: ironic/drivers/modules/ipminative.py:63
msgid "IP of the node's BMC. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:64
msgid "IPMI password. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:65
msgid "IPMI username. Required."
msgstr ""

#: ironic/drivers/modules/ipminative.py:68
#: ironic/drivers/modules/ipmitool.py:96 ironic/drivers/modules/seamicro.py:80
#: ironic/drivers/modules/ilo/common.py:72
msgid "node's UDP port to connect to. Only required for console access."
msgstr ""

#: ironic/drivers/modules/ipminative.py:92
#: ironic/drivers/modules/ipmitool.py:212
#, python-format
msgid "Missing the following IPMI credentials in node's driver_info: %s."
msgstr ""

#: ironic/drivers/modules/ipminative.py:110
#: ironic/drivers/modules/ipmitool.py:232
msgid "IPMI terminal port is not an integer."
msgstr ""

#: ironic/drivers/modules/ipminative.py:494
#: ironic/drivers/modules/ipmitool.py:940
msgid "Missing 'ipmi_terminal_port' parameter in node's driver_info."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:70
msgid "IP address or hostname of the node. Required."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:73
msgid "password. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:74
#, python-format
msgid "privilege level; default is ADMINISTRATOR. One of %s. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:76
msgid "username; default is NULL user. Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:77
msgid ""
"bridging_type; default is \"no\". One of \"single\", \"dual\", \"no\". "
"Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:79
msgid ""
"transit channel for bridged request. Required only if ipmi_bridging is "
"set to \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:81
msgid ""
"transit address for bridged request. Required only if ipmi_bridging is "
"set to \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:83
msgid ""
"destination channel for bridged request. Required only if ipmi_bridging "
"is set to \"single\" or \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:86
msgid ""
"destination address for bridged request. Required only if ipmi_bridging "
"is set to \"single\" or \"dual\"."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:89
msgid ""
"local IPMB address for bridged requests. Used only if ipmi_bridging is "
"set to \"single\" or \"dual\". Optional."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:243
#, python-format
msgid ""
"Value for ipmi_bridging is provided as %s, but IPMI bridging is not "
"supported by the IPMI utility installed on host. Ensure ipmitool version "
"is > 1.8.11"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:266
#, python-format
msgid "%(param)s not provided"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:269
#, python-format
msgid ""
"Invalid value for ipmi_bridging: %(bridging_type)s, the valid value can "
"be one of: %(bridging_types)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:277
#, python-format
msgid ""
"Invalid privilege level value:%(priv_level)s, the valid value can be one "
"of %(valid_levels)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:507
#, python-format
msgid "parse ipmi sensor data failed, unknown sensor type data: %(sensors_data)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:545
#, python-format
msgid ""
"parse ipmi sensor data failed, get nothing with input data: "
"%(sensors_data)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:587
#: ironic/drivers/modules/ipmitool.py:678
#: ironic/drivers/modules/ipmitool.py:830
#: ironic/drivers/modules/ipmitool.py:922
msgid ""
"Unable to locate usable ipmitool command in the system path when checking"
" ipmitool version"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:906
msgid "Parameter raw_bytes (string of bytes) was not specified."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:119
msgid ""
"Cannot validate iSCSI deploy. Some parameters were missing in node's "
"instance_info"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:131
#, python-format
msgid ""
"Cannot validate parameter for iSCSI deploy. Invalid parameter %(param)s. "
"Reason: %(reason)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:137
#, python-format
msgid "'%s' is not an integer value."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:166
#, python-format
msgid ""
"Root partition is too small for requested image. Image size: %(image_mb)d"
" MB, Root size: %(root_mb)d MB"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:221
msgid "Deploy key does not match"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:237
#, python-format
msgid "Parameters %s were not passed to ironic for deploy."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:268
msgid "Failure in deploy ramdisk."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:282 ironic/drivers/modules/pxe.py:518
#: ironic/drivers/modules/ilo/deploy.py:528
msgid "Failed to continue iSCSI deployment."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:389
#, python-format
msgid "Failed to connect to Glance to get the properties of the image %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:393
#, python-format
msgid "Image %s not found in Glance"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:403
#, python-format
msgid "Image %(image)s is missing the following properties: %(properties)s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:423 ironic/drivers/modules/ssh.py:508
#, python-format
msgid "Node %s does not have any port associated with it."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:432
#, python-format
msgid ""
"Couldn't get the URL of the Ironic API service from the configuration "
"file or keystone catalog. Keystone error: %s"
msgstr ""

#: ironic/drivers/modules/pxe.py:100
msgid "UUID (from Glance) of the deployment kernel. Required."
msgstr ""

#: ironic/drivers/modules/pxe.py:102
msgid "UUID (from Glance) of the ramdisk that is mounted at boot time. Required."
msgstr ""

#: ironic/drivers/modules/pxe.py:124
msgid ""
"Cannot validate PXE bootloader. Some parameters were missing in node's "
"driver_info"
msgstr ""

#: ironic/drivers/modules/pxe.py:315
#, python-format
msgid ""
"Local boot is requested, but can't be used with node %s because it's "
"configured to use UEFI boot"
msgstr ""

#: ironic/drivers/modules/pxe.py:323
msgid "iPXE boot is enabled but no HTTP URL or HTTP root was specified."
msgstr ""

#: ironic/drivers/modules/pxe.py:330
#, python-format
msgid ""
"Conflict: iPXE is enabled, but cannot be used with node%(node_uuid)s "
"configured to use UEFI boot"
msgstr ""

#: ironic/drivers/modules/seamicro.py:68
msgid "API endpoint. Required."
msgstr ""

#: ironic/drivers/modules/seamicro.py:70
msgid "server ID. Required."
msgstr ""

#: ironic/drivers/modules/seamicro.py:74
msgid "version of SeaMicro API client; default is 2. Optional."
msgstr ""

#: ironic/drivers/modules/seamicro.py:101
#, python-format
msgid "Invalid 'seamicro_api_version' parameter. Reason: %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:117
#, python-format
msgid ""
"SeaMicro driver requires the following parameters to be set in node's "
"driver_info: %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:132
msgid "SeaMicro terminal port is not an integer."
msgstr ""

#: ironic/drivers/modules/seamicro.py:137
msgid ""
"Invalid 'seamicro_server_id' parameter in node's driver_info. Expected "
"format of 'seamicro_server_id' is <int>/<int>"
msgstr ""

#: ironic/drivers/modules/seamicro.py:144
msgid "Invalid 'seamicro_api_endpoint' parameter in node's driver_info."
msgstr ""

#: ironic/drivers/modules/seamicro.py:339
msgid "Invalid volume id specified"
msgstr ""

#: ironic/drivers/modules/seamicro.py:355
msgid "No storage pools found for ironic"
msgstr ""

#: ironic/drivers/modules/seamicro.py:425
msgid "set_power_state called with invalid power state."
msgstr ""

#: ironic/drivers/modules/seamicro.py:466
msgid "No vlan id provided"
msgstr ""

#: ironic/drivers/modules/seamicro.py:507
msgid "No volume size provided for creating volume"
msgstr ""

#: ironic/drivers/modules/seamicro.py:633
msgid "Missing 'seamicro_terminal_port' parameter in node's driver_info"
msgstr ""

#: ironic/drivers/modules/snmp.py:73
msgid "PDU manufacturer driver.  Required."
msgstr ""

#: ironic/drivers/modules/snmp.py:74
msgid "PDU IPv4 address or hostname.  Required."
msgstr ""

#: ironic/drivers/modules/snmp.py:75
msgid "PDU power outlet index (1-based).  Required."
msgstr ""

#: ironic/drivers/modules/snmp.py:79
#, python-format
msgid "SNMP protocol version: %(v1)s, %(v2c)s, %(v3)s  (optional, default %(v1)s)"
msgstr ""

#: ironic/drivers/modules/snmp.py:83
#, python-format
msgid "SNMP port, default %(port)d"
msgstr ""

#: ironic/drivers/modules/snmp.py:85
#, python-format
msgid "SNMP community.  Required for versions %(v1)s, %(v2c)s"
msgstr ""

#: ironic/drivers/modules/snmp.py:88
#, python-format
msgid "SNMP security name.  Required for version %(v3)s"
msgstr ""

#: ironic/drivers/modules/snmp.py:547
#, python-format
msgid ""
"SNMP driver requires the following parameters to be set in node's "
"driver_info: %s."
msgstr ""

#: ironic/drivers/modules/snmp.py:556
#, python-format
msgid "SNMPPowerDriver: unknown driver: '%s'"
msgstr ""

#: ironic/drivers/modules/snmp.py:562
#, python-format
msgid "SNMPPowerDriver: unknown SNMP version: '%s'"
msgstr ""

#: ironic/drivers/modules/snmp.py:571
#, python-format
msgid "SNMPPowerDriver: SNMP UDP port must be numeric: %s"
msgstr ""

#: ironic/drivers/modules/snmp.py:574
#, python-format
msgid "SNMPPowerDriver: SNMP UDP port out of range: %d"
msgstr ""

#: ironic/drivers/modules/snmp.py:581
#, python-format
msgid "SNMP driver requires snmp_community to be set for version %s."
msgstr ""

#: ironic/drivers/modules/snmp.py:587
#, python-format
msgid "SNMP driver requires snmp_security to be set for version %s."
msgstr ""

#: ironic/drivers/modules/ssh.py:58
msgid "IP address or hostname of the node to ssh into. Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:60
msgid "username to authenticate as. Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:61
msgid ""
"virtualization software to use; one of vbox, virsh, vmware, parallels. "
"Required."
msgstr ""

#: ironic/drivers/modules/ssh.py:65
msgid ""
"private key(s). One of this, ssh_key_filename, or ssh_password must be "
"specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:67
msgid ""
"(list of) filename(s) of optional private key(s) for authentication. One "
"of this, ssh_key_contents, or ssh_password must be specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:70
msgid ""
"password to use for authentication or for unlocking a private key. One of"
" this, ssh_key_contents, or ssh_key_filename must be specified."
msgstr ""

#: ironic/drivers/modules/ssh.py:73
msgid "port on the node to connect to; default is 22. Optional."
msgstr ""

#: ironic/drivers/modules/ssh.py:105
#, python-format
msgid "SSHPowerDriver '%(virt_type)s' is not a valid virt_type."
msgstr ""

#: ironic/drivers/modules/ssh.py:196
#, python-format
msgid "SSHPowerDriver '%(virt_type)s' is not a valid virt_type, "
msgstr ""

#: ironic/drivers/modules/ssh.py:287
#, python-format
msgid ""
"SSHPowerDriver requires the following parameters to be set in node's "
"driver_info: %s."
msgstr ""

#: ironic/drivers/modules/ssh.py:297
msgid "SSHPowerDriver requires ssh_port to be integer value"
msgstr ""

#: ironic/drivers/modules/ssh.py:318
msgid ""
"SSHPowerDriver requires one and only one of password, key_contents and "
"key_filename to be set."
msgstr ""

#: ironic/drivers/modules/ssh.py:327
#, python-format
msgid "SSH key file %s not found."
msgstr ""

#: ironic/drivers/modules/ssh.py:513
#, python-format
msgid "SSH connection cannot be established: %s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:59
msgid "Name of the VM in VirtualBox. Required."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:60
msgid "IP address or hostname of the VirtualBox host. Required."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:65
msgid "Username for the VirtualBox host. Default value is ''. Optional."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:67
msgid "Password for 'virtualbox_username'. Default value is ''. Optional."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:69
msgid "Port on which VirtualBox web service is listening. Optional."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:111
#, python-format
msgid "The following parameters are missing in driver_info: %s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:123
msgid "'virtualbox_port' is not an integer."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:169
#, python-format
msgid "Invalid VirtualMachine method '%s' passed to '_run_virtualbox_method'."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:245
#, python-format
msgid "'set_power_state' called with invalid power state '%s'"
msgstr ""

#: ironic/drivers/modules/drac/common.py:26
msgid "IP address or hostname of the DRAC card. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:27
msgid "username used for authentication. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:28
msgid "password used for authentication. Required."
msgstr ""

#: ironic/drivers/modules/drac/common.py:31
msgid "port used for WS-Man endpoint; default is 443. Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:32
msgid "path used for WS-Man endpoint; default is \"/wsman\". Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:34
msgid ""
"protocol used for WS-Man endpoint; one of http, https; default is "
"\"https\". Optional."
msgstr ""

#: ironic/drivers/modules/drac/common.py:61
#, python-format
msgid "'%s' not supplied to DracDriver."
msgstr ""

#: ironic/drivers/modules/drac/common.py:63
#, python-format
msgid "'%s' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:71
msgid "'drac_path' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:77
msgid "'drac_protocol' contains non-ASCII symbol."
msgstr ""

#: ironic/drivers/modules/drac/common.py:82
msgid "'drac_port' is not an integer value."
msgstr ""

#: ironic/drivers/modules/drac/common.py:85
#, python-format
msgid ""
"The following errors were encountered while parsing driver_info:\n"
"%s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:62
msgid "IP address or hostname of the iLO. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:63
msgid "username for the iLO with administrator privileges. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:65
msgid "password for ilo_username. Required."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:68
msgid "port to be used for iLO operations. Optional."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:69
msgid "timeout (in seconds) for iLO operations. Optional."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:108
#, python-format
msgid ""
"The following required iLO parameters are missing from the node's "
"driver_info: %s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:129
#, python-format
msgid ""
"The following iLO parameters from the node's driver_info should be "
"integers: %s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:177
msgid "iLO license check"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:289
#, python-format
msgid "Inserting virtual media %s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:319
#, python-format
msgid "Setting %s as boot mode"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:47
msgid "UUID (from Glance) of the deployment ISO. Required."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:177
msgid ""
"Error validating iLO virtual media deploy. Some parameters were missing "
"in node's driver_info"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:446
msgid "Missing 'console_port' parameter in node's driver_info."
msgstr ""

#: ironic/drivers/modules/ilo/management.py:100
msgid "Get boot device"
msgstr ""

#: ironic/drivers/modules/ilo/management.py:143
#, python-format
msgid "Setting %s as boot device"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:88
msgid "iLO get_power_status"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:152
#: ironic/drivers/modules/irmc/power.py:60
#, python-format
msgid "_set_power_state called with invalid power state '%s'"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:161
msgid "iLO set_power_state"
msgstr ""

#: ironic/drivers/modules/irmc/common.py:46
msgid "IP address or hostname of the iRMC. Required."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:47
msgid "Username for the iRMC with administrator privileges. Required."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:49
msgid "Password for irmc_username. Required."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:52
msgid ""
"Port to be used for iRMC operations; either 80 or 443. The default value "
"is 443. Optional."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:54
msgid ""
"Authentication method for iRMC operations; either 'basic' or 'digest'. "
"The default value is 'digest'. Optional."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:57
msgid ""
"Timeout (in seconds) for iRMC operations. The default value is 60. "
"Optional."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:82
#, python-format
msgid "Missing the following iRMC parameters in node's driver_info: %s."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:96
#: ironic/drivers/modules/irmc/common.py:99
#, python-format
msgid "'%s' has unsupported value."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:102
#, python-format
msgid "'%s' is not integer type."
msgstr ""

#: ironic/drivers/modules/irmc/common.py:104
#, python-format
msgid ""
"The following type errors were encountered while parsing driver_info:\n"
"%s"
msgstr ""

#: ironic/drivers/modules/irmc/power.py:69
msgid "iRMC set_power_state"
msgstr ""

#: ironic/objects/base.py:161
msgid "Invalid version string"
msgstr ""

#: ironic/objects/base.py:350
#, python-format
msgid "Cannot load '%(attrname)s' in the base class"
msgstr ""

#: ironic/objects/base.py:359
msgid "Cannot save anything in the base class"
msgstr ""

#: ironic/objects/base.py:391
#, python-format
msgid "%(objname)s object has no attribute '%(attrname)s'"
msgstr ""

#: ironic/objects/base.py:440
#, python-format
msgid "'%(objclass)s' object has no attribute '%(attrname)s'"
msgstr ""

#: ironic/objects/conductor.py:56
msgid "Cannot update a conductor record directly."
msgstr ""

#: ironic/objects/utils.py:40
msgid "A datetime.datetime is required here"
msgstr ""

#: ironic/objects/utils.py:105
#, python-format
msgid "An object of class %s is required here"
msgstr ""

#: ironic/openstack/common/cliutils.py:271
#, python-format
msgid "No %(name)s with a name or ID of '%(name_or_id)s' exists."
msgstr ""

#: ironic/openstack/common/cliutils.py:279
#, python-format
msgid ""
"Multiple %(name)s matches found for '%(name_or_id)s', use an ID to be "
"more specific."
msgstr ""

#: ironic/openstack/common/gettextutils.py:301
msgid "Message objects do not support addition."
msgstr ""

#: ironic/openstack/common/gettextutils.py:311
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: ironic/openstack/common/imageutils.py:75
#, python-format
msgid "Invalid input value \"%s\"."
msgstr ""

#: ironic/openstack/common/imageutils.py:104
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: ironic/openstack/common/log.py:298
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: ironic/openstack/common/log.py:406
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: ironic/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: ironic/openstack/common/log.py:715
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: ironic/openstack/common/periodic_task.py:46
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr ""

#: ironic/openstack/common/policy.py:111
msgid "The JSON file that defines policies."
msgstr ""

#: ironic/openstack/common/policy.py:114
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: ironic/openstack/common/policy.py:118
msgid ""
"Directories where policy configuration files are stored. They can be "
"relative to any directory in the search path defined by the config_dir "
"option, or absolute paths. The file defined by policy_file must exist for"
" these directories to be searched."
msgstr ""

#: ironic/openstack/common/policy.py:142
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: ironic/openstack/common/policy.py:239
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: ironic/openstack/common/strutils.py:114
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: ironic/openstack/common/strutils.py:219
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: ironic/openstack/common/strutils.py:228
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: ironic/openstack/common/versionutils.py:88
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: ironic/openstack/common/versionutils.py:92
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: ironic/openstack/common/versionutils.py:96
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: ironic/openstack/common/versionutils.py:99
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: ironic/openstack/common/apiclient/base.py:224
#: ironic/openstack/common/apiclient/base.py:381
#, python-format
msgid "No %(name)s matching %(args)s."
msgstr ""

#: ironic/openstack/common/apiclient/client.py:233
msgid "Cannot find endpoint or token for request"
msgstr ""

#: ironic/openstack/common/apiclient/client.py:356
#, python-format
msgid ""
"Invalid %(api_name)s client version '%(version)s'. Must be one of: "
"%(version_map)s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:41
#, python-format
msgid "Missing arguments: %s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:74
#, python-format
msgid "Authentication failed. Missing options: %s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:83
#, python-format
msgid "AuthSystemNotFound: %s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:106
#, python-format
msgid "AmbiguousEndpoints: %s"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:114
msgid "HTTP Error"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:134
msgid "HTTP Redirection"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:142
msgid "HTTP Client Error"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:151
msgid "HTTP Server Error"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:161
msgid "Multiple Choices"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:170
msgid "Bad Request"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:180
msgid "Unauthorized"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:189
msgid "Payment Required"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:199
msgid "Forbidden"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:209
msgid "Not Found"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:219
msgid "Method Not Allowed"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:229
msgid "Not Acceptable"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:238
msgid "Proxy Authentication Required"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:247
msgid "Request Timeout"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:257
msgid "Conflict"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:267
msgid "Gone"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:277
msgid "Length Required"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:287
msgid "Precondition Failed"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:296
msgid "Request Entity Too Large"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:313
msgid "Request-URI Too Long"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:323
msgid "Unsupported Media Type"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:333
msgid "Requested Range Not Satisfiable"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:342
msgid "Expectation Failed"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:352
msgid "Unprocessable Entity"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:361
msgid "Internal Server Error"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:372
msgid "Not Implemented"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:382
msgid "Bad Gateway"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:391
msgid "Service Unavailable"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:401
msgid "Gateway Timeout"
msgstr ""

#: ironic/openstack/common/apiclient/exceptions.py:410
msgid "HTTP Version Not Supported"
msgstr ""

