# Translations template for ironic.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ironic project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ironic 4.2.1.dev157\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-23 06:32+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: ironic/api/middleware/parsable_error.py:80
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ironic/common/exception.py:89
msgid "Exception in string format operation"
msgstr ""

#: ironic/common/images.py:149
#, python-format
msgid "vfat image creation failed. Error: %s"
msgstr ""

#: ironic/common/images.py:219 ironic/common/images.py:285
msgid "Creating the filesystem root failed."
msgstr ""

#: ironic/common/images.py:234 ironic/common/images.py:311
msgid "Creating ISO image failed."
msgstr ""

#: ironic/common/images.py:547
msgid "mounting the deploy iso failed."
msgstr ""

#: ironic/common/images.py:561
msgid "examining the deploy iso failed."
msgstr ""

#: ironic/common/service.py:91
#, python-format
msgid "Service error occurred when stopping the RPC server. Error: %s"
msgstr ""

#: ironic/common/service.py:96
#, python-format
msgid "Service error occurred when cleaning up the RPC manager. Error: %s"
msgstr ""

#: ironic/common/utils.py:426
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: ironic/common/utils.py:460
#, python-format
msgid "Failed to make file system. File system %s is not supported."
msgstr ""

#: ironic/common/utils.py:464
#, python-format
msgid "Failed to create a file system in %(path)s. Error: %(error)s"
msgstr ""

#: ironic/common/glance_service/base_image_service.py:128
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"attempt %(attempt)s of %(num_attempts)s failed."
msgstr ""

#: ironic/conductor/manager.py:264
#, python-format
msgid ""
"Conductor %s cannot be started because no drivers were loaded.  This "
"could be because no drivers were specified in 'enabled_drivers' config "
"option."
msgstr ""

#: ironic/conductor/manager.py:807
#, python-format
msgid "Error in tear_down of node %(node)s: %(err)s"
msgstr ""

#: ironic/conductor/manager.py:1113
#, python-format
msgid ""
"Failed to tear down cleaning for node %(node)s after aborting the "
"operation. Error: %(err)s"
msgstr ""

#: ironic/conductor/manager.py:1573
#, python-format
msgid "Failed to stop console while deleting the node %(node)s: %(err)s."
msgstr ""

#: ironic/conductor/manager.py:2369
#, python-format
msgid "Error while uploading the configdrive for %(node)s to Swift"
msgstr ""

#: ironic/conductor/manager.py:2380
#, python-format
msgid "Error while preparing to deploy to node %(node)s: %(err)s"
msgstr ""

#: ironic/conductor/manager.py:2390
#, python-format
msgid "Error in deploy of node %(node)s: %(err)s"
msgstr ""

#: ironic/conductor/manager.py:2407
#, python-format
msgid "Unexpected state %(state)s returned while deploying node %(node)s."
msgstr ""

#: ironic/conductor/manager.py:2533
#, python-format
msgid ""
"Failed to change power state of node %(node)s to '%(state)s', attempt "
"%(attempt)s of %(retries)s."
msgstr ""

#: ironic/conductor/manager.py:2567
#, python-format
msgid "Failed to inspect node %(node)s: %(err)s"
msgstr ""

#: ironic/conductor/manager.py:2603
#, python-format
msgid "Failed to tear down cleaning on node %(uuid)s, reason: %(err)s"
msgstr ""

#: ironic/dhcp/neutron.py:128
#, python-format
msgid "Failed to update Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:143
#, python-format
msgid "Failed to update MAC address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:216
#, python-format
msgid "Failed to Get IP address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:232
#, python-format
msgid "Neutron returned invalid IPv4 address %s."
msgstr ""

#: ironic/dhcp/neutron.py:236
#, python-format
msgid "No IP address assigned to Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:379
#, python-format
msgid "Failed to rollback cleaning port changes for node %s"
msgstr ""

#: ironic/drivers/base.py:625
#, python-format
msgid "vendor_passthru failed with method %s"
msgstr ""

#: ironic/drivers/modules/agent.py:118
#, python-format
msgid ""
"Agent deploy supports only HTTP(S) URLs as instance_info['image_source']."
" Either %s is not a valid HTTP(S) URL or is not reachable."
msgstr ""

#: ironic/drivers/modules/agent_base_vendor.py:515
#, python-format
msgid "Could not find matching node for the provided MACs %s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:516
#, python-format
msgid ""
"Failed to erase beginning of disk for node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:528
#, python-format
msgid ""
"Failed to get disk block count for node %(node)s. Command: %(command)s. "
"Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:540
#, python-format
msgid ""
"Failed to erase the end of the disk on node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:737
#, python-format
msgid "Failed to detect %s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:835
#: ironic/drivers/modules/deploy_utils.py:841
#, python-format
msgid "Deploy to address %s failed."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:836
#, python-format
msgid "Command: %s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:837
#, python-format
msgid "StdOut: %r"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:838
#, python-format
msgid "StdErr: %r"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:923
#, python-format
msgid ""
"Internal error. Node %(node)s in provision state \"%(state)s\" could not "
"transition to a failed state."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:931
#, python-format
msgid ""
"Node %s failed to power off while handling deploy failure. This may be a "
"serious condition. Node should be removed from Ironic or put in "
"maintenance mode until the problem is resolved."
msgstr ""

#: ironic/drivers/modules/inspector.py:156
#, python-format
msgid ""
"Exception during contacting ironic-inspector for inspection of node "
"%(node)s: %(err)s"
msgstr ""

#: ironic/drivers/modules/inspector.py:191
#, python-format
msgid ""
"Unexpected exception while getting inspection status for node %s, will "
"retry later"
msgstr ""

#: ironic/drivers/modules/inspector.py:207
#, python-format
msgid "Inspection failed for node %(uuid)s with error: %(err)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:285
#, python-format
msgid ""
"IPMI get sensor data failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:487
#, python-format
msgid ""
"IPMI set boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:533
#, python-format
msgid ""
"IPMI get boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:418
#, python-format
msgid "IPMI Error while attempting \"%(cmd)s\"for node %(node)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:493
#, python-format
msgid ""
"IPMI power %(state)s timed out after %(tries)s retries on node "
"%(node_id)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:656
#, python-format
msgid "IPMI \"raw bytes\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:1011
#, python-format
msgid "IPMI \"bmc reset\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:625
#: ironic/drivers/modules/iscsi_deploy.py:936
#: ironic/drivers/modules/iscsi_deploy.py:975
#: ironic/drivers/modules/ilo/deploy.py:1035
#: ironic/drivers/modules/irmc/deploy.py:871
#, python-format
msgid "Deploy failed for instance %(instance)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:296
msgid "Whole disk image with netboot is not supported in UEFI boot mode."
msgstr ""

#: ironic/drivers/modules/pxe.py:408
msgid "UEFI boot mode is not supported with iPXE boot enabled."
msgstr ""

#: ironic/drivers/modules/seamicro.py:198
#, python-format
msgid "SeaMicro client exception %(msg)s for node %(uuid)s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:479
#: ironic/drivers/modules/seamicro.py:518
#, python-format
msgid "SeaMicro client exception: %s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:582
#, python-format
msgid ""
"Seamicro set boot device failed for node %(node)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ssh.py:308
#, python-format
msgid "Cannot execute SSH cmd %(cmd)s. Reason: %(err)s."
msgstr ""

#: ironic/drivers/modules/ssh.py:710
#, python-format
msgid ""
"Failed to set boot device for node %(node)s, virt_type %(vtype)s does not"
" support this operation"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:161
#, python-format
msgid ""
"Failed while creating a VirtualMachine object for node %(node_id)s. "
"Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:177
#, python-format
msgid "'%(ironic_method)s' failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/virtualbox.py:219
#, python-format
msgid "VirtualBox returned unknown state '%(state)s' for node %(node)s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:315
#, python-format
msgid "VirtualBox returned unknown boot device '%(device)s' for node %(node)s"
msgstr ""

#: ironic/drivers/modules/virtualbox.py:356
#, python-format
msgid "'set_boot_device' failed for node %(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/amt/common.py:105
#, python-format
msgid "Call to AMT with URI %(uri)s failed: got Fault %(fault)s"
msgstr ""

#: ironic/drivers/modules/amt/common.py:129
#, python-format
msgid ""
"Call to AMT with URI %(uri)s and method %(method)s failed: return value "
"was %(value)s"
msgstr ""

#: ironic/drivers/modules/amt/management.py:89
#, python-format
msgid ""
"Failed to set boot device %(boot_device)s for node %(node_id)s with "
"error: %(error)s."
msgstr ""

#: ironic/drivers/modules/amt/management.py:142
#, python-format
msgid "Failed to enable boot config for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/amt/power.py:112
#, python-format
msgid ""
"Failed to set power state %(state)s for node %(node_id)s with error: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/amt/power.py:136
#, python-format
msgid "Failed to get power state for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/bios.py:191
#, python-format
msgid ""
"DRAC driver failed to get BIOS settings for resource %(resource)s from "
"node %(node_uuid)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:95
#, python-format
msgid ""
"DRAC driver failed to get next boot mode for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:149
#, python-format
msgid ""
"DRAC driver failed to get the current boot device for node %(node_uuid)s."
" Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:200
#, python-format
msgid ""
"DRAC driver failed to set the boot device for node %(node_uuid)s. Can't "
"find the ID for the %(device)s type. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:250
#, python-format
msgid ""
"DRAC driver failed to create config job for node %(node_uuid)s. The "
"changes are not applied. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:269
#, python-format
msgid ""
"DRAC driver failed to list the configuration jobs for node %(node_uuid)s."
" Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:311
#: ironic/drivers/modules/drac/power.py:61
#, python-format
msgid ""
"DRAC driver failed to get power state for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:403
#, python-format
msgid ""
"DRAC driver failed to set the boot device for node %(node_uuid)s to "
"%(target_boot_device)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:89
#, python-format
msgid ""
"DRAC driver failed to set power state for node %(node_uuid)s to "
"%(target_power_state)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:492
#, python-format
msgid ""
"Error while ejecting virtual media %(device)s from node %(uuid)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:522
#, python-format
msgid ""
"Error while deleting temporary swift object %(object_name)s from "
"%(container)s associated with virtual floppy. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:167
#, python-format
msgid ""
"Virtual media deploy accepts only Glance images or HTTP(S) URLs as "
"instance_info['ilo_boot_iso']. Either %s is not a valid HTTP(S) URL or is"
" not reachable."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:195
#, python-format
msgid ""
"Unable to find kernel or ramdisk for image %(image)s to generate boot ISO"
" for %(node)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:254
#, python-format
msgid "Failed to clean up boot ISO for node %(node)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:929
#, python-format
msgid "Cannot get boot ISO for node %s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:95
#, python-format
msgid "iLO get_power_state failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/power.py:167
#, python-format
msgid ""
"iLO set_power_state failed to set state to %(tstate)s  for node "
"%(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:180
#, python-format
msgid "iLO failed to change state to %(tstate)s within %(timeout)s sec"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:437
#, python-format
msgid "Error while inserting virtual cdrom from node %(uuid)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:460
#, python-format
msgid "Error while ejecting virtual cdrom from node %(uuid)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:493
#, python-format
msgid "Error while inserting virtual floppy from node %(uuid)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/irmc/deploy.py:516
#, python-format
msgid "Error while ejecting virtual floppy from node %(uuid)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/irmc/management.py:64
#, python-format
msgid ""
"SCCI get sensor data failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/irmc/power.py:94
#, python-format
msgid ""
"iRMC set_power_state failed to set state to %(tstate)s  for node "
"%(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/msftocs/msftocsclient.py:85
#, python-format
msgid "XML parsing failed: %s"
msgstr ""

#: ironic/drivers/modules/msftocs/power.py:87
#, python-format
msgid "Changing the power state to %(pstate)s failed. Error: %(err_msg)s"
msgstr ""

#: ironic/drivers/modules/msftocs/power.py:104
#, python-format
msgid "Reboot failed. Error: %(err_msg)s"
msgstr ""

#: ironic/drivers/modules/oneview/common.py:248
#, python-format
msgid ""
"Failed to get server profile from OneView appliance fornode %(node)s. "
"Error: %(message)s"
msgstr ""

#: ironic/drivers/modules/oneview/power.py:79
#, python-format
msgid "Error getting power state for node %(node)s. Error:%(error)s"
msgstr ""

#: ironic/drivers/modules/ucs/helper.py:118
#, python-format
msgid "Cisco client: service unavailable for node %(uuid)s."
msgstr ""

#: ironic/drivers/modules/ucs/management.py:95
#, python-format
msgid "%(driver)s: client failed to set boot device %(device)s for node %(uuid)s."
msgstr ""

#: ironic/drivers/modules/ucs/management.py:130
#, python-format
msgid "%(driver)s: client failed to get boot device for node %(uuid)s."
msgstr ""

#: ironic/drivers/modules/ucs/power.py:126
#, python-format
msgid ""
"%(driver)s: get_power_state operation failed for node %(uuid)s with "
"error: %(msg)s."
msgstr ""

#: ironic/drivers/modules/ucs/power.py:168
#, python-format
msgid ""
"%(driver)s: set_power_state operation failed for node %(uuid)s with "
"error: %(msg)s."
msgstr ""

#: ironic/drivers/modules/ucs/power.py:179
#, python-format
msgid ""
"%(driver)s: driver failed to change node %(uuid)s power state to "
"%(state)s within %(timeout)s seconds."
msgstr ""

#: ironic/drivers/modules/ucs/power.py:201
#, python-format
msgid "%(driver)s: driver failed to reset node %(uuid)s power state."
msgstr ""

#: ironic/drivers/modules/ucs/power.py:212
#, python-format
msgid ""
"%(driver)s: driver failed to reboot node %(uuid)s within %(timeout)s "
"seconds."
msgstr ""

#: ironic/tests/unit/db/sqlalchemy/test_migrations.py:169
#, python-format
msgid "Failed to migrate to version %(version)s on engine %(engine)s"
msgstr ""

