# Translations template for ironic.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ironic project.
# 
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Ironic\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-03-31 20:53+0000\n"
"PO-Revision-Date: 2014-03-31 18:09+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Tamil (http://www.transifex.com/projects/p/openstack/language/ta/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Language: ta\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ironic/api/controllers/v1/node.py:202
#, python-format
msgid "Node %(node)s is already in the '%(state)s' state."
msgstr ""

#: ironic/api/controllers/v1/node.py:215
#, python-format
msgid "Node %s is already being provisioned or decommissioned."
msgstr ""

#: ironic/api/controllers/v1/node.py:436
msgid "Method not specified"
msgstr ""

#: ironic/api/controllers/v1/node.py:466
msgid "Chassis id not specified."
msgstr ""

#: ironic/api/controllers/v1/node.py:641
#, python-format
msgid "Node %s can not be updated while a state transition is in progress."
msgstr ""

#: ironic/api/controllers/v1/port.py:166
msgid "Node id not specified."
msgstr ""

#: ironic/api/controllers/v1/types.py:128
#, python-format
msgid "'%s' is an internal attribute and can not be updated"
msgstr ""

#: ironic/api/controllers/v1/types.py:132
#, python-format
msgid "'%s' is a mandatory attribute and can not be removed"
msgstr ""

#: ironic/api/controllers/v1/types.py:137
#, python-format
msgid ""
"Adding a new attribute (%s) to the root of  the resource is not allowed"
msgstr ""

#: ironic/api/controllers/v1/types.py:143
msgid "'add' and 'replace' operations needs value"
msgstr ""

#: ironic/api/controllers/v1/types.py:174
#, python-format
msgid "Wrong type. Expected '%(type)s', got '%(value)s'"
msgstr ""

#: ironic/api/controllers/v1/utils.py:31
msgid "Limit must be positive"
msgstr ""

#: ironic/api/controllers/v1/utils.py:38
#, python-format
msgid "Invalid sort direction: %s. Acceptable values are 'asc' or 'desc'"
msgstr ""

#: ironic/api/middleware/auth_token.py:40
#, python-format
msgid "Cannot compile public API routes: %s"
msgstr ""

#: ironic/api/middleware/parsable_error.py:52
#, python-format
msgid "ErrorDocumentMiddleware received an invalid status %s"
msgstr ""

#: ironic/api/middleware/parsable_error.py:80
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ironic/cmd/api.py:53
#, python-format
msgid "Serving on http://%(host)s:%(port)s"
msgstr ""

#: ironic/cmd/api.py:55
msgid "Configuration:"
msgstr ""

#: ironic/common/exception.py:57
msgid "An unknown exception occurred."
msgstr ""

#: ironic/common/exception.py:78 ironic/openstack/common/rpc/common.py:88
msgid "Exception in string format operation"
msgstr ""

#: ironic/common/exception.py:98
msgid "Not authorized."
msgstr ""

#: ironic/common/exception.py:103
msgid "Operation not permitted."
msgstr ""

#: ironic/common/exception.py:107
msgid "Unacceptable parameters."
msgstr ""

#: ironic/common/exception.py:112
msgid "Conflict."
msgstr ""

#: ironic/common/exception.py:117
msgid "Resource temporarily unavailable, please retry."
msgstr ""

#: ironic/common/exception.py:122
msgid "Invalid resource state."
msgstr ""

#: ironic/common/exception.py:126
#, python-format
msgid "A Port with MAC address %(mac)s already exists."
msgstr ""

#: ironic/common/exception.py:130
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: ironic/common/exception.py:134
#, python-format
msgid "Expected an uuid or int but received %(identity)s."
msgstr ""

#: ironic/common/exception.py:138
#, python-format
msgid "Expected a MAC address but received %(mac)s."
msgstr ""

#: ironic/common/exception.py:142
#, python-format
msgid "Invalid state '%(state)s' requested for node %(node)s."
msgstr ""

#: ironic/common/exception.py:146
#, python-format
msgid "Couldn't apply patch '%(patch)s'. Reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:150
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr ""

#: ironic/common/exception.py:154 ironic/common/exception.py:158
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: ironic/common/exception.py:164
#, python-format
msgid "%(err)s"
msgstr ""

#: ironic/common/exception.py:168
msgid "Resource could not be found."
msgstr ""

#: ironic/common/exception.py:173
#, python-format
msgid "Failed to load driver %(driver_name)s."
msgstr ""

#: ironic/common/exception.py:177
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: ironic/common/exception.py:181
#, python-format
msgid "No valid host was found. Reason: %(reason)s"
msgstr ""

#: ironic/common/exception.py:185
#, python-format
msgid "Instance %(instance)s could not be found."
msgstr ""

#: ironic/common/exception.py:189
#, python-format
msgid "Node %(node)s could not be found."
msgstr ""

#: ironic/common/exception.py:193
#, python-format
msgid "Node %(node)s is associated with instance %(instance)s."
msgstr ""

#: ironic/common/exception.py:197
#, python-format
msgid "Port %(port)s could not be found."
msgstr ""

#: ironic/common/exception.py:201
#, python-format
msgid "Update DHCP options on port: %(port_id)s failed."
msgstr ""

#: ironic/common/exception.py:205
#, python-format
msgid "Update MAC address on port: %(port_id)s failed."
msgstr ""

#: ironic/common/exception.py:209
#, python-format
msgid "Chassis %(chassis)s could not be found."
msgstr ""

#: ironic/common/exception.py:213
#, python-format
msgid "Conductor %(conductor)s could not be found."
msgstr ""

#: ironic/common/exception.py:217
#, python-format
msgid "Conductor %(conductor)s already registered."
msgstr ""

#: ironic/common/exception.py:221
#, python-format
msgid "Failed to set node power state to %(pstate)s."
msgstr ""

#: ironic/common/exception.py:225
msgid ""
"An exclusive lock is required, but the current context has a shared lock."
msgstr ""

#: ironic/common/exception.py:230
#, python-format
msgid "Failed to toggle maintenance-mode flag for node %(node)s: %(reason)s"
msgstr ""

#: ironic/common/exception.py:235
#, python-format
msgid "Console access is not enabled on node %(node)s"
msgstr ""

#: ironic/common/exception.py:239
#, python-format
msgid ""
"The %(op)s operation can't be performed on node %(node)s because it's in "
"maintenance mode."
msgstr ""

#: ironic/common/exception.py:244
#, python-format
msgid ""
"Can not change instance association while node %(node)s is in power state "
"%(pstate)s."
msgstr ""

#: ironic/common/exception.py:249
#, python-format
msgid ""
"Cannot complete the requested action because chassis %(chassis)s contains "
"nodes."
msgstr ""

#: ironic/common/exception.py:254
#, python-format
msgid "IPMI call failed: %(cmd)s."
msgstr ""

#: ironic/common/exception.py:258
#, python-format
msgid "Failed to establish SSH connection to host %(host)s."
msgstr ""

#: ironic/common/exception.py:262
#, python-format
msgid "Failed to execute command via SSH: %(cmd)s."
msgstr ""

#: ironic/common/exception.py:266
#, python-format
msgid "Unsupported object type %(objtype)s"
msgstr ""

#: ironic/common/exception.py:270
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""

#: ironic/common/exception.py:274
#, python-format
msgid "Driver %(driver)s does not support %(extension)s."
msgstr ""

#: ironic/common/exception.py:278
#, python-format
msgid "Version %(objver)s of %(objname)s is not supported"
msgstr ""

#: ironic/common/exception.py:282
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr ""

#: ironic/common/exception.py:287
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: ironic/common/exception.py:291
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: ironic/common/exception.py:295
msgid "Unauthorised for keystone service catalog."
msgstr ""

#: ironic/common/exception.py:303
#, python-format
msgid ""
"Service type %(service_type)s with endpoint type %(endpoint_type)s not found"
" in keystone service catalog."
msgstr ""

#: ironic/common/exception.py:308
msgid "Connection failed"
msgstr ""

#: ironic/common/exception.py:312
msgid "Requested OpenStack Images API is forbidden"
msgstr ""

#: ironic/common/exception.py:320
msgid "The provided endpoint is invalid"
msgstr ""

#: ironic/common/exception.py:324
msgid "Unable to communicate with the server."
msgstr ""

#: ironic/common/exception.py:340
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: ironic/common/exception.py:344
#, python-format
msgid ""
"Node %(node)s is locked by host %(host)s, please retry after the current "
"operation is completed."
msgstr ""

#: ironic/common/exception.py:349
msgid ""
"Requested action cannot be performed due to lack of free conductor workers."
msgstr ""

#: ironic/common/exception.py:359
#, python-format
msgid "Invalid configuration file. %(error_msg)s"
msgstr ""

#: ironic/common/hash_ring.py:65
msgid "Invalid hosts supplied when building HashRing."
msgstr ""

#: ironic/common/hash_ring.py:78
msgid "Invalid data supplied to HashRing.get_hosts."
msgstr ""

#: ironic/common/images.py:110
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: ironic/common/images.py:203
msgid "'qemu-img info' parsing failed."
msgstr ""

#: ironic/common/images.py:209
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: ironic/common/images.py:215
#, python-format
msgid "%(image)s was %(format)s, converting to raw"
msgstr ""

#: ironic/common/images.py:224
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: ironic/common/keystone.py:30
msgid "Keystone API endpoint is missing"
msgstr ""

#: ironic/common/keystone.py:53
#, python-format
msgid "Could not perform authorization process for service catalog: %s"
msgstr ""

#: ironic/common/keystone.py:58
msgid "No keystone service catalog loaded"
msgstr ""

#: ironic/common/neutron.py:91
#, python-format
msgid "Failed to update Neutron port %s."
msgstr ""

#: ironic/common/neutron.py:105
#, python-format
msgid "Failed to update MAC address on Neutron port %s."
msgstr ""

#: ironic/common/policy.py:31
msgid "JSON file representing policy."
msgstr ""

#: ironic/common/policy.py:34
msgid "Rule checked when requested rule is not found."
msgstr ""

#: ironic/common/utils.py:65
#, python-format
msgid "Execution completed, command line is \"%s\""
msgstr ""

#: ironic/common/utils.py:66
#, python-format
msgid "Command stdout is: \"%s\""
msgstr ""

#: ironic/common/utils.py:67
#, python-format
msgid "Command stderr is: \"%s\""
msgstr ""

#: ironic/common/utils.py:98
msgid "Invalid private key"
msgstr ""

#: ironic/common/utils.py:112
#, python-format
msgid "SSH connect failed: %s"
msgstr ""

#: ironic/common/utils.py:145
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: ironic/common/utils.py:323 ironic/openstack/common/fileutils.py:65
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: ironic/common/utils.py:411
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: ironic/common/utils.py:446
#, python-format
msgid "Failed to unlink %(path)s, error: %(e)s"
msgstr ""

#: ironic/common/utils.py:455
#, python-format
msgid "Failed to remove dir %(path)s, error: %(e)s"
msgstr ""

#: ironic/common/utils.py:471
#, python-format
msgid "Failed to create symlink from %(source)s to %(link)s, error: %(e)s"
msgstr ""

#: ironic/common/utils.py:485
#, python-format
msgid ""
"Failed to remove trailing character. Returning original object. Supplied "
"object is not a string: %s,"
msgstr ""

#: ironic/common/glance_service/base_image_service.py:125
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""

#: ironic/common/glance_service/base_image_service.py:161
msgid "Getting a full list of images metadata from glance."
msgstr ""

#: ironic/common/glance_service/base_image_service.py:182
#, python-format
msgid "Getting image metadata from glance. Image: %s"
msgstr ""

#: ironic/conductor/manager.py:144
#, python-format
msgid ""
"A conductor with hostname %(hostname)s was previously registered. Updating "
"registration"
msgstr ""

#: ironic/conductor/manager.py:165
#, python-format
msgid "Received notification: %r"
msgstr ""

#: ironic/conductor/manager.py:188
#, python-format
msgid "RPC update_node called for node %s."
msgstr ""

#: ironic/conductor/manager.py:192
msgid "Invalid method call: update_node can not change node state."
msgstr ""

#: ironic/conductor/manager.py:233
#, python-format
msgid ""
"RPC change_node_power_state called for node %(node)s. The desired new state "
"is %(state)s."
msgstr ""

#: ironic/conductor/manager.py:272
#, python-format
msgid "RPC vendor_passthru called for node %s."
msgstr ""

#: ironic/conductor/manager.py:318
#, python-format
msgid "RPC do_node_deploy called for node %s."
msgstr ""

#: ironic/conductor/manager.py:324
#, python-format
msgid ""
"RPC do_node_deploy called for %(node)s, but provision state is already "
"%(state)s."
msgstr ""

#: ironic/conductor/manager.py:330
msgid "provisioning"
msgstr ""

#: ironic/conductor/manager.py:336
#, python-format
msgid "RPC do_node_deploy failed to validate deploy info. Error: %(msg)s"
msgstr ""

#: ironic/conductor/manager.py:363
#, python-format
msgid "Failed to deploy. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:393
#, python-format
msgid "RPC do_node_tear_down called for node %s."
msgstr ""

#: ironic/conductor/manager.py:402
#, python-format
msgid "RPC do_node_tear_down not allowed for node %(node)s in state %(state)s"
msgstr ""

#: ironic/conductor/manager.py:410
#, python-format
msgid "RPC do_node_tear_down failed to validate deploy info. Error: %(msg)s"
msgstr ""

#: ironic/conductor/manager.py:438
#, python-format
msgid "Failed to tear down. Error: %s"
msgstr ""

#: ironic/conductor/manager.py:459
#, python-format
msgid ""
"During sync_power_state, max retries exceeded for node %(node)s, node state "
"%(actual)s does not match expected state '%(state)s'. Updating DB state to "
"'%(actual)s' Switching node to maintenance mode."
msgstr ""

#: ironic/conductor/manager.py:481
#, python-format
msgid ""
"During sync_power_state, could not get power state for node %(node)s. Error:"
" %(err)s."
msgstr ""

#: ironic/conductor/manager.py:493
#, python-format
msgid ""
"During sync_power_state, node %(node)s has no previous known state. "
"Recording current state '%(state)s'."
msgstr ""

#: ironic/conductor/manager.py:506
#, python-format
msgid ""
"During sync_power_state, node %(node)s state does not match expected state "
"'%(state)s'. Updating recorded state to '%(actual)s'."
msgstr ""

#: ironic/conductor/manager.py:522
#, python-format
msgid ""
"During sync_power_state, node %(node)s state '%(actual)s' does not match "
"expected state. Changing hardware state to '%(state)s'."
msgstr ""

#: ironic/conductor/manager.py:535
#, python-format
msgid "Failed to change power state of node %(node)s to '%(state)s'."
msgstr ""

#: ironic/conductor/manager.py:540
#, python-format
msgid "%(left)s attempts remaining to sync_power_state for node %(node)s"
msgstr ""

#: ironic/conductor/manager.py:572
#, python-format
msgid ""
"During sync_power_state, node %(node)s was not found and presumed deleted by"
" another process."
msgstr ""

#: ironic/conductor/manager.py:577
#, python-format
msgid ""
"During sync_power_state, node %(node)s was already locked by another "
"process. Skip."
msgstr ""

#: ironic/conductor/manager.py:610
#, python-format
msgid "Timeout reached when waiting callback for node %s"
msgstr ""

#: ironic/conductor/manager.py:653
#, python-format
msgid "RPC validate_driver_interfaces called for node %s."
msgstr ""

#: ironic/conductor/manager.py:670
msgid "not supported"
msgstr ""

#: ironic/conductor/manager.py:689
#, python-format
msgid ""
"RPC change_node_maintenance_mode called for node %(node)s with maintanence "
"mode: %(mode)s"
msgstr ""

#: ironic/conductor/manager.py:699
msgid "The node is already in maintenance mode"
msgstr ""

#: ironic/conductor/manager.py:700
msgid "The node is not in maintenance mode"
msgstr ""

#: ironic/conductor/manager.py:743
#, python-format
msgid "Node %s can't be deleted because it's not powered off"
msgstr ""

#: ironic/conductor/manager.py:763
#, python-format
msgid "RPC get_console_information called for node %s"
msgstr ""

#: ironic/conductor/manager.py:798
#, python-format
msgid "RPC set_console_mode called for node %(node)s with enabled %(enabled)s"
msgstr ""

#: ironic/conductor/manager.py:816
msgid "enabled"
msgstr ""

#: ironic/conductor/manager.py:816
msgid "disabled"
msgstr ""

#: ironic/conductor/manager.py:817
#, python-format
msgid "No console action was triggered because the console is already %s"
msgstr ""

#: ironic/conductor/manager.py:844
msgid "enabling"
msgstr ""

#: ironic/conductor/manager.py:844
msgid "disabling"
msgstr ""

#: ironic/conductor/manager.py:845
#, python-format
msgid "Error %(op)s the console on node %(node)s. Reason: %(error)s"
msgstr ""

#: ironic/conductor/manager.py:867
#, python-format
msgid "RPC update_port called for port %s."
msgstr ""

#: ironic/conductor/manager.py:879
#, python-format
msgid ""
"No VIF found for instance %(instance)s port %(port)s when attempting to "
"update Neutron port MAC address."
msgstr ""

#: ironic/conductor/rpcapi.py:97
#, python-format
msgid "No conductor service registered which supports driver %s."
msgstr ""

#: ironic/conductor/task_manager.py:199
msgid "Multi-node TaskManager has no attribute 'node'"
msgstr ""

#: ironic/conductor/task_manager.py:208
msgid "Multi-node TaskManager has no attribute 'ports'"
msgstr ""

#: ironic/conductor/task_manager.py:217
msgid "Multi-node TaskManager has no attribute 'driver'"
msgstr ""

#: ironic/conductor/task_manager.py:226
msgid "Multi-node TaskManager can't select single node manager from the list"
msgstr ""

#: ironic/conductor/utils.py:73 ironic/conductor/utils.py:111
#, python-format
msgid "Failed to change power state to '%(target)s'. Error: %(error)s"
msgstr ""

#: ironic/conductor/utils.py:90
#, python-format
msgid ""
"Not going to change_node_power_state because current state = requested state"
" = '%(state)s'."
msgstr ""

#: ironic/conductor/utils.py:130
#, python-format
msgid "Cleanup failed for node %(node)s after deploy timeout:  %(error)s"
msgstr ""

#: ironic/conductor/utils.py:142
msgid ""
"Deploy timed out, but an unhandled exception was encountered while aborting."
" More info may be found in the log file."
msgstr ""

#: ironic/drivers/utils.py:21 ironic/drivers/modules/fake.py:34
#, python-format
msgid "Unsupported method (%s) passed through to vendor extension."
msgstr ""

#: ironic/drivers/utils.py:24 ironic/drivers/modules/fake.py:37
msgid "Method not specified when calling vendor extension."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:205
#, python-format
msgid "Parent device '%s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:210
#, python-format
msgid "Root device '%s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:213
#, python-format
msgid "Swap device '%s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:217
#, python-format
msgid "Ephemeral device '%s' not found"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:229
msgid "Failed to detect root device UUID."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:267
#: ironic/drivers/modules/deploy_utils.py:273
#, python-format
msgid "Deploy to address %s failed."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:268
#, python-format
msgid "Command: %s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:269
#, python-format
msgid "StdOut: %r"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:270
#, python-format
msgid "StdErr: %r"
msgstr ""

#: ironic/drivers/modules/fake.py:52 ironic/drivers/modules/ipminative.py:245
#, python-format
msgid "set_power_state called with an invalid power state: %s."
msgstr ""

#: ironic/drivers/modules/fake.py:92
msgid "Parameter 'bar' not passed to method 'first_method'."
msgstr ""

#: ironic/drivers/modules/fake.py:116
msgid "Parameter 'bar' not passed to method 'second_method'."
msgstr ""

#: ironic/drivers/modules/ipminative.py:59
#, python-format
msgid "The following IPMI credentials are not supplied to IPMI driver: %s."
msgstr ""

#: ironic/drivers/modules/ipminative.py:80
#, python-format
msgid ""
"IPMI power on failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:110
#, python-format
msgid ""
"IPMI power off failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:142
#, python-format
msgid ""
"IPMI power reboot failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:177
#, python-format
msgid ""
"IPMI get power state failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:191
#, python-format
msgid ""
"IPMI get power state for node %(node_id)s returns the  following details: "
"%(detail)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:284
#: ironic/drivers/modules/ipminative.py:311
#: ironic/drivers/modules/ipmitool.py:359
#: ironic/drivers/modules/ipmitool.py:376
#, python-format
msgid "Invalid boot device %s specified."
msgstr ""

#: ironic/drivers/modules/ipminative.py:293
#, python-format
msgid ""
"IPMI set boot device failed for node %(node_id)s with the following error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:314
#, python-format
msgid "Unsupported method (%s) passed to IPMINative driver."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:84
msgid "IPMI address not supplied to IPMI driver."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:89
#, python-format
msgid ""
"Invalid privilege level value:%(priv_level)s, the valid value can be one of "
"%(valid_levels)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:136
#, python-format
msgid "ipmitool stdout: '%(out)s', stderr: '%(err)s'"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:186
#, python-format
msgid "IPMI power %(state)s failed for node %(node)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:197
#, python-format
msgid "IPMI power %(state)s timed out after %(tries)s retries."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:249
#, python-format
msgid "IPMI power status failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:279
#, python-format
msgid "BMC inaccessible for node %(node)s: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:317 ironic/drivers/modules/ssh.py:436
#, python-format
msgid "set_power_state called with invalid power state %s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:379
#, python-format
msgid "Unsupported method (%s) passed to IPMItool driver."
msgstr ""

#: ironic/drivers/modules/pxe.py:106
#, python-format
msgid ""
"Can not validate PXE bootloader. The following parameters were not passed to"
" ironic: %s"
msgstr ""

#: ironic/drivers/modules/pxe.py:118
#, python-format
msgid ""
"Can not validate PXE bootloader. Invalid parameter pxe_%(param)s. Reason: "
"%(reason)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:124
#, python-format
msgid "'%s' is not an integer value."
msgstr ""

#: ironic/drivers/modules/pxe.py:135
msgid ""
"The deploy contains an ephemeral partition, but no filesystem type was "
"specified by the pxe_ephemeral_format parameter"
msgstr ""

#: ironic/drivers/modules/pxe.py:162
#, python-format
msgid "Building PXE config for deployment %s."
msgstr ""

#: ironic/drivers/modules/pxe.py:363
#, python-format
msgid "Fetching kernel and ramdisk for node %s"
msgstr ""

#: ironic/drivers/modules/pxe.py:393
#, python-format
msgid "Fetching image %(ami)s for node %(uuid)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:491
#, python-format
msgid ""
"No VIFs found for node %(node)s when attempting to update Neutron DHCP BOOT "
"options."
msgstr ""

#: ironic/drivers/modules/pxe.py:510
#, python-format
msgid "Failed to set DHCP BOOT options for any port on node %s."
msgstr ""

#: ironic/drivers/modules/pxe.py:514
#, python-format
msgid ""
"Some errors were encountered when updating the DHCP BOOT options for node "
"%(node)s on the following ports: %(ports)s."
msgstr ""

#: ironic/drivers/modules/pxe.py:549 ironic/drivers/modules/ssh.py:381
#, python-format
msgid "Node %s does not have any port associated with it."
msgstr ""

#: ironic/drivers/modules/pxe.py:560
msgid ""
"Couldn't get the URL of the Ironic API service from the configuration file "
"or keystone catalog."
msgstr ""

#: ironic/drivers/modules/pxe.py:670
msgid "Deploy key is not match"
msgstr ""

#: ironic/drivers/modules/pxe.py:687
#, python-format
msgid "Parameters %s were not passed to ironic for deploy."
msgstr ""

#: ironic/drivers/modules/pxe.py:701
#, python-format
msgid "Unsupported method (%s) passed to PXE driver."
msgstr ""

#: ironic/drivers/modules/pxe.py:722
#, python-format
msgid ""
"Node %s failed to power off while handling deploy failure. This may be a "
"serious condition. Node should be removed from Ironic or put in maintenance "
"mode until the problem is resolved."
msgstr ""

#: ironic/drivers/modules/pxe.py:734
#, python-format
msgid "Node %s is not waiting to be deployed."
msgstr ""

#: ironic/drivers/modules/pxe.py:746
#, python-format
msgid "Error returned from PXE deploy ramdisk: %s"
msgstr ""

#: ironic/drivers/modules/pxe.py:748
msgid "Failure in PXE deploy ramdisk."
msgstr ""

#: ironic/drivers/modules/pxe.py:751
#, python-format
msgid "Continuing deployment for node %(node)s, params %(params)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:757
#, python-format
msgid "PXE deploy failed for instance %(instance)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:760
msgid "PXE driver failed to continue deployment."
msgstr ""

#: ironic/drivers/modules/pxe.py:762
#, python-format
msgid "Deployment to node %s done"
msgstr ""

#: ironic/drivers/modules/seamicro.py:91
msgid "SeaMicro driver requires api_endpoint be set"
msgstr ""

#: ironic/drivers/modules/seamicro.py:95
msgid "SeaMicro driver requires both username and password be set"
msgstr ""

#: ironic/drivers/modules/seamicro.py:99
msgid "SeaMicro driver requires server_id be set"
msgstr ""

#: ironic/drivers/modules/seamicro.py:149
#, python-format
msgid "SeaMicro client exception %(msg)s for node %(uuid)s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:184
#, python-format
msgid "Power-on failed for node %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:223
#, python-format
msgid "Power-off failed for node %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:262
#, python-format
msgid "Reboot failed for node %s."
msgstr ""

#: ironic/drivers/modules/seamicro.py:287
msgid "Invalid volume id specified"
msgstr ""

#: ironic/drivers/modules/seamicro.py:303
msgid "No storage pools found for ironic"
msgstr ""

#: ironic/drivers/modules/seamicro.py:363
msgid "set_power_state called with invalid power state."
msgstr ""

#: ironic/drivers/modules/seamicro.py:394
#, python-format
msgid "Unsupported method (%s) passed to SeaMicro driver."
msgstr ""

#: ironic/drivers/modules/seamicro.py:412
msgid "No vlan id provided"
msgstr ""

#: ironic/drivers/modules/seamicro.py:424
#: ironic/drivers/modules/seamicro.py:459
#, python-format
msgid "SeaMicro client exception: %s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:449
msgid "No volume size provided for creating volume"
msgstr ""

#: ironic/drivers/modules/seamicro.py:475
msgid "No boot device provided"
msgstr ""

#: ironic/drivers/modules/seamicro.py:478
msgid "Boot device is invalid"
msgstr ""

#: ironic/drivers/modules/seamicro.py:488
#, python-format
msgid "set_boot_device error:  %s"
msgstr ""

#: ironic/drivers/modules/ssh.py:115
#, python-format
msgid "SSHPowerDriver '%(virt_type)s' is not a valid virt_type, "
msgstr ""

#: ironic/drivers/modules/ssh.py:140
#, python-format
msgid "Cannot execute SSH cmd %(cmd)s. Reason: %(err)s."
msgstr ""

#: ironic/drivers/modules/ssh.py:163
msgid "SSHPowerDriver requires ssh_port to be integer value"
msgstr ""

#: ironic/drivers/modules/ssh.py:179
msgid "SSHPowerDriver requires virt_type be set."
msgstr ""

#: ironic/drivers/modules/ssh.py:186
msgid "SSHPowerDriver requires both address and username be set."
msgstr ""

#: ironic/drivers/modules/ssh.py:191
msgid ""
"SSHPowerDriver requires one and only one of password, key_contents and "
"key_filename to be set."
msgstr ""

#: ironic/drivers/modules/ssh.py:200
#, python-format
msgid "SSH key file %s not found."
msgstr ""

#: ironic/drivers/modules/ssh.py:233
#, python-format
msgid "Node \"%(host)s\" with MAC address %(mac)s not found."
msgstr ""

#: ironic/drivers/modules/ssh.py:264
#, python-format
msgid "Retrieved Node List: %s"
msgstr ""

#: ironic/drivers/modules/ssh.py:269
#, python-format
msgid "Checking Node: %s's Mac address."
msgstr ""

#: ironic/drivers/modules/ssh.py:282
#, python-format
msgid "Found Mac address: %s"
msgstr ""

#: ironic/drivers/modules/ssh.py:386
#, python-format
msgid "SSH connection cannot be established: %s"
msgstr ""

#: ironic/nova/scheduler/filters/exact_core_filter.py:35
msgid "VCPUs not set; assuming CPU collection broken"
msgstr ""

#: ironic/nova/scheduler/filters/exact_core_filter.py:42
#, python-format
msgid ""
"%(host_state)s does not have %(requested_vcpus)s cores of usable vcpu, it "
"only has %(usable_vcpus)s cores of usable vcpu."
msgstr ""

#: ironic/nova/scheduler/filters/exact_disk_filter.py:34
#, python-format
msgid ""
"%(host_state)s does not have %(requested_disk)s MB usable disk, it only has "
"%(usable_disk_mb)s MB usable disk."
msgstr ""

#: ironic/nova/scheduler/filters/exact_ram_filter.py:30
#, python-format
msgid ""
"%(host_state)s does not have %(requested_ram)s MB usable ram, it only has "
"%(usable_ram)s MB usable ram."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:96
msgid "Maximum number of retries reached."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:103
#, python-format
msgid "Power state %s not found."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:261
#, python-format
msgid ""
"Adding the parameter %(param)s on node %(node)s failed after %(retries)d "
"retries"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:285
#, python-format
msgid ""
"Removing the parameter %(param)s on node %(node)s failed after %(retries)d "
"retries"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:314
msgid "Unable to authenticate Ironic client."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:383
#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:399
#, python-format
msgid "Unable to set instance UUID for node %s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:414
#, python-format
msgid ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:427
#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node %(node)s."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:438
#, python-format
msgid "Error triggering the node %s to start the deployment"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:465
#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:481
#, python-format
msgid "Destroy called on non-existing instance %s."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:494
#, python-format
msgid "Error triggering the unprovisioning of the node %s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:518
#, python-format
msgid ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."
msgstr ""

#: ironic/nova/virt/ironic/driver.py:536
#, python-format
msgid "Failed to unassociate the instance %(instance)s with node %(node)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:619
#, python-format
msgid "plug: instance_uuid=%(uuid)s vif=%(network_info)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:628
#, python-format
msgid ""
"Ironic node: %(id)s virtual to physical interface count  missmatch (Vif "
"count: %(vif_count)d, Pif count: %(pif_count)d)"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:648
#, python-format
msgid "Failed to set the VIF networking for port %s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:653
#, python-format
msgid "unplug: instance_uuid=%(uuid)s vif=%(network_info)s"
msgstr ""

#: ironic/nova/virt/ironic/driver.py:667
#, python-format
msgid "Failed to remove the VIF networking for port %s"
msgstr ""

#: ironic/objects/base.py:54
#, python-format
msgid "Error setting %(attr)s"
msgstr ""

#: ironic/objects/base.py:145
msgid "Invalid version string"
msgstr ""

#: ironic/objects/base.py:200
#, python-format
msgid "Unable to instantiate unregistered object type %(objtype)s"
msgstr ""

#: ironic/objects/base.py:301
#, python-format
msgid "Cannot load '%(attrname)s' in the base class"
msgstr ""

#: ironic/objects/base.py:310
msgid "Cannot save anything in the base class"
msgstr ""

#: ironic/objects/conductor.py:54
msgid "Cannot update a conductor record directly."
msgstr ""

#: ironic/objects/utils.py:39
msgid "A datetime.datetime is required here"
msgstr ""

#: ironic/objects/utils.py:104
#, python-format
msgid "An object of class %s is required here"
msgstr ""

#: ironic/openstack/common/excutils.py:64
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: ironic/openstack/common/excutils.py:93
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: ironic/openstack/common/gettextutils.py:297
msgid "Message objects do not support addition."
msgstr ""

#: ironic/openstack/common/gettextutils.py:306
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: ironic/openstack/common/lockutils.py:105
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: ironic/openstack/common/lockutils.py:170
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: ironic/openstack/common/lockutils.py:179
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: ironic/openstack/common/lockutils.py:189
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: ironic/openstack/common/lockutils.py:207
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: ironic/openstack/common/lockutils.py:211
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: ironic/openstack/common/lockutils.py:249
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: ironic/openstack/common/lockutils.py:253
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: ironic/openstack/common/log.py:303
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: ironic/openstack/common/log.py:402
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: ironic/openstack/common/log.py:453
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: ironic/openstack/common/log.py:623
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: ironic/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: ironic/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: ironic/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: ironic/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: ironic/openstack/common/periodic_task.py:43
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr ""

#: ironic/openstack/common/periodic_task.py:134
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr ""

#: ironic/openstack/common/periodic_task.py:139
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr ""

#: ironic/openstack/common/periodic_task.py:177
#, python-format
msgid "Running periodic task %(full_task_name)s"
msgstr ""

#: ironic/openstack/common/periodic_task.py:186
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: ironic/openstack/common/policy.py:395
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: ironic/openstack/common/policy.py:405
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: ironic/openstack/common/policy.py:680
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: ironic/openstack/common/processutils.py:127
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: ironic/openstack/common/processutils.py:142
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: ironic/openstack/common/processutils.py:167
#: ironic/openstack/common/processutils.py:240
#, python-format
msgid "Result was %s"
msgstr ""

#: ironic/openstack/common/processutils.py:179
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: ironic/openstack/common/processutils.py:219
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: ironic/openstack/common/processutils.py:221
msgid "Environment not supported over SSH"
msgstr ""

#: ironic/openstack/common/processutils.py:225
msgid "process_input not supported over SSH"
msgstr ""

#: ironic/openstack/common/service.py:166
#: ironic/openstack/common/service.py:384
msgid "Full set of CONF:"
msgstr ""

#: ironic/openstack/common/service.py:175
#: ironic/openstack/common/service.py:269
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: ironic/openstack/common/service.py:187
msgid "Exception during rpc cleanup."
msgstr ""

#: ironic/openstack/common/service.py:238
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: ironic/openstack/common/service.py:275
msgid "Unhandled exception"
msgstr ""

#: ironic/openstack/common/service.py:308
msgid "Forking too fast, sleeping"
msgstr ""

#: ironic/openstack/common/service.py:327
#, python-format
msgid "Started child %d"
msgstr ""

#: ironic/openstack/common/service.py:337
#, python-format
msgid "Starting %d workers"
msgstr ""

#: ironic/openstack/common/service.py:354
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: ironic/openstack/common/service.py:358
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: ironic/openstack/common/service.py:362
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: ironic/openstack/common/service.py:392
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: ironic/openstack/common/service.py:410
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: ironic/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: ironic/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: ironic/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: ironic/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: ironic/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: ironic/openstack/common/strutils.py:88
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: ironic/openstack/common/strutils.py:184
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: ironic/openstack/common/strutils.py:191
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: ironic/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/migration.py:188
msgid "version should be an integer"
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/migration.py:216
#, python-format
msgid ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/migration.py:240
msgid ""
"The database is not under version control, but has tables. Please stamp the "
"current version of the schema manually."
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:164
#, python-format
msgid ""
"There is no `deleted` column in `%s` table. Project doesn't use soft-deleted"
" feature."
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:176
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:183
#, python-format
msgid "There is no `project_id` column in `%s` table."
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:241
msgid "model should be a subclass of ModelBase"
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:284
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:290
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column %s "
"It should be instance of sqlalchemy.Column."
msgstr ""

#: ironic/openstack/common/db/sqlalchemy/utils.py:391
msgid "Unsupported id columns type"
msgstr ""

#: ironic/openstack/common/notifier/api.py:129
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: ironic/openstack/common/notifier/api.py:145
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: ironic/openstack/common/notifier/api.py:164
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: ironic/openstack/common/notifier/rpc_notifier.py:45
#: ironic/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:75
msgid "Pool creating new connection"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:202
#, python-format
msgid "No calling threads waiting for msg_id : %(msg_id)s, message : %(data)s"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:205
#, python-format
msgid "_call_waiters: %s"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:212
#, python-format
msgid ""
"Number of call waiters is greater than warning threshold: %d. There could be"
" a MulticallProxyWaiter leak."
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:290
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:342
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:435
#, python-format
msgid "received %s"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:443
#, python-format
msgid "no method for message: %s"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:444
#, python-format
msgid "No method for message: %s"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:472
#: ironic/openstack/common/rpc/impl_zmq.py:280
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:480
#: ironic/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:554
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:557
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:583
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:592
msgid "Making asynchronous fanout cast..."
msgstr ""

#: ironic/openstack/common/rpc/amqp.py:620
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: ironic/openstack/common/rpc/common.py:76
msgid "An unknown RPC related exception occurred."
msgstr ""

#: ironic/openstack/common/rpc/common.py:106
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: ironic/openstack/common/rpc/common.py:123
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method: "
"\"%(method)s\" info: \"%(info)s\""
msgstr ""

#: ironic/openstack/common/rpc/common.py:140
#: ironic/openstack/common/rpc/common.py:141
#: ironic/openstack/common/rpc/common.py:142
msgid "<unknown>"
msgstr ""

#: ironic/openstack/common/rpc/common.py:146
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: ironic/openstack/common/rpc/common.py:150
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: ironic/openstack/common/rpc/common.py:154
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: ironic/openstack/common/rpc/common.py:159
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this endpoint."
msgstr ""

#: ironic/openstack/common/rpc/common.py:164
#, python-format
msgid "Specified RPC version cap, %(version_cap)s, is too low"
msgstr ""

#: ironic/openstack/common/rpc/common.py:292
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:156
msgid "Failed to process message ... skipping it."
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:160
msgid "Failed to process message ... will requeue."
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:495
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:517
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:554
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:568
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:622
#: ironic/openstack/common/rpc/impl_qpid.py:573
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:640
#: ironic/openstack/common/rpc/impl_qpid.py:588
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:644
#: ironic/openstack/common/rpc/impl_qpid.py:592
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_kombu.py:683
#: ironic/openstack/common/rpc/impl_qpid.py:627
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: ironic/openstack/common/rpc/impl_qpid.py:87
#, python-format
msgid "Invalid value for qpid_topology_version: %d"
msgstr ""

#: ironic/openstack/common/rpc/impl_qpid.py:191
msgid "Failed to process message... skipping it."
msgstr ""

#: ironic/openstack/common/rpc/impl_qpid.py:515
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: ironic/openstack/common/rpc/impl_qpid.py:521
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_qpid.py:534
msgid "Re-established AMQP queues"
msgstr ""

#: ironic/openstack/common/rpc/impl_qpid.py:600
msgid "Error processing message.  Skipping it."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:101
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:136
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:137
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:138
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:146
msgid "Could not open socket."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:158
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:195
msgid "ZeroMQ socket could not be closed."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:200
msgid "You cannot recv on this socket."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:205
msgid "You cannot send on this socket."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:267
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:305
msgid "Sending reply"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:371
msgid "Registering reactor"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:383
msgid "In reactor registered"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:388
msgid "Consuming socket"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:438
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:444
msgid "Topic contained dangerous characters."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:476
msgid "Topic socket file creation failed."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:482
#, python-format
msgid ""
"Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:498
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:507
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:510
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:544
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:563
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:591
msgid "Skipping topic registration. Already registered."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:598
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:650
msgid "Creating payload"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:663
msgid "Creating queue socket for reply waiter"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:676
msgid "Sending cast"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:679
msgid "Cast sent; Waiting reply"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:682
#, python-format
msgid "Received message: %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:683
msgid "Unpacking response"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:692
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:699
msgid "RPC Message Invalid."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:722
#, python-format
msgid "%(msg)s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:725
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:729
msgid "No matchmaker results. Not casting."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:732
msgid "No match from matchmaker."
msgstr ""

#: ironic/openstack/common/rpc/impl_zmq.py:814
#, python-format
msgid "rpc_zmq_matchmaker = %(orig)s is deprecated; use %(new)s instead"
msgstr ""

#: ironic/openstack/common/rpc/matchmaker.py:46
msgid "Match not found by MatchMaker."
msgstr ""

#: ironic/openstack/common/rpc/matchmaker.py:80
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: ironic/openstack/common/rpc/matchmaker.py:216
#, python-format
msgid "Matchmaker unregistered: %(key)s, %(host)s"
msgstr ""

#: ironic/openstack/common/rpc/matchmaker.py:228
msgid "Register before starting heartbeat."
msgstr ""

#: ironic/openstack/common/rpc/matchmaker_ring.py:75
#: ironic/openstack/common/rpc/matchmaker_ring.py:93
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: ironic/openstack/common/rpc/service.py:47
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: ironic/tests/db/sqlalchemy/test_migrations.py:312
#, python-format
msgid "Failed to migrate to version %(version)s on engine %(engine)s"
msgstr ""
